# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_rpt_builder.ui'
#
# Created: Sun Jun 08 13:58:36 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ReportBuilder(object):
    def setupUi(self, ReportBuilder):
        ReportBuilder.setObjectName(_fromUtf8("ReportBuilder"))
        ReportBuilder.resize(656, 523)
        self.gridLayout = QtGui.QGridLayout(ReportBuilder)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(ReportBuilder)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setMinimumSize(QtCore.QSize(0, 30))
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout_2.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.tab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 0, 2, 1, 1)
        self.listWidget = QtGui.QListWidget(self.groupBox_2)
        self.listWidget.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        self.gridLayout_4.addWidget(self.listWidget, 1, 0, 1, 1)
        self.listWidget_2 = QtGui.QListWidget(self.groupBox_2)
        self.listWidget_2.setObjectName(_fromUtf8("listWidget_2"))
        self.gridLayout_4.addWidget(self.listWidget_2, 1, 2, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setFlat(True)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.btnAddField = QtGui.QPushButton(self.groupBox_3)
        self.btnAddField.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/next.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddField.setIcon(icon)
        self.btnAddField.setObjectName(_fromUtf8("btnAddField"))
        self.verticalLayout.addWidget(self.btnAddField)
        self.btnRemField = QtGui.QPushButton(self.groupBox_3)
        self.btnRemField.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/previous.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRemField.setIcon(icon1)
        self.btnRemField.setObjectName(_fromUtf8("btnRemField"))
        self.verticalLayout.addWidget(self.btnRemField)
        self.btnAddAllFields = QtGui.QPushButton(self.groupBox_3)
        self.btnAddAllFields.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/last.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddAllFields.setIcon(icon2)
        self.btnAddAllFields.setObjectName(_fromUtf8("btnAddAllFields"))
        self.verticalLayout.addWidget(self.btnAddAllFields)
        self.btnRemAllFields = QtGui.QPushButton(self.groupBox_3)
        self.btnRemAllFields.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/first.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRemAllFields.setIcon(icon3)
        self.btnRemAllFields.setObjectName(_fromUtf8("btnRemAllFields"))
        self.verticalLayout.addWidget(self.btnRemAllFields)
        self.gridLayout_4.addWidget(self.groupBox_3, 1, 1, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.groupBox_2)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setFlat(True)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.btnRptFieldUp = QtGui.QPushButton(self.groupBox_4)
        self.btnRptFieldUp.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRptFieldUp.setIcon(icon4)
        self.btnRptFieldUp.setObjectName(_fromUtf8("btnRptFieldUp"))
        self.verticalLayout_2.addWidget(self.btnRptFieldUp)
        self.btnRptFieldDwn = QtGui.QPushButton(self.groupBox_4)
        self.btnRptFieldDwn.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRptFieldDwn.setIcon(icon5)
        self.btnRptFieldDwn.setObjectName(_fromUtf8("btnRptFieldDwn"))
        self.verticalLayout_2.addWidget(self.btnRptFieldDwn)
        self.gridLayout_4.addWidget(self.groupBox_4, 1, 3, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_7.addWidget(self.label_4, 0, 0, 1, 2)
        self.groupBox_5 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lstFields = QtGui.QListWidget(self.groupBox_5)
        self.lstFields.setObjectName(_fromUtf8("lstFields"))
        self.gridLayout_6.addWidget(self.lstFields, 0, 0, 1, 1)
        self.lstUniqVal = QtGui.QListWidget(self.groupBox_5)
        self.lstUniqVal.setObjectName(_fromUtf8("lstUniqVal"))
        self.gridLayout_6.addWidget(self.lstUniqVal, 0, 1, 1, 1)
        self.btnUniqVals = QtGui.QPushButton(self.groupBox_5)
        self.btnUniqVals.setObjectName(_fromUtf8("btnUniqVals"))
        self.gridLayout_6.addWidget(self.btnUniqVals, 1, 1, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_5, 1, 0, 1, 6)
        self.groupBox_6 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.btnOpEqual = QtGui.QPushButton(self.groupBox_6)
        self.btnOpEqual.setMinimumSize(QtCore.QSize(0, 30))
        self.btnOpEqual.setObjectName(_fromUtf8("btnOpEqual"))
        self.gridLayout_5.addWidget(self.btnOpEqual, 0, 0, 1, 1)
        self.btnOpNotEqual = QtGui.QPushButton(self.groupBox_6)
        self.btnOpNotEqual.setMinimumSize(QtCore.QSize(0, 30))
        self.btnOpNotEqual.setObjectName(_fromUtf8("btnOpNotEqual"))
        self.gridLayout_5.addWidget(self.btnOpNotEqual, 0, 1, 1, 1)
        self.btnOpLike = QtGui.QPushButton(self.groupBox_6)
        self.btnOpLike.setMinimumSize(QtCore.QSize(0, 30))
        self.btnOpLike.setObjectName(_fromUtf8("btnOpLike"))
        self.gridLayout_5.addWidget(self.btnOpLike, 0, 2, 1, 1)
        self.btnOpGreater = QtGui.QPushButton(self.groupBox_6)
        self.btnOpGreater.setMinimumSize(QtCore.QSize(0, 30))
        self.btnOpGreater.setObjectName(_fromUtf8("btnOpGreater"))
        self.gridLayout_5.addWidget(self.btnOpGreater, 1, 0, 1, 1)
        self.btnOpGreaterEq = QtGui.QPushButton(self.groupBox_6)
        self.btnOpGreaterEq.setMinimumSize(QtCore.QSize(0, 30))
        self.btnOpGreaterEq.setObjectName(_fromUtf8("btnOpGreaterEq"))
        self.gridLayout_5.addWidget(self.btnOpGreaterEq, 1, 1, 1, 1)
        self.btnOpAnd = QtGui.QPushButton(self.groupBox_6)
        self.btnOpAnd.setMinimumSize(QtCore.QSize(0, 30))
        self.btnOpAnd.setObjectName(_fromUtf8("btnOpAnd"))
        self.gridLayout_5.addWidget(self.btnOpAnd, 1, 2, 1, 1)
        self.btnOpLess = QtGui.QPushButton(self.groupBox_6)
        self.btnOpLess.setMinimumSize(QtCore.QSize(0, 30))
        self.btnOpLess.setObjectName(_fromUtf8("btnOpLess"))
        self.gridLayout_5.addWidget(self.btnOpLess, 2, 0, 1, 1)
        self.btnOpLess_2 = QtGui.QPushButton(self.groupBox_6)
        self.btnOpLess_2.setMinimumSize(QtCore.QSize(0, 30))
        self.btnOpLess_2.setObjectName(_fromUtf8("btnOpLess_2"))
        self.gridLayout_5.addWidget(self.btnOpLess_2, 2, 1, 1, 1)
        self.btnOpOr = QtGui.QPushButton(self.groupBox_6)
        self.btnOpOr.setMinimumSize(QtCore.QSize(0, 30))
        self.btnOpOr.setObjectName(_fromUtf8("btnOpOr"))
        self.gridLayout_5.addWidget(self.btnOpOr, 2, 2, 1, 1)
        self.gridLayout_7.addWidget(self.groupBox_6, 2, 0, 2, 1)
        self.lblSqlEntity = QtGui.QLabel(self.tab_2)
        self.lblSqlEntity.setObjectName(_fromUtf8("lblSqlEntity"))
        self.gridLayout_7.addWidget(self.lblSqlEntity, 2, 1, 1, 5)
        self.txtSqlParser = QtGui.QTextEdit(self.tab_2)
        self.txtSqlParser.setObjectName(_fromUtf8("txtSqlParser"))
        self.gridLayout_7.addWidget(self.txtSqlParser, 3, 1, 1, 5)
        self.btnSQLClr = QtGui.QPushButton(self.tab_2)
        self.btnSQLClr.setMinimumSize(QtCore.QSize(0, 30))
        self.btnSQLClr.setObjectName(_fromUtf8("btnSQLClr"))
        self.gridLayout_7.addWidget(self.btnSQLClr, 4, 1, 1, 1)
        self.btnSQLVer = QtGui.QPushButton(self.tab_2)
        self.btnSQLVer.setMinimumSize(QtCore.QSize(0, 30))
        self.btnSQLVer.setObjectName(_fromUtf8("btnSQLVer"))
        self.gridLayout_7.addWidget(self.btnSQLVer, 4, 2, 1, 1)
        self.btnMap = QtGui.QPushButton(self.tab_2)
        self.btnMap.setMinimumSize(QtCore.QSize(0, 30))
        self.btnMap.setObjectName(_fromUtf8("btnMap"))
        self.gridLayout_7.addWidget(self.btnMap, 4, 4, 1, 1)
        self.btnSQLApply = QtGui.QPushButton(self.tab_2)
        self.btnSQLApply.setMinimumSize(QtCore.QSize(0, 30))
        self.btnSQLApply.setObjectName(_fromUtf8("btnSQLApply"))
        self.gridLayout_7.addWidget(self.btnSQLApply, 4, 3, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_5 = QtGui.QLabel(self.tab_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_8.addWidget(self.label_5, 0, 0, 1, 1)
        self.lstRptFields = QtGui.QListWidget(self.tab_3)
        self.lstRptFields.setObjectName(_fromUtf8("lstRptFields"))
        self.gridLayout_8.addWidget(self.lstRptFields, 1, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_7.setTitle(_fromUtf8(""))
        self.groupBox_7.setFlat(True)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_7)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.btnAddGpField = QtGui.QPushButton(self.groupBox_7)
        self.btnAddGpField.setText(_fromUtf8(""))
        self.btnAddGpField.setIcon(icon)
        self.btnAddGpField.setObjectName(_fromUtf8("btnAddGpField"))
        self.verticalLayout_3.addWidget(self.btnAddGpField)
        self.btnRemGpField = QtGui.QPushButton(self.groupBox_7)
        self.btnRemGpField.setText(_fromUtf8(""))
        self.btnRemGpField.setIcon(icon1)
        self.btnRemGpField.setObjectName(_fromUtf8("btnRemGpField"))
        self.verticalLayout_3.addWidget(self.btnRemGpField)
        self.gridLayout_8.addWidget(self.groupBox_7, 1, 1, 1, 1)
        self.tbGroupFields = QtGui.QTableWidget(self.tab_3)
        self.tbGroupFields.setObjectName(_fromUtf8("tbGroupFields"))
        self.tbGroupFields.setColumnCount(1)
        self.tbGroupFields.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbGroupFields.setHorizontalHeaderItem(0, item)
        self.tbGroupFields.horizontalHeader().setDefaultSectionSize(95)
        self.tbGroupFields.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_8.addWidget(self.tbGroupFields, 1, 2, 1, 1)
        self.chIncludeGpFields = QtGui.QCheckBox(self.tab_3)
        self.chIncludeGpFields.setObjectName(_fromUtf8("chIncludeGpFields"))
        self.gridLayout_8.addWidget(self.chIncludeGpFields, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab_4)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_6 = QtGui.QLabel(self.tab_4)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_4.addWidget(self.label_6)
        self.tbSortFields = QtGui.QTableWidget(self.tab_4)
        self.tbSortFields.setObjectName(_fromUtf8("tbSortFields"))
        self.tbSortFields.setColumnCount(3)
        self.tbSortFields.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tbSortFields.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tbSortFields.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.tbSortFields.setHorizontalHeaderItem(2, item)
        self.tbSortFields.horizontalHeader().setDefaultSectionSize(130)
        self.tbSortFields.horizontalHeader().setHighlightSections(False)
        self.tbSortFields.horizontalHeader().setStretchLastSection(True)
        self.verticalLayout_4.addWidget(self.tbSortFields)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_7 = QtGui.QLabel(self.tab_5)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_9.addWidget(self.label_7, 0, 0, 1, 1)
        self.trRptSettings = QtGui.QTreeWidget(self.tab_5)
        self.trRptSettings.setObjectName(_fromUtf8("trRptSettings"))
        item_0 = QtGui.QTreeWidgetItem(self.trRptSettings)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_1 = QtGui.QTreeWidgetItem(item_0)
        item_0 = QtGui.QTreeWidgetItem(self.trRptSettings)
        item_0 = QtGui.QTreeWidgetItem(self.trRptSettings)
        self.trRptSettings.header().setVisible(False)
        self.gridLayout_9.addWidget(self.trRptSettings, 1, 0, 1, 1)
        self.stackedWidget = QtGui.QStackedWidget(self.tab_5)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.gridLayout_9.addWidget(self.stackedWidget, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 4)
        self.btnLoad = QtGui.QPushButton(ReportBuilder)
        self.btnLoad.setMinimumSize(QtCore.QSize(0, 30))
        self.btnLoad.setObjectName(_fromUtf8("btnLoad"))
        self.gridLayout.addWidget(self.btnLoad, 1, 0, 1, 1)
        self.btnRptCancel = QtGui.QPushButton(ReportBuilder)
        self.btnRptCancel.setMinimumSize(QtCore.QSize(0, 30))
        self.btnRptCancel.setObjectName(_fromUtf8("btnRptCancel"))
        self.gridLayout.addWidget(self.btnRptCancel, 1, 3, 1, 1)
        self.btnGenRpt = QtGui.QPushButton(ReportBuilder)
        self.btnGenRpt.setMinimumSize(QtCore.QSize(0, 30))
        self.btnGenRpt.setObjectName(_fromUtf8("btnGenRpt"))
        self.gridLayout.addWidget(self.btnGenRpt, 1, 2, 1, 1)
        self.btnSave = QtGui.QPushButton(ReportBuilder)
        self.btnSave.setMinimumSize(QtCore.QSize(0, 30))
        self.btnSave.setObjectName(_fromUtf8("btnSave"))
        self.gridLayout.addWidget(self.btnSave, 1, 1, 1, 1)

        self.retranslateUi(ReportBuilder)
        self.tabWidget.setCurrentIndex(0)
        self.stackedWidget.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(ReportBuilder)

    def retranslateUi(self, ReportBuilder):
        ReportBuilder.setWindowTitle(_translate("ReportBuilder", "STDM Report Builder", None))
        self.label.setText(_translate("ReportBuilder", "Entity", None))
        self.groupBox_2.setTitle(_translate("ReportBuilder", "Report Contents Fields:", None))
        self.label_2.setText(_translate("ReportBuilder", "Available Fields:", None))
        self.label_3.setText(_translate("ReportBuilder", "Report Fields:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("ReportBuilder", "Fields", None))
        self.label_4.setText(_translate("ReportBuilder", "Enter a WHERE clause to select records that will be appended to the report.", None))
        self.groupBox_5.setTitle(_translate("ReportBuilder", "Report Fields", None))
        self.btnUniqVals.setText(_translate("ReportBuilder", "Get Unique Values", None))
        self.groupBox_6.setTitle(_translate("ReportBuilder", "Operators:", None))
        self.btnOpEqual.setText(_translate("ReportBuilder", "=", None))
        self.btnOpNotEqual.setText(_translate("ReportBuilder", "<>", None))
        self.btnOpLike.setText(_translate("ReportBuilder", "LIKE", None))
        self.btnOpGreater.setText(_translate("ReportBuilder", ">", None))
        self.btnOpGreaterEq.setText(_translate("ReportBuilder", ">=", None))
        self.btnOpAnd.setText(_translate("ReportBuilder", "AND", None))
        self.btnOpLess.setText(_translate("ReportBuilder", "<", None))
        self.btnOpLess_2.setText(_translate("ReportBuilder", "<=", None))
        self.btnOpOr.setText(_translate("ReportBuilder", "OR", None))
        self.lblSqlEntity.setText(_translate("ReportBuilder", "Select * FROM [ENTITY] WHERE:", None))
        self.btnSQLClr.setText(_translate("ReportBuilder", "Clear", None))
        self.btnSQLVer.setText(_translate("ReportBuilder", "Verify", None))
        self.btnMap.setText(_translate("ReportBuilder", "Show on Map", None))
        self.btnSQLApply.setText(_translate("ReportBuilder", "Apply", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("ReportBuilder", "Filter", None))
        self.label_5.setText(_translate("ReportBuilder", "Report Fields:", None))
        item = self.tbGroupFields.horizontalHeaderItem(0)
        item.setText(_translate("ReportBuilder", "Fields", None))
        self.chIncludeGpFields.setText(_translate("ReportBuilder", "Include Group Fields", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("ReportBuilder", "Grouping", None))
        self.label_6.setText(_translate("ReportBuilder", "Sort records by a maximum of three fields in either ascending or descending order.", None))
        item = self.tbSortFields.horizontalHeaderItem(0)
        item.setText(_translate("ReportBuilder", "Fields", None))
        item = self.tbSortFields.horizontalHeaderItem(1)
        item.setText(_translate("ReportBuilder", "Sort", None))
        item = self.tbSortFields.horizontalHeaderItem(2)
        item.setText(_translate("ReportBuilder", "Order", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("ReportBuilder", "Sorting", None))
        self.label_7.setText(_translate("ReportBuilder", "Settings:", None))
        self.trRptSettings.headerItem().setText(0, _translate("ReportBuilder", "1", None))
        __sortingEnabled = self.trRptSettings.isSortingEnabled()
        self.trRptSettings.setSortingEnabled(False)
        self.trRptSettings.topLevelItem(0).setText(0, _translate("ReportBuilder", "Elements", None))
        self.trRptSettings.topLevelItem(0).child(0).setText(0, _translate("ReportBuilder", "Title", None))
        self.trRptSettings.topLevelItem(0).child(1).setText(0, _translate("ReportBuilder", "Subtitle", None))
        self.trRptSettings.topLevelItem(0).child(2).setText(0, _translate("ReportBuilder", "Field Names", None))
        self.trRptSettings.topLevelItem(0).child(3).setText(0, _translate("ReportBuilder", "Date", None))
        self.trRptSettings.topLevelItem(0).child(4).setText(0, _translate("ReportBuilder", "Page Numbering", None))
        self.trRptSettings.topLevelItem(1).setText(0, _translate("ReportBuilder", "Fields", None))
        self.trRptSettings.topLevelItem(2).setText(0, _translate("ReportBuilder", "Groups", None))
        self.trRptSettings.setSortingEnabled(__sortingEnabled)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("ReportBuilder", "Display", None))
        self.btnLoad.setText(_translate("ReportBuilder", "Load...", None))
        self.btnRptCancel.setText(_translate("ReportBuilder", "Cancel", None))
        self.btnGenRpt.setText(_translate("ReportBuilder", "Generate Report", None))
        self.btnSave.setText(_translate("ReportBuilder", "Save", None))
