# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_first_examination.ui'
#
# Created: Wed Jul 10 15:41:52 2019
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FirstExam_Wzd(object):
    def setupUi(self, FirstExam_Wzd):
        FirstExam_Wzd.setObjectName(_fromUtf8("FirstExam_Wzd"))
        FirstExam_Wzd.resize(817, 550)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(FirstExam_Wzd.sizePolicy().hasHeightForWidth())
        FirstExam_Wzd.setSizePolicy(sizePolicy)
        FirstExam_Wzd.setWizardStyle(QtGui.QWizard.ModernStyle)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.wizardPage1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.title_frame = QtGui.QFrame(self.wizardPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_frame.sizePolicy().hasHeightForWidth())
        self.title_frame.setSizePolicy(sizePolicy)
        self.title_frame.setMinimumSize(QtCore.QSize(0, 40))
        self.title_frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.title_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.title_frame.setObjectName(_fromUtf8("title_frame"))
        self.title_label = QtGui.QLabel(self.title_frame)
        self.title_label.setGeometry(QtCore.QRect(10, 0, 91, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_label.setFont(font)
        self.title_label.setObjectName(_fromUtf8("title_label"))
        self.subtitle_label = QtGui.QLabel(self.title_frame)
        self.subtitle_label.setGeometry(QtCore.QRect(10, 20, 311, 16))
        self.subtitle_label.setObjectName(_fromUtf8("subtitle_label"))
        self.gridLayout_2.addWidget(self.title_frame, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(self.wizardPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.textEdit = QtGui.QTextEdit(self.frame_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.textEdit.sizePolicy().hasHeightForWidth())
        self.textEdit.setSizePolicy(sizePolicy)
        self.textEdit.setTextInteractionFlags(QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.verticalLayout.addWidget(self.textEdit)
        self.gridLayout_2.addWidget(self.frame_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.wizardPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 2, 0, 1, 1)
        FirstExam_Wzd.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.wizardPage2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_2 = QtGui.QLabel(self.wizardPage2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 1, 0, 1, 1)
        self.holders_tblWdg = QtGui.QTableWidget(self.wizardPage2)
        self.holders_tblWdg.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.holders_tblWdg.sizePolicy().hasHeightForWidth())
        self.holders_tblWdg.setSizePolicy(sizePolicy)
        self.holders_tblWdg.setMinimumSize(QtCore.QSize(500, 300))
        self.holders_tblWdg.setObjectName(_fromUtf8("holders_tblWdg"))
        self.holders_tblWdg.setColumnCount(5)
        self.holders_tblWdg.setRowCount(9)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.holders_tblWdg.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.holders_tblWdg.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.holders_tblWdg.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.holders_tblWdg.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.holders_tblWdg.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.holders_tblWdg.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        self.holders_tblWdg.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        self.holders_tblWdg.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        self.holders_tblWdg.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.holders_tblWdg.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.holders_tblWdg.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.holders_tblWdg.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(8)
        item.setFont(font)
        self.holders_tblWdg.setHorizontalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter|QtCore.Qt.AlignCenter)
        self.holders_tblWdg.setHorizontalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.holders_tblWdg.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.holders_tblWdg.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.holders_tblWdg.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.holders_tblWdg.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(207, 207, 207))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setForeground(brush)
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.holders_tblWdg.setItem(1, 3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.holders_tblWdg.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.holders_tblWdg.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.holders_tblWdg.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.holders_tblWdg.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.holders_tblWdg.setItem(3, 3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.holders_tblWdg.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.holders_tblWdg.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.holders_tblWdg.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.holders_tblWdg.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable)
        self.holders_tblWdg.setItem(5, 3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.holders_tblWdg.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.holders_tblWdg.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.holders_tblWdg.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Unchecked)
        self.holders_tblWdg.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        self.holders_tblWdg.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setCheckState(QtCore.Qt.Checked)
        self.holders_tblWdg.setItem(8, 2, item)
        self.gridLayout_4.addWidget(self.holders_tblWdg, 2, 0, 1, 1)
        self.title_frame_2 = QtGui.QFrame(self.wizardPage2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_frame_2.sizePolicy().hasHeightForWidth())
        self.title_frame_2.setSizePolicy(sizePolicy)
        self.title_frame_2.setMinimumSize(QtCore.QSize(0, 40))
        self.title_frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.title_frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.title_frame_2.setObjectName(_fromUtf8("title_frame_2"))
        self.title_label_2 = QtGui.QLabel(self.title_frame_2)
        self.title_label_2.setGeometry(QtCore.QRect(10, 0, 111, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_label_2.setFont(font)
        self.title_label_2.setObjectName(_fromUtf8("title_label_2"))
        self.subtitle_label_2 = QtGui.QLabel(self.title_frame_2)
        self.subtitle_label_2.setGeometry(QtCore.QRect(10, 20, 311, 16))
        self.subtitle_label_2.setObjectName(_fromUtf8("subtitle_label_2"))
        self.gridLayout_4.addWidget(self.title_frame_2, 0, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(self.wizardPage2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.pushButton = QtGui.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(350, 10, 91, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMaximumSize(QtCore.QSize(100, 30))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_4.addWidget(self.frame_3, 3, 0, 1, 1)
        FirstExam_Wzd.addPage(self.wizardPage2)
        self.wizardPage = QtGui.QWizardPage()
        self.wizardPage.setObjectName(_fromUtf8("wizardPage"))
        self.gridLayout_3 = QtGui.QGridLayout(self.wizardPage)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.title_frame_3 = QtGui.QFrame(self.wizardPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_frame_3.sizePolicy().hasHeightForWidth())
        self.title_frame_3.setSizePolicy(sizePolicy)
        self.title_frame_3.setMinimumSize(QtCore.QSize(0, 40))
        self.title_frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.title_frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.title_frame_3.setObjectName(_fromUtf8("title_frame_3"))
        self.title_label_3 = QtGui.QLabel(self.title_frame_3)
        self.title_label_3.setGeometry(QtCore.QRect(10, 0, 61, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_label_3.setFont(font)
        self.title_label_3.setObjectName(_fromUtf8("title_label_3"))
        self.subtitle_label_3 = QtGui.QLabel(self.title_frame_3)
        self.subtitle_label_3.setGeometry(QtCore.QRect(10, 20, 311, 16))
        self.subtitle_label_3.setObjectName(_fromUtf8("subtitle_label_3"))
        self.gridLayout_3.addWidget(self.title_frame_3, 0, 0, 1, 1)
        self.frame = QtGui.QFrame(self.wizardPage)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tr_summary = QtGui.QTreeView(self.frame)
        self.tr_summary.setObjectName(_fromUtf8("tr_summary"))
        self.gridLayout.addWidget(self.tr_summary, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.frame, 1, 0, 1, 1)
        self.label = QtGui.QLabel(self.wizardPage)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 2, 0, 1, 1)
        FirstExam_Wzd.addPage(self.wizardPage)

        self.retranslateUi(FirstExam_Wzd)
        QtCore.QMetaObject.connectSlotsByName(FirstExam_Wzd)

    def retranslateUi(self, FirstExam_Wzd):
        FirstExam_Wzd.setWindowTitle(_translate("FirstExam_Wzd", "First Examination", None))
        self.title_label.setText(_translate("FirstExam_Wzd", "Scheme Details", None))
        self.subtitle_label.setText(_translate("FirstExam_Wzd", "This screen shows data for the established scheme ", None))
        self.textEdit.setHtml(_translate("FirstExam_Wzd", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:8pt;\"><br /></p></body></html>", None))
        self.label_3.setText(_translate("FirstExam_Wzd", "Click Next to proceed to the list of documents ", None))
        self.label_2.setText(_translate("FirstExam_Wzd", "For unapproved documents input comment must be added.", None))
        item = self.holders_tblWdg.verticalHeaderItem(0)
        item.setText(_translate("FirstExam_Wzd", "Notice of Scheme Establishment", None))
        item = self.holders_tblWdg.verticalHeaderItem(1)
        item.setText(_translate("FirstExam_Wzd", "Explanatory Report", None))
        item = self.holders_tblWdg.verticalHeaderItem(2)
        item.setText(_translate("FirstExam_Wzd", "Council Resolution", None))
        item = self.holders_tblWdg.verticalHeaderItem(3)
        item.setText(_translate("FirstExam_Wzd", "Title Deed of Blockerf", None))
        item = self.holders_tblWdg.verticalHeaderItem(4)
        item.setText(_translate("FirstExam_Wzd", "Cover Certificate", None))
        item = self.holders_tblWdg.verticalHeaderItem(5)
        item.setText(_translate("FirstExam_Wzd", "List of Potential Holders", None))
        item = self.holders_tblWdg.verticalHeaderItem(6)
        item.setText(_translate("FirstExam_Wzd", "Transfer Contract", None))
        item = self.holders_tblWdg.verticalHeaderItem(7)
        item.setText(_translate("FirstExam_Wzd", "Document Imposing Conditions", None))
        item = self.holders_tblWdg.verticalHeaderItem(8)
        item.setText(_translate("FirstExam_Wzd", "Digital Layout Plan", None))
        item = self.holders_tblWdg.horizontalHeaderItem(0)
        item.setText(_translate("FirstExam_Wzd", "View", None))
        item = self.holders_tblWdg.horizontalHeaderItem(1)
        item.setText(_translate("FirstExam_Wzd", "Revision History", None))
        item = self.holders_tblWdg.horizontalHeaderItem(2)
        item.setText(_translate("FirstExam_Wzd", "Approve", None))
        item = self.holders_tblWdg.horizontalHeaderItem(3)
        item.setText(_translate("FirstExam_Wzd", "Comments", None))
        item = self.holders_tblWdg.horizontalHeaderItem(4)
        item.setText(_translate("FirstExam_Wzd", "Notification", None))
        __sortingEnabled = self.holders_tblWdg.isSortingEnabled()
        self.holders_tblWdg.setSortingEnabled(False)
        self.holders_tblWdg.setSortingEnabled(__sortingEnabled)
        self.title_label_2.setText(_translate("FirstExam_Wzd", "List of Documents", None))
        self.subtitle_label_2.setText(_translate("FirstExam_Wzd", "This screen shows data for the established scheme ", None))
        self.pushButton.setText(_translate("FirstExam_Wzd", "Finish", None))
        self.title_label_3.setText(_translate("FirstExam_Wzd", "Summary", None))
        self.subtitle_label_3.setText(_translate("FirstExam_Wzd", "Below is an output of the examination process.", None))
        self.label.setText(_translate("FirstExam_Wzd", "Confirm the details. Click finish if details are ok or go back to previous steps to edit", None))

