# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_print_certificate.ui'
#
# Created: Sat Jul  6 21:38:56 2019
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_PrintCert_dialog(object):
    def setupUi(self, PrintCert_dialog):
        PrintCert_dialog.setObjectName(_fromUtf8("PrintCert_dialog"))
        PrintCert_dialog.resize(631, 588)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PrintCert_dialog.sizePolicy().hasHeightForWidth())
        PrintCert_dialog.setSizePolicy(sizePolicy)
        PrintCert_dialog.setMinimumSize(QtCore.QSize(400, 300))
        self.gridLayout = QtGui.QGridLayout(PrintCert_dialog)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.title_frame_2 = QtGui.QFrame(PrintCert_dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.title_frame_2.sizePolicy().hasHeightForWidth())
        self.title_frame_2.setSizePolicy(sizePolicy)
        self.title_frame_2.setMinimumSize(QtCore.QSize(0, 40))
        self.title_frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.title_frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.title_frame_2.setObjectName(_fromUtf8("title_frame_2"))
        self.title_label_2 = QtGui.QLabel(self.title_frame_2)
        self.title_label_2.setGeometry(QtCore.QRect(10, 0, 141, 16))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.title_label_2.setFont(font)
        self.title_label_2.setObjectName(_fromUtf8("title_label_2"))
        self.subtitle_label_2 = QtGui.QLabel(self.title_frame_2)
        self.subtitle_label_2.setGeometry(QtCore.QRect(10, 20, 331, 16))
        self.subtitle_label_2.setObjectName(_fromUtf8("subtitle_label_2"))
        self.gridLayout.addWidget(self.title_frame_2, 0, 0, 1, 1)
        self.frame_2 = QtGui.QFrame(PrintCert_dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 10))
        self.frame_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_2 = QtGui.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(110, 0, 61, 16))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label = QtGui.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(10, 0, 101, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame = QtGui.QFrame(PrintCert_dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 200))
        self.frame.setFrameShape(QtGui.QFrame.Box)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setLineWidth(2)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout.addWidget(self.frame, 2, 0, 1, 1)
        self.frame_5 = QtGui.QFrame(PrintCert_dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 40))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.frame_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.selectScanner_Cbx = QtGui.QComboBox(self.frame_5)
        self.selectScanner_Cbx.setObjectName(_fromUtf8("selectScanner_Cbx"))
        self.gridLayout_2.addWidget(self.selectScanner_Cbx, 0, 1, 1, 1)
        self.gridLayout.addWidget(self.frame_5, 3, 0, 1, 1)
        self.frame_4 = QtGui.QFrame(PrintCert_dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 20))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.label_4 = QtGui.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(0, 0, 411, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.frame_4, 4, 0, 1, 1)
        self.frame_3 = QtGui.QFrame(PrintCert_dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.pushButton = QtGui.QPushButton(self.frame_3)
        self.pushButton.setGeometry(QtCore.QRect(155, 10, 75, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.accept_btn = QtGui.QPushButton(self.frame_3)
        self.accept_btn.setGeometry(QtCore.QRect(381, 10, 75, 23))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.accept_btn.sizePolicy().hasHeightForWidth())
        self.accept_btn.setSizePolicy(sizePolicy)
        self.accept_btn.setObjectName(_fromUtf8("accept_btn"))
        self.gridLayout.addWidget(self.frame_3, 5, 0, 1, 1)

        self.retranslateUi(PrintCert_dialog)
        QtCore.QObject.connect(self.accept_btn, QtCore.SIGNAL(_fromUtf8("clicked()")), PrintCert_dialog.close)
        QtCore.QMetaObject.connectSlotsByName(PrintCert_dialog)

    def retranslateUi(self, PrintCert_dialog):
        PrintCert_dialog.setWindowTitle(_translate("PrintCert_dialog", "Print Certificate", None))
        self.title_label_2.setText(_translate("PrintCert_dialog", "Certificate Layout", None))
        self.subtitle_label_2.setText(_translate("PrintCert_dialog", "Below is the certificte requested for printing.", None))
        self.label.setText(_translate("PrintCert_dialog", "Certificate Number:", None))
        self.label_3.setText(_translate("PrintCert_dialog", "Select Printer:", None))
        self.selectScanner_Cbx.setToolTip(_translate("PrintCert_dialog", "<html><head/><body><p>Select a scanner</p></body></html>", None))
        self.label_4.setText(_translate("PrintCert_dialog", "Click print to print certificate and ok to exit dialog", None))
        self.pushButton.setText(_translate("PrintCert_dialog", "Print", None))
        self.accept_btn.setText(_translate("PrintCert_dialog", "Ok", None))

