# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_scheme_lodgement.ui'
#
# Created: Sun Jul 14 07:58:08 2019
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ldg_wzd(object):
    def setupUi(self, ldg_wzd):
        ldg_wzd.setObjectName(_fromUtf8("ldg_wzd"))
        ldg_wzd.setEnabled(True)
        ldg_wzd.resize(702, 494)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ldg_wzd.sizePolicy().hasHeightForWidth())
        ldg_wzd.setSizePolicy(sizePolicy)
        ldg_wzd.setMinimumSize(QtCore.QSize(255, 400))
        ldg_wzd.setMaximumSize(QtCore.QSize(1500, 900))
        ldg_wzd.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        ldg_wzd.setAcceptDrops(False)
        ldg_wzd.setWizardStyle(QtGui.QWizard.ModernStyle)
        ldg_wzd.setOptions(QtGui.QWizard.NoBackButtonOnStartPage)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.wizardPage1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.cbx_relv_auth = QtGui.QComboBox(self.wizardPage1)
        self.cbx_relv_auth.setObjectName(_fromUtf8("cbx_relv_auth"))
        self.gridLayout_2.addWidget(self.cbx_relv_auth, 6, 1, 1, 1)
        self.cbx_region = QtGui.QComboBox(self.wizardPage1)
        self.cbx_region.setObjectName(_fromUtf8("cbx_region"))
        self.gridLayout_2.addWidget(self.cbx_region, 8, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.wizardPage1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 9, 0, 1, 1)
        self.lnedit_schm_num = QtGui.QLineEdit(self.wizardPage1)
        self.lnedit_schm_num.setReadOnly(True)
        self.lnedit_schm_num.setObjectName(_fromUtf8("lnedit_schm_num"))
        self.gridLayout_2.addWidget(self.lnedit_schm_num, 2, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.wizardPage1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 10, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.wizardPage1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 6, 0, 1, 1)
        self.cbx_reg_div = QtGui.QComboBox(self.wizardPage1)
        self.cbx_reg_div.setObjectName(_fromUtf8("cbx_reg_div"))
        self.gridLayout_2.addWidget(self.cbx_reg_div, 10, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.wizardPage1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 5, 0, 1, 1)
        self.cbx_lro = QtGui.QComboBox(self.wizardPage1)
        self.cbx_lro.setObjectName(_fromUtf8("cbx_lro"))
        self.gridLayout_2.addWidget(self.cbx_lro, 7, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.wizardPage1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 8, 0, 1, 1)
        self.date_establish = QtGui.QDateEdit(self.wizardPage1)
        self.date_establish.setMinimumDate(QtCore.QDate(2019, 9, 14))
        self.date_establish.setCalendarPopup(True)
        self.date_establish.setObjectName(_fromUtf8("date_establish"))
        self.gridLayout_2.addWidget(self.date_establish, 5, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.wizardPage1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 7, 0, 1, 1)
        self.lnedit_twnshp = QtGui.QLineEdit(self.wizardPage1)
        self.lnedit_twnshp.setObjectName(_fromUtf8("lnedit_twnshp"))
        self.gridLayout_2.addWidget(self.lnedit_twnshp, 9, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.wizardPage1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.wizardPage1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 4, 0, 1, 1)
        self.date_apprv = QtGui.QDateEdit(self.wizardPage1)
        self.date_apprv.setMinimumDate(QtCore.QDate(2009, 9, 22))
        self.date_apprv.setCalendarPopup(True)
        self.date_apprv.setObjectName(_fromUtf8("date_apprv"))
        self.gridLayout_2.addWidget(self.date_apprv, 4, 1, 1, 1)
        self.lnedit_schm_nam = QtGui.QLineEdit(self.wizardPage1)
        self.lnedit_schm_nam.setObjectName(_fromUtf8("lnedit_schm_nam"))
        self.gridLayout_2.addWidget(self.lnedit_schm_nam, 3, 1, 1, 1)
        self.desc_Label1 = QtGui.QLabel(self.wizardPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desc_Label1.sizePolicy().hasHeightForWidth())
        self.desc_Label1.setSizePolicy(sizePolicy)
        self.desc_Label1.setObjectName(_fromUtf8("desc_Label1"))
        self.gridLayout_2.addWidget(self.desc_Label1, 1, 0, 1, 2)
        self.lbl_Sceme = QtGui.QLabel(self.wizardPage1)
        self.lbl_Sceme.setObjectName(_fromUtf8("lbl_Sceme"))
        self.gridLayout_2.addWidget(self.lbl_Sceme, 2, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.wizardPage1)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 11, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.wizardPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 12, 0, 1, 2)
        self.dbl_spinbx_block_area = QtGui.QDoubleSpinBox(self.wizardPage1)
        self.dbl_spinbx_block_area.setDecimals(4)
        self.dbl_spinbx_block_area.setMaximum(10000000.0)
        self.dbl_spinbx_block_area.setObjectName(_fromUtf8("dbl_spinbx_block_area"))
        self.gridLayout_2.addWidget(self.dbl_spinbx_block_area, 11, 1, 1, 1)
        self.vlNotification = QtGui.QVBoxLayout()
        self.vlNotification.setContentsMargins(-1, -1, -1, 10)
        self.vlNotification.setObjectName(_fromUtf8("vlNotification"))
        self.gridLayout_2.addLayout(self.vlNotification, 0, 0, 1, 2)
        ldg_wzd.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.wizardPage2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.vlNotification_2 = QtGui.QVBoxLayout()
        self.vlNotification_2.setContentsMargins(-1, -1, -1, 10)
        self.vlNotification_2.setObjectName(_fromUtf8("vlNotification_2"))
        self.gridLayout_3.addLayout(self.vlNotification_2, 0, 0, 1, 2)
        self.desc_Label2 = QtGui.QLabel(self.wizardPage2)
        self.desc_Label2.setObjectName(_fromUtf8("desc_Label2"))
        self.gridLayout_3.addWidget(self.desc_Label2, 1, 0, 1, 1)
        self.lnEdit_hld_path = QtGui.QLineEdit(self.wizardPage2)
        self.lnEdit_hld_path.setEnabled(True)
        self.lnEdit_hld_path.setObjectName(_fromUtf8("lnEdit_hld_path"))
        self.gridLayout_3.addWidget(self.lnEdit_hld_path, 2, 0, 1, 1)
        self.btn_brws_hld = QtGui.QPushButton(self.wizardPage2)
        self.btn_brws_hld.setDefault(True)
        self.btn_brws_hld.setObjectName(_fromUtf8("btn_brws_hld"))
        self.gridLayout_3.addWidget(self.btn_brws_hld, 2, 1, 1, 1)
        self.lbl_data_prv = QtGui.QLabel(self.wizardPage2)
        self.lbl_data_prv.setObjectName(_fromUtf8("lbl_data_prv"))
        self.gridLayout_3.addWidget(self.lbl_data_prv, 3, 0, 1, 1)
        self.tw_hld_prv = ExcelWorkbookView(self.wizardPage2)
        self.tw_hld_prv.setObjectName(_fromUtf8("tw_hld_prv"))
        # self.tw_hld_prv.setColumnCount(0)
        # self.tw_hld_prv.setRowCount(0)
        self.gridLayout_3.addWidget(self.tw_hld_prv, 4, 0, 1, 1)
        self.lbl_upld = QtGui.QLabel(self.wizardPage2)
        self.lbl_upld.setObjectName(_fromUtf8("lbl_upld"))
        self.gridLayout_3.addWidget(self.lbl_upld, 5, 0, 1, 1)
        self.btn_valid_upld = QtGui.QPushButton(self.wizardPage2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_valid_upld.sizePolicy().hasHeightForWidth())
        self.btn_valid_upld.setSizePolicy(sizePolicy)
        self.btn_valid_upld.setObjectName(_fromUtf8("btn_valid_upld"))
        self.gridLayout_3.addWidget(self.btn_valid_upld, 5, 1, 1, 1)
        ldg_wzd.addPage(self.wizardPage2)
        self.wizardPage = QtGui.QWizardPage()
        self.wizardPage.setObjectName(_fromUtf8("wizardPage"))
        self.gridLayout = QtGui.QGridLayout(self.wizardPage)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.desc_Label2_2 = QtGui.QLabel(self.wizardPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desc_Label2_2.sizePolicy().hasHeightForWidth())
        self.desc_Label2_2.setSizePolicy(sizePolicy)
        self.desc_Label2_2.setMinimumSize(QtCore.QSize(0, 15))
        self.desc_Label2_2.setMaximumSize(QtCore.QSize(16777215, 15))
        self.desc_Label2_2.setLineWidth(0)
        self.desc_Label2_2.setWordWrap(True)
        self.desc_Label2_2.setMargin(1)
        self.desc_Label2_2.setObjectName(_fromUtf8("desc_Label2_2"))
        self.gridLayout.addWidget(self.desc_Label2_2, 1, 0, 1, 2)
        self.tbw_documents = QtGui.QTableView(self.wizardPage)
        self.tbw_documents.setObjectName(_fromUtf8("tbw_documents"))
        self.gridLayout.addWidget(self.tbw_documents, 2, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.btn_upld_multi = QtGui.QPushButton(self.wizardPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_upld_multi.sizePolicy().hasHeightForWidth())
        self.btn_upld_multi.setSizePolicy(sizePolicy)
        self.btn_upld_multi.setMinimumSize(QtCore.QSize(0, 0))
        self.btn_upld_multi.setMaximumSize(QtCore.QSize(155, 16777215))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/flts_import_file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_upld_multi.setIcon(icon)
        self.btn_upld_multi.setObjectName(_fromUtf8("btn_upld_multi"))
        self.gridLayout.addWidget(self.btn_upld_multi, 3, 1, 1, 1)
        self.vlNotification_3 = QtGui.QVBoxLayout()
        self.vlNotification_3.setContentsMargins(-1, -1, -1, 10)
        self.vlNotification_3.setObjectName(_fromUtf8("vlNotification_3"))
        self.gridLayout.addLayout(self.vlNotification_3, 0, 0, 1, 2)
        ldg_wzd.addPage(self.wizardPage)
        self.wizardPage_4 = QtGui.QWizardPage()
        self.wizardPage_4.setObjectName(_fromUtf8("wizardPage_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.wizardPage_4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.desc_Label2_5 = QtGui.QLabel(self.wizardPage_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desc_Label2_5.sizePolicy().hasHeightForWidth())
        self.desc_Label2_5.setSizePolicy(sizePolicy)
        self.desc_Label2_5.setObjectName(_fromUtf8("desc_Label2_5"))
        self.verticalLayout_2.addWidget(self.desc_Label2_5)
        self.tr_summary = QtGui.QTreeView(self.wizardPage_4)
        self.tr_summary.setObjectName(_fromUtf8("tr_summary"))
        self.verticalLayout_2.addWidget(self.tr_summary)
        ldg_wzd.addPage(self.wizardPage_4)

        self.retranslateUi(ldg_wzd)
        QtCore.QMetaObject.connectSlotsByName(ldg_wzd)

    def retranslateUi(self, ldg_wzd):
        ldg_wzd.setWindowTitle(_translate("ldg_wzd", "Lodgement of Scheme", None))
        self.label_9.setText(_translate("ldg_wzd", "Township Name", None))
        self.label_10.setText(_translate("ldg_wzd", "Registration Division", None))
        self.label_6.setText(_translate("ldg_wzd", "Relevant Authority", None))
        self.label_4.setText(_translate("ldg_wzd", "Date of Esablishment", None))
        self.label_8.setText(_translate("ldg_wzd", "Region", None))
        self.label_7.setText(_translate("ldg_wzd", "Land Rights Office", None))
        self.label_2.setText(_translate("ldg_wzd", "Scheme Name", None))
        self.label_3.setText(_translate("ldg_wzd", "Date of Approval", None))
        self.desc_Label1.setText(_translate("ldg_wzd", "Enter scheme information below. Please note the scheme number will be automatically generated", None))
        self.lbl_Sceme.setText(_translate("ldg_wzd", "Scheme Number", None))
        self.label_11.setText(_translate("ldg_wzd", "Block Area", None))
        self.label_5.setText(_translate("ldg_wzd", "If you would like to end this process click \'cancel\' below, otherwise click \'next to proceed", None))
        self.desc_Label2.setText(_translate("ldg_wzd", "This step entails locating and importing the list of holders file.  ", None))
        self.btn_brws_hld.setText(_translate("ldg_wzd", "Browse...", None))
        self.lbl_data_prv.setText(_translate("ldg_wzd", "Data preview", None))
        self.lbl_upld.setText(_translate("ldg_wzd", "Click Upload button to save data.", None))
        self.btn_valid_upld.setText(_translate("ldg_wzd", "Upload", None))
        self.desc_Label2_2.setText(_translate("ldg_wzd", "Below is a list for required documents. Click Browse to add individual documents or upload multiple documents.", None))
        self.btn_upld_multi.setText(_translate("ldg_wzd", "Upload Documents", None))
        self.desc_Label2_5.setText(_translate("ldg_wzd", "Confirm the scheme information.Click Back to edit the information or Finish to save.  ", None))

from stdm.ui.customcontrols.table_widget import ExcelWorkbookView
# import resources_rc
