# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_scheme_lodgement.ui'
#
# Created: Thu Jul 11 20:00:30 2019
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Ldg_Wzd(object):
    def setupUi(self, Ldg_Wzd):
        Ldg_Wzd.setObjectName(_fromUtf8("Ldg_Wzd"))
        Ldg_Wzd.setEnabled(True)
        Ldg_Wzd.resize(600, 480)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Ldg_Wzd.sizePolicy().hasHeightForWidth())
        Ldg_Wzd.setSizePolicy(sizePolicy)
        Ldg_Wzd.setMinimumSize(QtCore.QSize(410, 460))
        Ldg_Wzd.setMaximumSize(QtCore.QSize(600, 550))
        Ldg_Wzd.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        Ldg_Wzd.setAcceptDrops(False)
        Ldg_Wzd.setWizardStyle(QtGui.QWizard.ModernStyle)
        Ldg_Wzd.setOptions(QtGui.QWizard.NoBackButtonOnStartPage)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.wizardPage1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.desc_Label1 = QtGui.QLabel(self.wizardPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desc_Label1.sizePolicy().hasHeightForWidth())
        self.desc_Label1.setSizePolicy(sizePolicy)
        self.desc_Label1.setObjectName(_fromUtf8("desc_Label1"))
        self.gridLayout_2.addWidget(self.desc_Label1, 0, 0, 1, 2)
        self.lbl_Sceme = QtGui.QLabel(self.wizardPage1)
        self.lbl_Sceme.setObjectName(_fromUtf8("lbl_Sceme"))
        self.gridLayout_2.addWidget(self.lbl_Sceme, 1, 0, 1, 1)
        self.lnEdit_schNum = QtGui.QLineEdit(self.wizardPage1)
        self.lnEdit_schNum.setReadOnly(True)
        self.lnEdit_schNum.setObjectName(_fromUtf8("lnEdit_schNum"))
        self.gridLayout_2.addWidget(self.lnEdit_schNum, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.wizardPage1)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 2, 0, 1, 1)
        self.lnEdit_schmNam = QtGui.QLineEdit(self.wizardPage1)
        self.lnEdit_schmNam.setObjectName(_fromUtf8("lnEdit_schmNam"))
        self.gridLayout_2.addWidget(self.lnEdit_schmNam, 2, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.wizardPage1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 3, 0, 1, 1)
        self.date_apprv = QtGui.QDateEdit(self.wizardPage1)
        self.date_apprv.setMinimumDate(QtCore.QDate(2009, 9, 22))
        self.date_apprv.setCalendarPopup(True)
        self.date_apprv.setObjectName(_fromUtf8("date_apprv"))
        self.gridLayout_2.addWidget(self.date_apprv, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.wizardPage1)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 4, 0, 1, 1)
        self.date_establish = QtGui.QDateEdit(self.wizardPage1)
        self.date_establish.setMinimumDate(QtCore.QDate(2019, 9, 14))
        self.date_establish.setCalendarPopup(True)
        self.date_establish.setObjectName(_fromUtf8("date_establish"))
        self.gridLayout_2.addWidget(self.date_establish, 4, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.wizardPage1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 5, 0, 1, 1)
        self.cbx_relvAuth = QtGui.QComboBox(self.wizardPage1)
        self.cbx_relvAuth.setObjectName(_fromUtf8("cbx_relvAuth"))
        self.gridLayout_2.addWidget(self.cbx_relvAuth, 5, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.wizardPage1)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 6, 0, 1, 1)
        self.scb_lro = QtGui.QComboBox(self.wizardPage1)
        self.scb_lro.setObjectName(_fromUtf8("scb_lro"))
        self.gridLayout_2.addWidget(self.scb_lro, 6, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.wizardPage1)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 7, 0, 1, 1)
        self.cbx_region = QtGui.QComboBox(self.wizardPage1)
        self.cbx_region.setObjectName(_fromUtf8("cbx_region"))
        self.gridLayout_2.addWidget(self.cbx_region, 7, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.wizardPage1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 8, 0, 1, 1)
        self.lnEdit_twnshp = QtGui.QLineEdit(self.wizardPage1)
        self.lnEdit_twnshp.setObjectName(_fromUtf8("lnEdit_twnshp"))
        self.gridLayout_2.addWidget(self.lnEdit_twnshp, 8, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.wizardPage1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 9, 0, 1, 1)
        self.cbx_regDiv = QtGui.QComboBox(self.wizardPage1)
        self.cbx_regDiv.setObjectName(_fromUtf8("cbx_regDiv"))
        self.gridLayout_2.addWidget(self.cbx_regDiv, 9, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.wizardPage1)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 10, 0, 1, 1)
        self.dblSpinBx_blockArea = QtGui.QDoubleSpinBox(self.wizardPage1)
        self.dblSpinBx_blockArea.setDecimals(4)
        self.dblSpinBx_blockArea.setObjectName(_fromUtf8("dblSpinBx_blockArea"))
        self.gridLayout_2.addWidget(self.dblSpinBx_blockArea, 10, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.wizardPage1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 11, 0, 1, 2)
        Ldg_Wzd.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.wizardPage2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.desc_Label2 = QtGui.QLabel(self.wizardPage2)
        self.desc_Label2.setObjectName(_fromUtf8("desc_Label2"))
        self.gridLayout_3.addWidget(self.desc_Label2, 0, 0, 1, 1)
        self.lbl_data_prv = QtGui.QLabel(self.wizardPage2)
        self.lbl_data_prv.setObjectName(_fromUtf8("lbl_data_prv"))
        self.gridLayout_3.addWidget(self.lbl_data_prv, 2, 0, 1, 1)
        self.tw_hld_prv = ExcelWorkbookView(self.wizardPage2)
        self.tw_hld_prv.setObjectName(_fromUtf8("tw_hld_prv"))
        # self.tw_hld_prv.setColumnCount(0)
        # self.tw_hld_prv.setRowCount(0)
        self.gridLayout_3.addWidget(self.tw_hld_prv, 3, 0, 1, 2)
        self.btn_valid_upld = QtGui.QPushButton(self.wizardPage2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_valid_upld.sizePolicy().hasHeightForWidth())
        self.btn_valid_upld.setSizePolicy(sizePolicy)
        self.btn_valid_upld.setObjectName(_fromUtf8("btn_valid_upld"))
        self.gridLayout_3.addWidget(self.btn_valid_upld, 4, 1, 1, 1)
        self.btn_brws_hld = QtGui.QPushButton(self.wizardPage2)
        self.btn_brws_hld.setDefault(True)
        self.btn_brws_hld.setObjectName(_fromUtf8("btn_brws_hld"))
        self.gridLayout_3.addWidget(self.btn_brws_hld, 1, 1, 1, 1)
        self.lnEdit_hld_path = QtGui.QLineEdit(self.wizardPage2)
        self.lnEdit_hld_path.setEnabled(True)
        self.lnEdit_hld_path.setObjectName(_fromUtf8("lnEdit_hld_path"))
        self.gridLayout_3.addWidget(self.lnEdit_hld_path, 1, 0, 1, 1)
        self.lbl_upld = QtGui.QLabel(self.wizardPage2)
        self.lbl_upld.setObjectName(_fromUtf8("lbl_upld"))
        self.gridLayout_3.addWidget(self.lbl_upld, 4, 0, 1, 1)
        Ldg_Wzd.addPage(self.wizardPage2)
        self.wizardPage = QtGui.QWizardPage()
        self.wizardPage.setObjectName(_fromUtf8("wizardPage"))
        self.gridLayout_4 = QtGui.QGridLayout(self.wizardPage)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.frame = QtGui.QFrame(self.wizardPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btn_upld_multi = QtGui.QPushButton(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_upld_multi.sizePolicy().hasHeightForWidth())
        self.btn_upld_multi.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/flts_import_file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_upld_multi.setIcon(icon)
        self.btn_upld_multi.setObjectName(_fromUtf8("btn_upld_multi"))
        self.gridLayout.addWidget(self.btn_upld_multi, 0, 0, 1, 1)
        self.gridLayout_4.addWidget(self.frame, 2, 0, 1, 1)
        self.desc_Label2_2 = QtGui.QLabel(self.wizardPage)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desc_Label2_2.sizePolicy().hasHeightForWidth())
        self.desc_Label2_2.setSizePolicy(sizePolicy)
        self.desc_Label2_2.setMinimumSize(QtCore.QSize(0, 15))
        self.desc_Label2_2.setMaximumSize(QtCore.QSize(16777215, 15))
        self.desc_Label2_2.setLineWidth(0)
        self.desc_Label2_2.setWordWrap(True)
        self.desc_Label2_2.setMargin(1)
        self.desc_Label2_2.setObjectName(_fromUtf8("desc_Label2_2"))
        self.gridLayout_4.addWidget(self.desc_Label2_2, 0, 0, 1, 1)
        self.tbl_upld_docs = QtGui.QTableWidget(self.wizardPage)
        self.tbl_upld_docs.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbl_upld_docs.sizePolicy().hasHeightForWidth())
        self.tbl_upld_docs.setSizePolicy(sizePolicy)
        self.tbl_upld_docs.setMinimumSize(QtCore.QSize(0, 300))
        self.tbl_upld_docs.setMaximumSize(QtCore.QSize(500, 300))
        self.tbl_upld_docs.setSizeIncrement(QtCore.QSize(300, 0))
        self.tbl_upld_docs.setFrameShape(QtGui.QFrame.NoFrame)
        self.tbl_upld_docs.setObjectName(_fromUtf8("tbl_upld_docs"))
        self.tbl_upld_docs.setColumnCount(3)
        self.tbl_upld_docs.setRowCount(9)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_upld_docs.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_upld_docs.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_upld_docs.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_upld_docs.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_upld_docs.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_upld_docs.setVerticalHeaderItem(5, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_upld_docs.setVerticalHeaderItem(6, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_upld_docs.setVerticalHeaderItem(7, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tbl_upld_docs.setVerticalHeaderItem(8, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tbl_upld_docs.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tbl_upld_docs.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        item.setFont(font)
        self.tbl_upld_docs.setHorizontalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(0, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(0, 2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate)
        self.tbl_upld_docs.setItem(1, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(1, 2, item)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setUnderline(True)
        item.setFont(font)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setBackground(brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        item.setForeground(brush)
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate)
        self.tbl_upld_docs.setItem(2, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(2, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate)
        self.tbl_upld_docs.setItem(3, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(3, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(4, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate)
        self.tbl_upld_docs.setItem(4, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(4, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(5, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate)
        self.tbl_upld_docs.setItem(5, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(5, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(6, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate)
        self.tbl_upld_docs.setItem(6, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(6, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(7, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate)
        self.tbl_upld_docs.setItem(7, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(7, 2, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(8, 0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsTristate)
        self.tbl_upld_docs.setItem(8, 1, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.tbl_upld_docs.setItem(8, 2, item)
        self.gridLayout_4.addWidget(self.tbl_upld_docs, 1, 0, 1, 1)
        Ldg_Wzd.addPage(self.wizardPage)
        self.wizardPage_4 = QtGui.QWizardPage()
        self.wizardPage_4.setObjectName(_fromUtf8("wizardPage_4"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.wizardPage_4)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.desc_Label2_5 = QtGui.QLabel(self.wizardPage_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.desc_Label2_5.sizePolicy().hasHeightForWidth())
        self.desc_Label2_5.setSizePolicy(sizePolicy)
        self.desc_Label2_5.setObjectName(_fromUtf8("desc_Label2_5"))
        self.verticalLayout_2.addWidget(self.desc_Label2_5)
        self.tr_summary = QtGui.QTreeView(self.wizardPage_4)
        self.tr_summary.setObjectName(_fromUtf8("tr_summary"))
        self.verticalLayout_2.addWidget(self.tr_summary)
        Ldg_Wzd.addPage(self.wizardPage_4)

        self.retranslateUi(Ldg_Wzd)
        QtCore.QMetaObject.connectSlotsByName(Ldg_Wzd)

    def retranslateUi(self, Ldg_Wzd):
        Ldg_Wzd.setWindowTitle(_translate("Ldg_Wzd", "Lodgement of Scheme", None))
        self.desc_Label1.setText(_translate("Ldg_Wzd", "Enter scheme information below. Please note the scheme number will be automatically generated", None))
        self.lbl_Sceme.setText(_translate("Ldg_Wzd", "Scheme Number", None))
        self.label_2.setText(_translate("Ldg_Wzd", "Scheme Name", None))
        self.label_3.setText(_translate("Ldg_Wzd", "Date of Approval", None))
        self.label_4.setText(_translate("Ldg_Wzd", "Date of Esablishment", None))
        self.label_6.setText(_translate("Ldg_Wzd", "Relevant Authority", None))
        self.label_7.setText(_translate("Ldg_Wzd", "Land Rights Office", None))
        self.label_8.setText(_translate("Ldg_Wzd", "Region", None))
        self.label_9.setText(_translate("Ldg_Wzd", "Township Name", None))
        self.label_10.setText(_translate("Ldg_Wzd", "Registration Division", None))
        self.label_11.setText(_translate("Ldg_Wzd", "Block Area", None))
        self.label_5.setText(_translate("Ldg_Wzd", "If you would like to end this process click \'cancel\' below, otherwise click \'next to proceed", None))
        self.desc_Label2.setText(_translate("Ldg_Wzd", "This step entails locating and importing the list of holders file.  ", None))
        self.lbl_data_prv.setText(_translate("Ldg_Wzd", "Data preview", None))
        self.btn_valid_upld.setText(_translate("Ldg_Wzd", "Upload", None))
        self.btn_brws_hld.setText(_translate("Ldg_Wzd", "Browse...", None))
        self.lbl_upld.setText(_translate("Ldg_Wzd", "Click Upload button to save data.", None))
        self.btn_upld_multi.setText(_translate("Ldg_Wzd", "Upload Multiple Documents", None))
        self.desc_Label2_2.setText(_translate("Ldg_Wzd", "Below is a list for required documents. Click Browse to add individual documents or upload multiple documents.", None))
        item = self.tbl_upld_docs.verticalHeaderItem(0)
        item.setText(_translate("Ldg_Wzd", "Notice of Scheme Establishment", None))
        item = self.tbl_upld_docs.verticalHeaderItem(1)
        item.setText(_translate("Ldg_Wzd", "Explanatory Report", None))
        item = self.tbl_upld_docs.verticalHeaderItem(2)
        item.setText(_translate("Ldg_Wzd", "Council Resolution", None))
        item = self.tbl_upld_docs.verticalHeaderItem(3)
        item.setText(_translate("Ldg_Wzd", "Title Deed of Blockerf", None))
        item = self.tbl_upld_docs.verticalHeaderItem(4)
        item.setText(_translate("Ldg_Wzd", "Cover Certificate", None))
        item = self.tbl_upld_docs.verticalHeaderItem(5)
        item.setText(_translate("Ldg_Wzd", "List of Potential Holders", None))
        item = self.tbl_upld_docs.verticalHeaderItem(6)
        item.setText(_translate("Ldg_Wzd", "Transfer Contract", None))
        item = self.tbl_upld_docs.verticalHeaderItem(7)
        item.setText(_translate("Ldg_Wzd", "Document Imposing Conditions", None))
        item = self.tbl_upld_docs.verticalHeaderItem(8)
        item.setText(_translate("Ldg_Wzd", "Digital Layout Plan", None))
        item = self.tbl_upld_docs.horizontalHeaderItem(0)
        item.setText(_translate("Ldg_Wzd", "Browse", None))
        item.setToolTip(_translate("Ldg_Wzd", "Browse for file", None))
        item = self.tbl_upld_docs.horizontalHeaderItem(1)
        item.setText(_translate("Ldg_Wzd", "Status", None))
        item.setToolTip(_translate("Ldg_Wzd", "Status of file", None))
        item = self.tbl_upld_docs.horizontalHeaderItem(2)
        item.setText(_translate("Ldg_Wzd", "View", None))
        item.setToolTip(_translate("Ldg_Wzd", "Click to view file", None))
        __sortingEnabled = self.tbl_upld_docs.isSortingEnabled()
        self.tbl_upld_docs.setSortingEnabled(False)
        self.tbl_upld_docs.setSortingEnabled(__sortingEnabled)
        self.desc_Label2_5.setText(_translate("Ldg_Wzd", "Confirm the scheme information.Click Back to edit the information or Finish to save.  ", None))

from stdm.ui.customcontrols.table_widget import ExcelWorkbookView
# import resources_rc
