# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_composer_spcolumn_styler.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmComposerSpatialColumnEditor(object):
    def setupUi(self, frmComposerSpatialColumnEditor):
        frmComposerSpatialColumnEditor.setObjectName(_fromUtf8("frmComposerSpatialColumnEditor"))
        frmComposerSpatialColumnEditor.resize(379, 419)
        self.gridLayout = QtGui.QGridLayout(frmComposerSpatialColumnEditor)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(frmComposerSpatialColumnEditor)
        self.tabWidget.setTabPosition(QtGui.QTabWidget.South)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.general = QtGui.QWidget()
        self.general.setObjectName(_fromUtf8("general"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.general)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.scrollArea = QtGui.QScrollArea(self.general)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 327, 345))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout.setContentsMargins(-1, -1, -1, 15)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 30))
        self.label_2.setWordWrap(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.cboLabelField = QtGui.QComboBox(self.groupBox)
        self.cboLabelField.setMinimumSize(QtCore.QSize(0, 30))
        self.cboLabelField.setObjectName(_fromUtf8("cboLabelField"))
        self.verticalLayout.addWidget(self.cboLabelField)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.scrollAreaWidgetContents_2)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setContentsMargins(-1, -1, -1, 15)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.zoom_rad = QtGui.QRadioButton(self.groupBox_2)
        self.zoom_rad.setChecked(True)
        self.zoom_rad.setObjectName(_fromUtf8("zoom_rad"))
        self.gridLayout_2.addWidget(self.zoom_rad, 1, 0, 1, 1)
        self.scale_rad = QtGui.QRadioButton(self.groupBox_2)
        self.scale_rad.setObjectName(_fromUtf8("scale_rad"))
        self.gridLayout_2.addWidget(self.scale_rad, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 2)
        self.sb_zoom = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.sb_zoom.setMinimumSize(QtCore.QSize(0, 32))
        self.sb_zoom.setMaximum(16.0)
        self.sb_zoom.setProperty("value", 1.5)
        self.sb_zoom.setObjectName(_fromUtf8("sb_zoom"))
        self.gridLayout_2.addWidget(self.sb_zoom, 3, 0, 1, 2)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.tabWidget.addTab(self.general, _fromUtf8(""))
        self.style = QtGui.QWidget()
        self.style.setObjectName(_fromUtf8("style"))
        self.gridLayout_3 = QtGui.QGridLayout(self.style)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.styleScrollArea = QtGui.QScrollArea(self.style)
        self.styleScrollArea.setWidgetResizable(True)
        self.styleScrollArea.setObjectName(_fromUtf8("styleScrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 327, 345))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_5 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.styleLayout = QtGui.QGridLayout()
        self.styleLayout.setObjectName(_fromUtf8("styleLayout"))
        self.gridLayout_5.addLayout(self.styleLayout, 0, 0, 1, 1)
        self.styleScrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.styleScrollArea, 0, 0, 1, 1)
        self.tabWidget.addTab(self.style, _fromUtf8(""))
        self.measurement = QtGui.QWidget()
        self.measurement.setObjectName(_fromUtf8("measurement"))
        self.gridLayout_7 = QtGui.QGridLayout(self.measurement)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_11 = QtGui.QLabel(self.measurement)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_7.addWidget(self.label_11, 2, 0, 1, 1)
        self.area_projection = QgsProjectionSelectionWidget(self.measurement)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.area_projection.sizePolicy().hasHeightForWidth())
        self.area_projection.setSizePolicy(sizePolicy)
        self.area_projection.setObjectName(_fromUtf8("area_projection"))
        self.gridLayout_7.addWidget(self.area_projection, 2, 1, 1, 2)
        self.area_box = QgsCollapsibleGroupBox(self.measurement)
        self.area_box.setCheckable(True)
        self.area_box.setChecked(True)
        self.area_box.setObjectName(_fromUtf8("area_box"))
        self.gridLayout_4 = QtGui.QGridLayout(self.area_box)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_3 = QtGui.QLabel(self.area_box)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_4.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.area_box)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 4, 0, 1, 1)
        self.area_prefix_type = QtGui.QComboBox(self.area_box)
        self.area_prefix_type.setObjectName(_fromUtf8("area_prefix_type"))
        self.area_prefix_type.addItem(_fromUtf8(""))
        self.area_prefix_type.addItem(_fromUtf8(""))
        self.area_prefix_type.addItem(_fromUtf8(""))
        self.area_prefix_type.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.area_prefix_type, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.area_box)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 3, 0, 1, 1)
        self.area_prefix = QtGui.QLineEdit(self.area_box)
        self.area_prefix.setObjectName(_fromUtf8("area_prefix"))
        self.gridLayout_4.addWidget(self.area_prefix, 2, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.area_box)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 2, 0, 1, 1)
        self.area_suffix = QtGui.QLineEdit(self.area_box)
        self.area_suffix.setObjectName(_fromUtf8("area_suffix"))
        self.gridLayout_4.addWidget(self.area_suffix, 4, 1, 1, 1)
        self.area_suffix_type = QtGui.QComboBox(self.area_box)
        self.area_suffix_type.setObjectName(_fromUtf8("area_suffix_type"))
        self.area_suffix_type.addItem(_fromUtf8(""))
        self.area_suffix_type.addItem(_fromUtf8(""))
        self.area_suffix_type.addItem(_fromUtf8(""))
        self.area_suffix_type.addItem(_fromUtf8(""))
        self.gridLayout_4.addWidget(self.area_suffix_type, 3, 1, 1, 1)
        self.gridLayout_7.addWidget(self.area_box, 1, 0, 1, 3)
        self.length_box = QgsCollapsibleGroupBox(self.measurement)
        self.length_box.setCheckable(True)
        self.length_box.setChecked(True)
        self.length_box.setObjectName(_fromUtf8("length_box"))
        self.gridLayout_6 = QtGui.QGridLayout(self.length_box)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_7 = QtGui.QLabel(self.length_box)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 1, 0, 1, 1)
        self.length_prefix_type = QtGui.QComboBox(self.length_box)
        self.length_prefix_type.setObjectName(_fromUtf8("length_prefix_type"))
        self.length_prefix_type.addItem(_fromUtf8(""))
        self.length_prefix_type.addItem(_fromUtf8(""))
        self.length_prefix_type.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.length_prefix_type, 1, 1, 1, 1)
        self.length_suffix_type = QtGui.QComboBox(self.length_box)
        self.length_suffix_type.setObjectName(_fromUtf8("length_suffix_type"))
        self.length_suffix_type.addItem(_fromUtf8(""))
        self.length_suffix_type.addItem(_fromUtf8(""))
        self.length_suffix_type.addItem(_fromUtf8(""))
        self.gridLayout_6.addWidget(self.length_suffix_type, 3, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.length_box)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_6.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.length_box)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.length_box)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 3, 0, 1, 1)
        self.length_suffix = QtGui.QLineEdit(self.length_box)
        self.length_suffix.setObjectName(_fromUtf8("length_suffix"))
        self.gridLayout_6.addWidget(self.length_suffix, 4, 1, 1, 1)
        self.length_prefix = QtGui.QLineEdit(self.length_box)
        self.length_prefix.setObjectName(_fromUtf8("length_prefix"))
        self.gridLayout_6.addWidget(self.length_prefix, 2, 1, 1, 1)
        self.gridLayout_7.addWidget(self.length_box, 0, 0, 1, 3)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem1, 3, 1, 1, 1)
        self.tabWidget.addTab(self.measurement, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(frmComposerSpatialColumnEditor)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(frmComposerSpatialColumnEditor)

    def retranslateUi(self, frmComposerSpatialColumnEditor):
        frmComposerSpatialColumnEditor.setWindowTitle(_translate("frmComposerSpatialColumnEditor", "Spatial Column Style Editor", None))
        self.groupBox.setTitle(_translate("frmComposerSpatialColumnEditor", "Legend Label:", None))
        self.label_2.setText(_translate("frmComposerSpatialColumnEditor", "<html><head/><body><p>Select the field whose value will be used to label the feature in the composer legend</p></body></html>", None))
        self.groupBox_2.setTitle(_translate("frmComposerSpatialColumnEditor", "Feature Zoom and Scale:", None))
        self.zoom_rad.setText(_translate("frmComposerSpatialColumnEditor", "Zoom Level", None))
        self.scale_rad.setText(_translate("frmComposerSpatialColumnEditor", "Scale", None))
        self.label.setText(_translate("frmComposerSpatialColumnEditor", "Specify the zoom out level or scale of the feature relative to the fulll extent of the map", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.general), _translate("frmComposerSpatialColumnEditor", "General", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.style), _translate("frmComposerSpatialColumnEditor", "Style", None))
        self.label_11.setText(_translate("frmComposerSpatialColumnEditor", "Output projection:", None))
        self.area_box.setTitle(_translate("frmComposerSpatialColumnEditor", "Area:", None))
        self.label_3.setText(_translate("frmComposerSpatialColumnEditor", "Prefix type:", None))
        self.label_6.setText(_translate("frmComposerSpatialColumnEditor", "Suffix:", None))
        self.area_prefix_type.setItemText(0, _translate("frmComposerSpatialColumnEditor", "Map Unit", None))
        self.area_prefix_type.setItemText(1, _translate("frmComposerSpatialColumnEditor", "None", None))
        self.area_prefix_type.setItemText(2, _translate("frmComposerSpatialColumnEditor", "Hectares", None))
        self.area_prefix_type.setItemText(3, _translate("frmComposerSpatialColumnEditor", "Custom", None))
        self.label_4.setText(_translate("frmComposerSpatialColumnEditor", "Suffix type:", None))
        self.label_5.setText(_translate("frmComposerSpatialColumnEditor", "Prefix:", None))
        self.area_suffix_type.setItemText(0, _translate("frmComposerSpatialColumnEditor", "None", None))
        self.area_suffix_type.setItemText(1, _translate("frmComposerSpatialColumnEditor", "Map Unit", None))
        self.area_suffix_type.setItemText(2, _translate("frmComposerSpatialColumnEditor", "Hectares", None))
        self.area_suffix_type.setItemText(3, _translate("frmComposerSpatialColumnEditor", "Custom", None))
        self.length_box.setTitle(_translate("frmComposerSpatialColumnEditor", "Length:", None))
        self.label_7.setText(_translate("frmComposerSpatialColumnEditor", "Prefix type:", None))
        self.length_prefix_type.setItemText(0, _translate("frmComposerSpatialColumnEditor", "Map Unit", None))
        self.length_prefix_type.setItemText(1, _translate("frmComposerSpatialColumnEditor", "Custom", None))
        self.length_prefix_type.setItemText(2, _translate("frmComposerSpatialColumnEditor", "None", None))
        self.length_suffix_type.setItemText(0, _translate("frmComposerSpatialColumnEditor", "None", None))
        self.length_suffix_type.setItemText(1, _translate("frmComposerSpatialColumnEditor", "Map Unit", None))
        self.length_suffix_type.setItemText(2, _translate("frmComposerSpatialColumnEditor", "Custom", None))
        self.label_10.setText(_translate("frmComposerSpatialColumnEditor", "Suffix:", None))
        self.label_9.setText(_translate("frmComposerSpatialColumnEditor", "Prefix:", None))
        self.label_8.setText(_translate("frmComposerSpatialColumnEditor", "Suffix type:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.measurement), _translate("frmComposerSpatialColumnEditor", "Measurement", None))


from qgis.gui import QgsCollapsibleGroupBox, QgsProjectionSelectionWidget
