# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_stdm_config.ui'
#
# Created: Tue Jul 11 15:14:30 2017
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_STDMWizard(object):
    def setupUi(self, STDMWizard):
        STDMWizard.setObjectName(_fromUtf8("STDMWizard"))
        STDMWizard.setWindowModality(QtCore.Qt.WindowModal)
        STDMWizard.resize(840, 638)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(STDMWizard.sizePolicy().hasHeightForWidth())
        STDMWizard.setSizePolicy(sizePolicy)
        STDMWizard.setMinimumSize(QtCore.QSize(720, 100))
        STDMWizard.setBaseSize(QtCore.QSize(0, 460))
        STDMWizard.setModal(True)
        STDMWizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        STDMWizard.setOptions(QtGui.QWizard.HaveCustomButton1|QtGui.QWizard.HelpButtonOnRight)
        self.wpLicense = QtGui.QWizardPage()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.wpLicense.setFont(font)
        self.wpLicense.setObjectName(_fromUtf8("wpLicense"))
        self.gridLayout_2 = QtGui.QGridLayout(self.wpLicense)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_16 = QtGui.QGroupBox(self.wpLicense)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_16)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.rbAccpt = QtGui.QRadioButton(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.rbAccpt.setFont(font)
        self.rbAccpt.setChecked(False)
        self.rbAccpt.setObjectName(_fromUtf8("rbAccpt"))
        self.gridLayout_20.addWidget(self.rbAccpt, 2, 0, 1, 1)
        self.rbReject = QtGui.QRadioButton(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.rbReject.setFont(font)
        self.rbReject.setCheckable(True)
        self.rbReject.setChecked(False)
        self.rbReject.setObjectName(_fromUtf8("rbReject"))
        self.gridLayout_20.addWidget(self.rbReject, 2, 1, 1, 1)
        self.txtLicense = QtGui.QTextEdit(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtLicense.setFont(font)
        self.txtLicense.setFrameShape(QtGui.QFrame.NoFrame)
        self.txtLicense.setFrameShadow(QtGui.QFrame.Raised)
        self.txtLicense.setObjectName(_fromUtf8("txtLicense"))
        self.gridLayout_20.addWidget(self.txtLicense, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox_16, 0, 0, 1, 1)
        STDMWizard.addPage(self.wpLicense)
        self.wpPathSetting = QtGui.QWizardPage()
        self.wpPathSetting.setObjectName(_fromUtf8("wpPathSetting"))
        self.formLayout_2 = QtGui.QFormLayout(self.wpPathSetting)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.gridLayout.setContentsMargins(-1, 20, -1, -1)
        self.gridLayout.setVerticalSpacing(100)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.btnTemplates = QtGui.QPushButton(self.wpPathSetting)
        self.btnTemplates.setMinimumSize(QtCore.QSize(0, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/open_file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTemplates.setIcon(icon)
        self.btnTemplates.setObjectName(_fromUtf8("btnTemplates"))
        self.gridLayout.addWidget(self.btnTemplates, 2, 2, 1, 1)
        self.btnDocOutput = QtGui.QPushButton(self.wpPathSetting)
        self.btnDocOutput.setMinimumSize(QtCore.QSize(0, 30))
        self.btnDocOutput.setIcon(icon)
        self.btnDocOutput.setObjectName(_fromUtf8("btnDocOutput"))
        self.gridLayout.addWidget(self.btnDocOutput, 1, 2, 1, 1)
        self.edtTemplatePath = QtGui.QLineEdit(self.wpPathSetting)
        self.edtTemplatePath.setMinimumSize(QtCore.QSize(0, 30))
        self.edtTemplatePath.setReadOnly(True)
        self.edtTemplatePath.setObjectName(_fromUtf8("edtTemplatePath"))
        self.gridLayout.addWidget(self.edtTemplatePath, 2, 1, 1, 1)
        self.label_37 = QtGui.QLabel(self.wpPathSetting)
        self.label_37.setMinimumSize(QtCore.QSize(0, 0))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout.addWidget(self.label_37, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.wpPathSetting)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_31 = QtGui.QLabel(self.wpPathSetting)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout.addWidget(self.label_31, 1, 0, 1, 1)
        self.edtOutputPath = QtGui.QLineEdit(self.wpPathSetting)
        self.edtOutputPath.setMinimumSize(QtCore.QSize(0, 30))
        self.edtOutputPath.setReadOnly(True)
        self.edtOutputPath.setObjectName(_fromUtf8("edtOutputPath"))
        self.gridLayout.addWidget(self.edtOutputPath, 1, 1, 1, 1)
        self.btnDocPath = QtGui.QPushButton(self.wpPathSetting)
        self.btnDocPath.setMinimumSize(QtCore.QSize(0, 30))
        self.btnDocPath.setIcon(icon)
        self.btnDocPath.setObjectName(_fromUtf8("btnDocPath"))
        self.gridLayout.addWidget(self.btnDocPath, 0, 2, 1, 1)
        self.edtDocPath = QtGui.QLineEdit(self.wpPathSetting)
        self.edtDocPath.setMinimumSize(QtCore.QSize(0, 30))
        self.edtDocPath.setToolTip(_fromUtf8(""))
        self.edtDocPath.setText(_fromUtf8(""))
        self.edtDocPath.setReadOnly(True)
        self.edtDocPath.setObjectName(_fromUtf8("edtDocPath"))
        self.gridLayout.addWidget(self.edtDocPath, 0, 1, 1, 1)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.SpanningRole, self.gridLayout)
        STDMWizard.addPage(self.wpPathSetting)
        self.wpProfile = QtGui.QWizardPage()
        self.wpProfile.setObjectName(_fromUtf8("wpProfile"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.wpProfile)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.groupBox_17 = QtGui.QGroupBox(self.wpProfile)
        self.groupBox_17.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_17.setMaximumSize(QtCore.QSize(13900, 300))
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_17)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.btnCopy = QtGui.QPushButton(self.groupBox_17)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnCopy.sizePolicy().hasHeightForWidth())
        self.btnCopy.setSizePolicy(sizePolicy)
        self.btnCopy.setMinimumSize(QtCore.QSize(0, 30))
        self.btnCopy.setMaximumSize(QtCore.QSize(150, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/composer_table.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCopy.setIcon(icon1)
        self.btnCopy.setObjectName(_fromUtf8("btnCopy"))
        self.gridLayout_6.addWidget(self.btnCopy, 0, 3, 1, 1)
        self.btnPDelete = QtGui.QPushButton(self.groupBox_17)
        self.btnPDelete.setMinimumSize(QtCore.QSize(0, 30))
        self.btnPDelete.setMaximumSize(QtCore.QSize(150, 16777215))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPDelete.setIcon(icon2)
        self.btnPDelete.setObjectName(_fromUtf8("btnPDelete"))
        self.gridLayout_6.addWidget(self.btnPDelete, 0, 4, 1, 1)
        self.cboProfile = QtGui.QComboBox(self.groupBox_17)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboProfile.sizePolicy().hasHeightForWidth())
        self.cboProfile.setSizePolicy(sizePolicy)
        self.cboProfile.setMinimumSize(QtCore.QSize(10, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cboProfile.setFont(font)
        self.cboProfile.setObjectName(_fromUtf8("cboProfile"))
        self.gridLayout_6.addWidget(self.cboProfile, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_17)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_6.addWidget(self.label, 0, 0, 1, 1)
        self.btnNewP = QtGui.QPushButton(self.groupBox_17)
        self.btnNewP.setMinimumSize(QtCore.QSize(0, 30))
        self.btnNewP.setMaximumSize(QtCore.QSize(150, 16777215))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNewP.setIcon(icon3)
        self.btnNewP.setObjectName(_fromUtf8("btnNewP"))
        self.gridLayout_6.addWidget(self.btnNewP, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_17)
        self.label_3.setMargin(0)
        self.label_3.setIndent(-1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_6.addWidget(self.label_3, 1, 0, 1, 1)
        self.edtDesc = QtGui.QLineEdit(self.groupBox_17)
        self.edtDesc.setObjectName(_fromUtf8("edtDesc"))
        self.gridLayout_6.addWidget(self.edtDesc, 1, 1, 1, 4)
        self.verticalLayout_4.addLayout(self.gridLayout_6)
        self.widget = QtGui.QWidget(self.groupBox_17)
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_4.addWidget(self.widget)
        self.verticalLayout_7.addWidget(self.groupBox_17)
        self.groupBox_18 = QtGui.QGroupBox(self.wpProfile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_18.sizePolicy().hasHeightForWidth())
        self.groupBox_18.setSizePolicy(sizePolicy)
        self.groupBox_18.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBox_18.setMaximumSize(QtCore.QSize(169999, 169999))
        self.groupBox_18.setStyleSheet(_fromUtf8("font: 75 9pt \"Myriad Web Pro\";"))
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.formLayout_3 = QtGui.QFormLayout(self.groupBox_18)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnNewEntity = QtGui.QPushButton(self.groupBox_18)
        self.btnNewEntity.setMinimumSize(QtCore.QSize(30, 25))
        self.btnNewEntity.setMaximumSize(QtCore.QSize(30, 25))
        self.btnNewEntity.setBaseSize(QtCore.QSize(30, 25))
        self.btnNewEntity.setText(_fromUtf8(""))
        self.btnNewEntity.setIcon(icon3)
        self.btnNewEntity.setObjectName(_fromUtf8("btnNewEntity"))
        self.horizontalLayout.addWidget(self.btnNewEntity)
        self.btnEditEntity = QtGui.QPushButton(self.groupBox_18)
        self.btnEditEntity.setMinimumSize(QtCore.QSize(30, 25))
        self.btnEditEntity.setMaximumSize(QtCore.QSize(30, 25))
        self.btnEditEntity.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEditEntity.setIcon(icon4)
        self.btnEditEntity.setObjectName(_fromUtf8("btnEditEntity"))
        self.horizontalLayout.addWidget(self.btnEditEntity)
        self.btnDeleteEntity = QtGui.QPushButton(self.groupBox_18)
        self.btnDeleteEntity.setMinimumSize(QtCore.QSize(30, 25))
        self.btnDeleteEntity.setMaximumSize(QtCore.QSize(30, 25))
        self.btnDeleteEntity.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDeleteEntity.setIcon(icon5)
        self.btnDeleteEntity.setObjectName(_fromUtf8("btnDeleteEntity"))
        self.horizontalLayout.addWidget(self.btnDeleteEntity)
        self.formLayout_3.setLayout(0, QtGui.QFormLayout.LabelRole, self.horizontalLayout)
        self.pftableView = QtGui.QTableView(self.groupBox_18)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.pftableView.sizePolicy().hasHeightForWidth())
        self.pftableView.setSizePolicy(sizePolicy)
        self.pftableView.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.pftableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.pftableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.pftableView.setObjectName(_fromUtf8("pftableView"))
        self.pftableView.horizontalHeader().setStretchLastSection(True)
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.SpanningRole, self.pftableView)
        self.verticalLayout_7.addWidget(self.groupBox_18)
        STDMWizard.addPage(self.wpProfile)
        self.wpEntityCustom = QtGui.QWizardPage()
        self.wpEntityCustom.setObjectName(_fromUtf8("wpEntityCustom"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.wpEntityCustom)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.splitter_3 = QtGui.QSplitter(self.wpEntityCustom)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_3.sizePolicy().hasHeightForWidth())
        self.splitter_3.setSizePolicy(sizePolicy)
        self.splitter_3.setOrientation(QtCore.Qt.Vertical)
        self.splitter_3.setObjectName(_fromUtf8("splitter_3"))
        self.splitter = QtGui.QSplitter(self.splitter_3)
        self.splitter.setMinimumSize(QtCore.QSize(100, 100))
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.groupBox = QtGui.QGroupBox(self.splitter)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setMargin(5)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.lvEntities = QtGui.QListView(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lvEntities.sizePolicy().hasHeightForWidth())
        self.lvEntities.setSizePolicy(sizePolicy)
        self.lvEntities.setMinimumSize(QtCore.QSize(0, 0))
        self.lvEntities.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lvEntities.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lvEntities.setObjectName(_fromUtf8("lvEntities"))
        self.verticalLayout_8.addWidget(self.lvEntities)
        self.groupBox_2 = QtGui.QGroupBox(self.splitter)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout.setMargin(5)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.btnAddColumn = QtGui.QPushButton(self.groupBox_2)
        self.btnAddColumn.setMinimumSize(QtCore.QSize(30, 25))
        self.btnAddColumn.setMaximumSize(QtCore.QSize(30, 25))
        self.btnAddColumn.setText(_fromUtf8(""))
        self.btnAddColumn.setIcon(icon3)
        self.btnAddColumn.setIconSize(QtCore.QSize(20, 20))
        self.btnAddColumn.setObjectName(_fromUtf8("btnAddColumn"))
        self.horizontalLayout_2.addWidget(self.btnAddColumn)
        self.btnEditColumn = QtGui.QPushButton(self.groupBox_2)
        self.btnEditColumn.setMinimumSize(QtCore.QSize(30, 25))
        self.btnEditColumn.setMaximumSize(QtCore.QSize(30, 25))
        self.btnEditColumn.setText(_fromUtf8(""))
        self.btnEditColumn.setIcon(icon4)
        self.btnEditColumn.setIconSize(QtCore.QSize(20, 20))
        self.btnEditColumn.setObjectName(_fromUtf8("btnEditColumn"))
        self.horizontalLayout_2.addWidget(self.btnEditColumn)
        self.btnDeleteColumn = QtGui.QPushButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeleteColumn.sizePolicy().hasHeightForWidth())
        self.btnDeleteColumn.setSizePolicy(sizePolicy)
        self.btnDeleteColumn.setMinimumSize(QtCore.QSize(30, 25))
        self.btnDeleteColumn.setMaximumSize(QtCore.QSize(30, 25))
        self.btnDeleteColumn.setText(_fromUtf8(""))
        self.btnDeleteColumn.setIcon(icon5)
        self.btnDeleteColumn.setObjectName(_fromUtf8("btnDeleteColumn"))
        self.horizontalLayout_2.addWidget(self.btnDeleteColumn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.tbvColumns = QtGui.QTableView(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.tbvColumns.sizePolicy().hasHeightForWidth())
        self.tbvColumns.setSizePolicy(sizePolicy)
        self.tbvColumns.setMinimumSize(QtCore.QSize(0, 0))
        self.tbvColumns.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tbvColumns.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tbvColumns.setFrameShadow(QtGui.QFrame.Sunken)
        self.tbvColumns.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tbvColumns.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tbvColumns.setObjectName(_fromUtf8("tbvColumns"))
        self.tbvColumns.horizontalHeader().setDefaultSectionSize(130)
        self.tbvColumns.horizontalHeader().setStretchLastSection(True)
        self.tbvColumns.verticalHeader().setDefaultSectionSize(30)
        self.verticalLayout.addWidget(self.tbvColumns)
        self.splitter_2 = QtGui.QSplitter(self.splitter_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setMinimumSize(QtCore.QSize(100, 100))
        self.splitter_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.splitter_2.setBaseSize(QtCore.QSize(0, 230))
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.groupBox_5 = QtGui.QGroupBox(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMinimumSize(QtCore.QSize(100, 20))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_5)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setMargin(5)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(6)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.btnAddLookup = QtGui.QPushButton(self.groupBox_5)
        self.btnAddLookup.setMinimumSize(QtCore.QSize(30, 25))
        self.btnAddLookup.setMaximumSize(QtCore.QSize(30, 25))
        self.btnAddLookup.setText(_fromUtf8(""))
        self.btnAddLookup.setIcon(icon3)
        self.btnAddLookup.setObjectName(_fromUtf8("btnAddLookup"))
        self.horizontalLayout_4.addWidget(self.btnAddLookup)
        self.btnEditLookup = QtGui.QPushButton(self.groupBox_5)
        self.btnEditLookup.setMinimumSize(QtCore.QSize(30, 25))
        self.btnEditLookup.setMaximumSize(QtCore.QSize(30, 25))
        self.btnEditLookup.setText(_fromUtf8(""))
        self.btnEditLookup.setIcon(icon4)
        self.btnEditLookup.setObjectName(_fromUtf8("btnEditLookup"))
        self.horizontalLayout_4.addWidget(self.btnEditLookup)
        self.btnDeleteLookup = QtGui.QPushButton(self.groupBox_5)
        self.btnDeleteLookup.setMinimumSize(QtCore.QSize(30, 25))
        self.btnDeleteLookup.setMaximumSize(QtCore.QSize(30, 25))
        self.btnDeleteLookup.setText(_fromUtf8(""))
        self.btnDeleteLookup.setIcon(icon5)
        self.btnDeleteLookup.setObjectName(_fromUtf8("btnDeleteLookup"))
        self.horizontalLayout_4.addWidget(self.btnDeleteLookup)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.lvLookups = QtGui.QListView(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lvLookups.sizePolicy().hasHeightForWidth())
        self.lvLookups.setSizePolicy(sizePolicy)
        self.lvLookups.setMinimumSize(QtCore.QSize(0, 0))
        self.lvLookups.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lvLookups.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lvLookups.setObjectName(_fromUtf8("lvLookups"))
        self.verticalLayout_3.addWidget(self.lvLookups)
        self.groupBox_6 = QtGui.QGroupBox(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_6.sizePolicy().hasHeightForWidth())
        self.groupBox_6.setSizePolicy(sizePolicy)
        self.groupBox_6.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_6)
        self.verticalLayout_2.setMargin(5)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.btnAddLkupValue = QtGui.QPushButton(self.groupBox_6)
        self.btnAddLkupValue.setMinimumSize(QtCore.QSize(30, 25))
        self.btnAddLkupValue.setMaximumSize(QtCore.QSize(30, 25))
        self.btnAddLkupValue.setText(_fromUtf8(""))
        self.btnAddLkupValue.setIcon(icon3)
        self.btnAddLkupValue.setObjectName(_fromUtf8("btnAddLkupValue"))
        self.horizontalLayout_5.addWidget(self.btnAddLkupValue)
        self.btnEditLkupValue = QtGui.QPushButton(self.groupBox_6)
        self.btnEditLkupValue.setMinimumSize(QtCore.QSize(30, 25))
        self.btnEditLkupValue.setMaximumSize(QtCore.QSize(30, 25))
        self.btnEditLkupValue.setText(_fromUtf8(""))
        self.btnEditLkupValue.setIcon(icon4)
        self.btnEditLkupValue.setObjectName(_fromUtf8("btnEditLkupValue"))
        self.horizontalLayout_5.addWidget(self.btnEditLkupValue)
        self.btnDeleteLkupValue = QtGui.QPushButton(self.groupBox_6)
        self.btnDeleteLkupValue.setMinimumSize(QtCore.QSize(30, 25))
        self.btnDeleteLkupValue.setMaximumSize(QtCore.QSize(30, 25))
        self.btnDeleteLkupValue.setText(_fromUtf8(""))
        self.btnDeleteLkupValue.setIcon(icon5)
        self.btnDeleteLkupValue.setObjectName(_fromUtf8("btnDeleteLkupValue"))
        self.horizontalLayout_5.addWidget(self.btnDeleteLkupValue)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.lvLookupValues = QtGui.QListView(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.lvLookupValues.sizePolicy().hasHeightForWidth())
        self.lvLookupValues.setSizePolicy(sizePolicy)
        self.lvLookupValues.setMinimumSize(QtCore.QSize(0, 0))
        self.lvLookupValues.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lvLookupValues.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lvLookupValues.setObjectName(_fromUtf8("lvLookupValues"))
        self.verticalLayout_2.addWidget(self.lvLookupValues)
        self.verticalLayout_9.addWidget(self.splitter_3)
        STDMWizard.addPage(self.wpEntityCustom)
        self.wpSTR = QtGui.QWizardPage()
        self.wpSTR.setObjectName(_fromUtf8("wpSTR"))
        self.gridLayout_3 = QtGui.QGridLayout(self.wpSTR)
        self.gridLayout_3.setContentsMargins(2, 4, 2, 4)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.dg_tenure = ProfileTenureDiagram(self.wpSTR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dg_tenure.sizePolicy().hasHeightForWidth())
        self.dg_tenure.setSizePolicy(sizePolicy)
        self.dg_tenure.setMinimumSize(QtCore.QSize(100, 320))
        self.dg_tenure.setObjectName(_fromUtf8("dg_tenure"))
        self.gridLayout_3.addWidget(self.dg_tenure, 1, 1, 1, 1)
        self.scrollArea = QtGui.QScrollArea(self.wpSTR)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(50, 0))
        self.scrollArea.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 244, 624))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setContentsMargins(3, 0, 2, 1)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_5 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_5.addWidget(self.label_5)
        self.lst_parties = STRPartyListView(self.scrollAreaWidgetContents_2)
        self.lst_parties.setMaximumSize(QtCore.QSize(16777215, 120))
        self.lst_parties.setObjectName(_fromUtf8("lst_parties"))
        self.verticalLayout_5.addWidget(self.lst_parties)
        self.cbMultiParty = QtGui.QCheckBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbMultiParty.sizePolicy().hasHeightForWidth())
        self.cbMultiParty.setSizePolicy(sizePolicy)
        self.cbMultiParty.setObjectName(_fromUtf8("cbMultiParty"))
        self.verticalLayout_5.addWidget(self.cbMultiParty)
        self.label_6 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_5.addWidget(self.label_6)
        self.lst_spatial_units = STRSpatialUnitListView(self.scrollAreaWidgetContents_2)
        self.lst_spatial_units.setMaximumSize(QtCore.QSize(16777215, 120))
        self.lst_spatial_units.setObjectName(_fromUtf8("lst_spatial_units"))
        self.verticalLayout_5.addWidget(self.lst_spatial_units)
        self.btn_sp_units_tenure = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/social_tenure.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_sp_units_tenure.setIcon(icon6)
        self.btn_sp_units_tenure.setObjectName(_fromUtf8("btn_sp_units_tenure"))
        self.verticalLayout_5.addWidget(self.btn_sp_units_tenure)
        self.label_7 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout_5.addWidget(self.label_7)
        self.gb_start_dates = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_start_dates.sizePolicy().hasHeightForWidth())
        self.gb_start_dates.setSizePolicy(sizePolicy)
        self.gb_start_dates.setCheckable(True)
        self.gb_start_dates.setChecked(False)
        self.gb_start_dates.setObjectName(_fromUtf8("gb_start_dates"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gb_start_dates)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_8 = QtGui.QLabel(self.gb_start_dates)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_4.addWidget(self.label_8, 0, 0, 1, 1)
        self.dt_start_minimum = QtGui.QDateEdit(self.gb_start_dates)
        self.dt_start_minimum.setCalendarPopup(True)
        self.dt_start_minimum.setObjectName(_fromUtf8("dt_start_minimum"))
        self.gridLayout_4.addWidget(self.dt_start_minimum, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gb_start_dates)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_4.addWidget(self.label_9, 1, 0, 1, 1)
        self.dt_start_maximum = QtGui.QDateEdit(self.gb_start_dates)
        self.dt_start_maximum.setCalendarPopup(True)
        self.dt_start_maximum.setObjectName(_fromUtf8("dt_start_maximum"))
        self.gridLayout_4.addWidget(self.dt_start_maximum, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.gb_start_dates)
        self.gb_end_dates = QgsCollapsibleGroupBox(self.scrollAreaWidgetContents_2)
        self.gb_end_dates.setCheckable(True)
        self.gb_end_dates.setChecked(False)
        self.gb_end_dates.setObjectName(_fromUtf8("gb_end_dates"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gb_end_dates)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_10 = QtGui.QLabel(self.gb_end_dates)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 0, 0, 1, 1)
        self.dt_end_minimum = QtGui.QDateEdit(self.gb_end_dates)
        self.dt_end_minimum.setCalendarPopup(True)
        self.dt_end_minimum.setObjectName(_fromUtf8("dt_end_minimum"))
        self.gridLayout_5.addWidget(self.dt_end_minimum, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gb_end_dates)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 1, 0, 1, 1)
        self.dt_end_maximum = QtGui.QDateEdit(self.gb_end_dates)
        self.dt_end_maximum.setCalendarPopup(True)
        self.dt_end_maximum.setObjectName(_fromUtf8("dt_end_maximum"))
        self.gridLayout_5.addWidget(self.dt_end_maximum, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.gb_end_dates)
        self.label_12 = QtGui.QLabel(self.scrollAreaWidgetContents_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout_5.addWidget(self.label_12)
        self.btn_custom_attrs = QtGui.QPushButton(self.scrollAreaWidgetContents_2)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/column.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_custom_attrs.setIcon(icon7)
        self.btn_custom_attrs.setObjectName(_fromUtf8("btn_custom_attrs"))
        self.verticalLayout_5.addWidget(self.btn_custom_attrs)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem3)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_3.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.vl_notification_str = QtGui.QVBoxLayout()
        self.vl_notification_str.setObjectName(_fromUtf8("vl_notification_str"))
        self.gridLayout_3.addLayout(self.vl_notification_str, 0, 0, 1, 2)
        STDMWizard.addPage(self.wpSTR)
        self.wpSaveProfile = QtGui.QWizardPage()
        self.wpSaveProfile.setObjectName(_fromUtf8("wpSaveProfile"))
        self.formLayout_10 = QtGui.QFormLayout(self.wpSaveProfile)
        self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
        self.label_2 = QtGui.QLabel(self.wpSaveProfile)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_10.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.txtHtml = QtGui.QTextEdit(self.wpSaveProfile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.txtHtml.sizePolicy().hasHeightForWidth())
        self.txtHtml.setSizePolicy(sizePolicy)
        self.txtHtml.setReadOnly(True)
        self.txtHtml.setObjectName(_fromUtf8("txtHtml"))
        self.formLayout_10.setWidget(1, QtGui.QFormLayout.SpanningRole, self.txtHtml)
        STDMWizard.addPage(self.wpSaveProfile)

        self.retranslateUi(STDMWizard)
        QtCore.QMetaObject.connectSlotsByName(STDMWizard)
        STDMWizard.setTabOrder(self.rbAccpt, self.cboProfile)
        STDMWizard.setTabOrder(self.cboProfile, self.rbReject)
        STDMWizard.setTabOrder(self.rbReject, self.btnPDelete)
        STDMWizard.setTabOrder(self.btnPDelete, self.btnNewP)
        STDMWizard.setTabOrder(self.btnNewP, self.pftableView)
        STDMWizard.setTabOrder(self.pftableView, self.btnNewEntity)
        STDMWizard.setTabOrder(self.btnNewEntity, self.btnEditEntity)
        STDMWizard.setTabOrder(self.btnEditEntity, self.btnDeleteEntity)
        STDMWizard.setTabOrder(self.btnDeleteEntity, self.btnDeleteColumn)
        STDMWizard.setTabOrder(self.btnDeleteColumn, self.btnEditColumn)
        STDMWizard.setTabOrder(self.btnEditColumn, self.btnAddColumn)
        STDMWizard.setTabOrder(self.btnAddColumn, self.tbvColumns)
        STDMWizard.setTabOrder(self.tbvColumns, self.lvLookups)
        STDMWizard.setTabOrder(self.lvLookups, self.btnEditLookup)
        STDMWizard.setTabOrder(self.btnEditLookup, self.lvLookupValues)
        STDMWizard.setTabOrder(self.lvLookupValues, self.btnEditLkupValue)
        STDMWizard.setTabOrder(self.btnEditLkupValue, self.txtLicense)

    def retranslateUi(self, STDMWizard):
        STDMWizard.setWindowTitle(QtGui.QApplication.translate("STDMWizard", "Configuration Wizard", None, QtGui.QApplication.UnicodeUTF8))
        self.wpLicense.setTitle(QtGui.QApplication.translate("STDMWizard", "End User License Agreement", None, QtGui.QApplication.UnicodeUTF8))
        self.wpLicense.setSubTitle(QtGui.QApplication.translate("STDMWizard", "Read carefully before you proceed", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_16.setTitle(QtGui.QApplication.translate("STDMWizard", "Terms and Conditions", None, QtGui.QApplication.UnicodeUTF8))
        self.rbAccpt.setText(QtGui.QApplication.translate("STDMWizard", "I Agree", None, QtGui.QApplication.UnicodeUTF8))
        self.rbReject.setText(QtGui.QApplication.translate("STDMWizard", "Decline", None, QtGui.QApplication.UnicodeUTF8))
        self.wpPathSetting.setTitle(QtGui.QApplication.translate("STDMWizard", "Directory Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.wpPathSetting.setSubTitle(QtGui.QApplication.translate("STDMWizard", "Specify configuration and documents directory path", None, QtGui.QApplication.UnicodeUTF8))
        self.btnTemplates.setText(QtGui.QApplication.translate("STDMWizard", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDocOutput.setText(QtGui.QApplication.translate("STDMWizard", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.edtTemplatePath.setPlaceholderText(QtGui.QApplication.translate("STDMWizard", "Specify path to save document templates", None, QtGui.QApplication.UnicodeUTF8))
        self.label_37.setText(QtGui.QApplication.translate("STDMWizard", "<html><head/><body><p>Supporting documents path</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("STDMWizard", "Documents template path", None, QtGui.QApplication.UnicodeUTF8))
        self.label_31.setText(QtGui.QApplication.translate("STDMWizard", "Documents output path", None, QtGui.QApplication.UnicodeUTF8))
        self.edtOutputPath.setPlaceholderText(QtGui.QApplication.translate("STDMWizard", "Specify path to save generated documents", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDocPath.setText(QtGui.QApplication.translate("STDMWizard", "Change", None, QtGui.QApplication.UnicodeUTF8))
        self.edtDocPath.setPlaceholderText(QtGui.QApplication.translate("STDMWizard", "Specify path to save entity supporting documents", None, QtGui.QApplication.UnicodeUTF8))
        self.wpProfile.setTitle(QtGui.QApplication.translate("STDMWizard", "Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.wpProfile.setSubTitle(QtGui.QApplication.translate("STDMWizard", "Manage profile and related entities.  A profile represents a collection of logically related entities, some of which represent the party and spatial unit. Examples of profiles include individual, household, neighbourhood or even city-wide profiles.   ", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_17.setTitle(QtGui.QApplication.translate("STDMWizard", "Profile", None, QtGui.QApplication.UnicodeUTF8))
        self.btnCopy.setText(QtGui.QApplication.translate("STDMWizard", "Copy profile", None, QtGui.QApplication.UnicodeUTF8))
        self.btnPDelete.setText(QtGui.QApplication.translate("STDMWizard", "Delete profile", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("STDMWizard", "Name", None, QtGui.QApplication.UnicodeUTF8))
        self.btnNewP.setText(QtGui.QApplication.translate("STDMWizard", "New profile", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("STDMWizard", "Description", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_18.setTitle(QtGui.QApplication.translate("STDMWizard", "Profile entities ", None, QtGui.QApplication.UnicodeUTF8))
        self.wpEntityCustom.setTitle(QtGui.QApplication.translate("STDMWizard", "Entity Customization", None, QtGui.QApplication.UnicodeUTF8))
        self.wpEntityCustom.setSubTitle(QtGui.QApplication.translate("STDMWizard", "Add or edit entity columns, lookups and lookup values", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("STDMWizard", "Entities", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("STDMWizard", "Columns", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_5.setTitle(QtGui.QApplication.translate("STDMWizard", "Lookups", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("STDMWizard", "Values", None, QtGui.QApplication.UnicodeUTF8))
        self.wpSTR.setTitle(QtGui.QApplication.translate("STDMWizard", "Define Social Tenure Entities", None, QtGui.QApplication.UnicodeUTF8))
        self.wpSTR.setSubTitle(QtGui.QApplication.translate("STDMWizard", "Set entities to participate in the profile\'s social tenure relationship", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("STDMWizard", "1. Select the party entities", None, QtGui.QApplication.UnicodeUTF8))
        self.cbMultiParty.setText(QtGui.QApplication.translate("STDMWizard", "Allow multiple parties to be \n"
"linked to a single spatial unit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("STDMWizard", "2. Select the spatial unit entities", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_sp_units_tenure.setText(QtGui.QApplication.translate("STDMWizard", "Spatial Unit Tenure Types...", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("STDMWizard", "3. Specify validity ranges (optional)", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_start_dates.setTitle(QtGui.QApplication.translate("STDMWizard", "\'Start\' date range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("STDMWizard", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_9.setText(QtGui.QApplication.translate("STDMWizard", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.gb_end_dates.setTitle(QtGui.QApplication.translate("STDMWizard", "\'End\' date range", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("STDMWizard", "Minimum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("STDMWizard", "Maximum", None, QtGui.QApplication.UnicodeUTF8))
        self.label_12.setText(QtGui.QApplication.translate("STDMWizard", "4. Specify custom tenure attributes (optional)", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_custom_attrs.setText(QtGui.QApplication.translate("STDMWizard", "Custom Attributes...", None, QtGui.QApplication.UnicodeUTF8))
        self.wpSaveProfile.setTitle(QtGui.QApplication.translate("STDMWizard", "Save configuration", None, QtGui.QApplication.UnicodeUTF8))
        self.wpSaveProfile.setSubTitle(QtGui.QApplication.translate("STDMWizard", "Click finish to save changes in your configuration to the database.  ", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("STDMWizard", "Save status will be displayed in the window below.", None, QtGui.QApplication.UnicodeUTF8))

from stdm.ui.wizard.party_list_view import STRPartyListView
from qgis.gui import QgsCollapsibleGroupBox
from stdm.ui.wizard.profile_tenure_view import ProfileTenureDiagram
from .spatial_unit_list_view import STRSpatialUnitListView
