# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_geometry_container.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_GeometryContainer(object):
    def setupUi(self, GeometryContainer):
        GeometryContainer.setObjectName(_fromUtf8("GeometryContainer"))
        GeometryContainer.resize(356, 435)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockWidgetContents)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        self.label = QtGui.QLabel(self.dockWidgetContents)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.geom_tools_combo = QtGui.QComboBox(self.dockWidgetContents)
        self.geom_tools_combo.setObjectName(_fromUtf8("geom_tools_combo"))
        self.geom_tools_combo.addItem(_fromUtf8(""))
        self.geom_tools_combo.addItem(_fromUtf8(""))
        self.geom_tools_combo.addItem(_fromUtf8(""))
        self.geom_tools_combo.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.geom_tools_combo, 0, 1, 1, 2)
        self.geom_tools_widgets = QtGui.QStackedWidget(self.dockWidgetContents)
        self.geom_tools_widgets.setObjectName(_fromUtf8("geom_tools_widgets"))
        self.page_1 = QtGui.QWidget()
        self.page_1.setObjectName(_fromUtf8("page_1"))
        self.gridLayout_3 = QtGui.QGridLayout(self.page_1)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_22 = QtGui.QLabel(self.page_1)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_3.addWidget(self.label_22, 0, 2, 1, 1)
        self.pushButton_2 = QtGui.QPushButton(self.page_1)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.gridLayout_3.addWidget(self.pushButton_2, 5, 3, 1, 2)
        self.pushButton_3 = QtGui.QPushButton(self.page_1)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_3.addWidget(self.pushButton_3, 5, 5, 1, 1)
        self.label_6 = QtGui.QLabel(self.page_1)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 2, 2, 1, 1)
        self.pushButton = QtGui.QPushButton(self.page_1)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_3.addWidget(self.pushButton, 5, 2, 1, 1)
        self.label_23 = QtGui.QLabel(self.page_1)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_3.addWidget(self.label_23, 0, 3, 1, 2)
        self.doubleSpinBox_3 = QtGui.QDoubleSpinBox(self.page_1)
        self.doubleSpinBox_3.setObjectName(_fromUtf8("doubleSpinBox_3"))
        self.gridLayout_3.addWidget(self.doubleSpinBox_3, 2, 3, 1, 3)
        self.label_30 = QtGui.QLabel(self.page_1)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_3.addWidget(self.label_30, 1, 2, 1, 1)
        self.label_31 = QtGui.QLabel(self.page_1)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_3.addWidget(self.label_31, 1, 3, 1, 1)
        self.geom_tools_widgets.addWidget(self.page_1)
        self.page_3 = QtGui.QWidget()
        self.page_3.setObjectName(_fromUtf8("page_3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.page_3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_25 = QtGui.QLabel(self.page_3)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_2.addWidget(self.label_25, 0, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.page_3)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 3, 0, 1, 1)
        self.offset_side_l = QtGui.QRadioButton(self.page_3)
        self.offset_side_l.setObjectName(_fromUtf8("offset_side_l"))
        self.gridLayout_2.addWidget(self.offset_side_l, 3, 1, 1, 1)
        self.offset_side_r = QtGui.QRadioButton(self.page_3)
        self.offset_side_r.setObjectName(_fromUtf8("offset_side_r"))
        self.gridLayout_2.addWidget(self.offset_side_r, 3, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.page_3)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 2, 0, 1, 1)
        self.pushButton_4 = QtGui.QPushButton(self.page_3)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.gridLayout_2.addWidget(self.pushButton_4, 4, 2, 1, 1)
        self.pushButton_5 = QtGui.QPushButton(self.page_3)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.gridLayout_2.addWidget(self.pushButton_5, 4, 1, 1, 1)
        self.pushButton_6 = QtGui.QPushButton(self.page_3)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.gridLayout_2.addWidget(self.pushButton_6, 4, 0, 1, 1)
        self.label_24 = QtGui.QLabel(self.page_3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_2.addWidget(self.label_24, 0, 0, 1, 1)
        self.doubleSpinBox_2 = QtGui.QDoubleSpinBox(self.page_3)
        self.doubleSpinBox_2.setObjectName(_fromUtf8("doubleSpinBox_2"))
        self.gridLayout_2.addWidget(self.doubleSpinBox_2, 2, 1, 1, 2)
        self.label_28 = QtGui.QLabel(self.page_3)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_2.addWidget(self.label_28, 1, 0, 1, 1)
        self.label_29 = QtGui.QLabel(self.page_3)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_2.addWidget(self.label_29, 1, 1, 1, 1)
        self.geom_tools_widgets.addWidget(self.page_3)
        self.page_4 = QtGui.QWidget()
        self.page_4.setObjectName(_fromUtf8("page_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.page_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_14 = QtGui.QLabel(self.page_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_5.addWidget(self.label_14, 3, 0, 1, 1)
        self.pushButton_8 = QtGui.QPushButton(self.page_4)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.gridLayout_5.addWidget(self.pushButton_8, 6, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.page_4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_5.addWidget(self.label_15, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.page_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.page_4)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.radioButton = QtGui.QRadioButton(self.groupBox)
        self.radioButton.setObjectName(_fromUtf8("radioButton"))
        self.gridLayout_6.addWidget(self.radioButton, 0, 0, 1, 1)
        self.radioButton_2 = QtGui.QRadioButton(self.groupBox)
        self.radioButton_2.setObjectName(_fromUtf8("radioButton_2"))
        self.gridLayout_6.addWidget(self.radioButton_2, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_6.addWidget(self.label_13, 2, 0, 1, 1)
        self.doubleSpinBox = QtGui.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setObjectName(_fromUtf8("doubleSpinBox"))
        self.gridLayout_6.addWidget(self.doubleSpinBox, 2, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 4, 0, 1, 4)
        self.label_12 = QtGui.QLabel(self.page_4)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.page_4)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 1, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.page_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 2, 0, 1, 1)
        self.pushButton_7 = QtGui.QPushButton(self.page_4)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.gridLayout_5.addWidget(self.pushButton_7, 6, 0, 1, 1)
        self.pushButton_9 = QtGui.QPushButton(self.page_4)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.gridLayout_5.addWidget(self.pushButton_9, 6, 2, 1, 1)
        self.label_26 = QtGui.QLabel(self.page_4)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_5.addWidget(self.label_26, 0, 0, 1, 1)
        self.label_27 = QtGui.QLabel(self.page_4)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_5.addWidget(self.label_27, 0, 1, 1, 1)
        self.geom_tools_widgets.addWidget(self.page_4)
        self.page_5 = QtGui.QWidget()
        self.page_5.setObjectName(_fromUtf8("page_5"))
        self.gridLayout_8 = QtGui.QGridLayout(self.page_5)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.pushButton_11 = QtGui.QPushButton(self.page_5)
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.gridLayout_8.addWidget(self.pushButton_11, 6, 1, 1, 1)
        self.label_19 = QtGui.QLabel(self.page_5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_8.addWidget(self.label_19, 2, 1, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(self.page_5)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.radioButton_3 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_3.setObjectName(_fromUtf8("radioButton_3"))
        self.gridLayout_7.addWidget(self.radioButton_3, 0, 0, 1, 1)
        self.radioButton_4 = QtGui.QRadioButton(self.groupBox_2)
        self.radioButton_4.setObjectName(_fromUtf8("radioButton_4"))
        self.gridLayout_7.addWidget(self.radioButton_4, 1, 0, 1, 1)
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_7.addWidget(self.label_16, 2, 0, 1, 1)
        self.doubleSpinBox_4 = QtGui.QDoubleSpinBox(self.groupBox_2)
        self.doubleSpinBox_4.setObjectName(_fromUtf8("doubleSpinBox_4"))
        self.gridLayout_7.addWidget(self.doubleSpinBox_4, 2, 1, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_2, 4, 0, 1, 3)
        self.label_21 = QtGui.QLabel(self.page_5)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_8.addWidget(self.label_21, 5, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.page_5)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_8.addWidget(self.label_20, 1, 1, 1, 2)
        self.label_18 = QtGui.QLabel(self.page_5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_8.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.page_5)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_8.addWidget(self.label_17, 2, 0, 1, 1)
        self.doubleSpinBox_5 = QtGui.QDoubleSpinBox(self.page_5)
        self.doubleSpinBox_5.setObjectName(_fromUtf8("doubleSpinBox_5"))
        self.gridLayout_8.addWidget(self.doubleSpinBox_5, 5, 1, 1, 2)
        self.pushButton_10 = QtGui.QPushButton(self.page_5)
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.gridLayout_8.addWidget(self.pushButton_10, 6, 0, 1, 1)
        self.pushButton_12 = QtGui.QPushButton(self.page_5)
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.gridLayout_8.addWidget(self.pushButton_12, 6, 2, 1, 1)
        self.label_2 = QtGui.QLabel(self.page_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_8.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.page_5)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_8.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_3 = QtGui.QLabel(self.page_5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_8.addWidget(self.label_3, 3, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.page_5)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_8.addWidget(self.label_4, 3, 1, 1, 1)
        self.geom_tools_widgets.addWidget(self.page_5)
        self.gridLayout.addWidget(self.geom_tools_widgets, 1, 0, 2, 3)
        GeometryContainer.setWidget(self.dockWidgetContents)

        self.retranslateUi(GeometryContainer)
        self.geom_tools_widgets.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(GeometryContainer)

    def retranslateUi(self, GeometryContainer):
        GeometryContainer.setWindowTitle(_translate("GeometryContainer", "Geometry Tools", None))
        self.label.setText(_translate("GeometryContainer", "Geometry tools:", None))
        self.geom_tools_combo.setItemText(0, _translate("GeometryContainer", "Split Polygon: Move Line and Area", None))
        self.geom_tools_combo.setItemText(1, _translate("GeometryContainer", "Split Polygon: Offset Distance", None))
        self.geom_tools_combo.setItemText(2, _translate("GeometryContainer", "Split Polygon: Join Points", None))
        self.geom_tools_combo.setItemText(3, _translate("GeometryContainer", "Split Polygon: One Point and Area", None))
        self.label_22.setText(_translate("GeometryContainer", "Selected features:", None))
        self.pushButton_2.setText(_translate("GeometryContainer", "Preview", None))
        self.pushButton_3.setText(_translate("GeometryContainer", "Save", None))
        self.label_6.setText(_translate("GeometryContainer", "Split polygon area:", None))
        self.pushButton.setText(_translate("GeometryContainer", "Cancel", None))
        self.label_23.setText(_translate("GeometryContainer", "0", None))
        self.label_30.setText(_translate("GeometryContainer", "Selected line:", None))
        self.label_31.setText(_translate("GeometryContainer", "0", None))
        self.label_25.setText(_translate("GeometryContainer", "0", None))
        self.label_10.setText(_translate("GeometryContainer", "Offset side:", None))
        self.offset_side_l.setText(_translate("GeometryContainer", "Left", None))
        self.offset_side_r.setText(_translate("GeometryContainer", "Right", None))
        self.label_11.setText(_translate("GeometryContainer", "Offset distance:", None))
        self.pushButton_4.setText(_translate("GeometryContainer", "Save", None))
        self.pushButton_5.setText(_translate("GeometryContainer", "Preview", None))
        self.pushButton_6.setText(_translate("GeometryContainer", "Cancel", None))
        self.label_24.setText(_translate("GeometryContainer", "Selected features:", None))
        self.label_28.setText(_translate("GeometryContainer", "Selected line:", None))
        self.label_29.setText(_translate("GeometryContainer", "0", None))
        self.label_14.setText(_translate("GeometryContainer", "Selected points:", None))
        self.pushButton_8.setText(_translate("GeometryContainer", "Preview", None))
        self.label_15.setText(_translate("GeometryContainer", "0", None))
        self.label_8.setText(_translate("GeometryContainer", "Selected line:", None))
        self.groupBox.setTitle(_translate("GeometryContainer", "Reference Point", None))
        self.radioButton.setText(_translate("GeometryContainer", "RadioButton", None))
        self.radioButton_2.setText(_translate("GeometryContainer", "RadioButton", None))
        self.label_13.setText(_translate("GeometryContainer", "Length from reference point:", None))
        self.label_12.setText(_translate("GeometryContainer", "0", None))
        self.label_9.setText(_translate("GeometryContainer", "0", None))
        self.label_7.setText(_translate("GeometryContainer", "Total length:", None))
        self.pushButton_7.setText(_translate("GeometryContainer", "Cancel", None))
        self.pushButton_9.setText(_translate("GeometryContainer", "Save", None))
        self.label_26.setText(_translate("GeometryContainer", "Selected features:", None))
        self.label_27.setText(_translate("GeometryContainer", "0", None))
        self.pushButton_11.setText(_translate("GeometryContainer", "Preview", None))
        self.label_19.setText(_translate("GeometryContainer", "0", None))
        self.groupBox_2.setTitle(_translate("GeometryContainer", "Reference Point", None))
        self.radioButton_3.setText(_translate("GeometryContainer", "RadioButton", None))
        self.radioButton_4.setText(_translate("GeometryContainer", "RadioButton", None))
        self.label_16.setText(_translate("GeometryContainer", "Length from reference point:", None))
        self.label_21.setText(_translate("GeometryContainer", "Split polygon area:", None))
        self.label_20.setText(_translate("GeometryContainer", "0", None))
        self.label_18.setText(_translate("GeometryContainer", "Selected line:", None))
        self.label_17.setText(_translate("GeometryContainer", "Total length:", None))
        self.pushButton_10.setText(_translate("GeometryContainer", "Cancel", None))
        self.pushButton_12.setText(_translate("GeometryContainer", "Save", None))
        self.label_2.setText(_translate("GeometryContainer", "Selected Features:", None))
        self.label_5.setText(_translate("GeometryContainer", "0", None))
        self.label_3.setText(_translate("GeometryContainer", "Selected points:", None))
        self.label_4.setText(_translate("GeometryContainer", "0", None))

