# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_show_measurements.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ShowMeasurements(object):
    def setupUi(self, ShowMeasurements):
        ShowMeasurements.setObjectName(_fromUtf8("ShowMeasurements"))
        ShowMeasurements.resize(410, 416)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ShowMeasurements.sizePolicy().hasHeightForWidth())
        ShowMeasurements.setSizePolicy(sizePolicy)
        ShowMeasurements.setMaximumSize(QtCore.QSize(16777215, 416))
        self.gridLayout = QtGui.QGridLayout(ShowMeasurements)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.area_box = QtGui.QGroupBox(ShowMeasurements)
        self.area_box.setEnabled(False)
        self.area_box.setObjectName(_fromUtf8("area_box"))
        self.gridLayout_2 = QtGui.QGridLayout(self.area_box)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.area_box)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.area_prefix_type = QtGui.QComboBox(self.area_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.area_prefix_type.sizePolicy().hasHeightForWidth())
        self.area_prefix_type.setSizePolicy(sizePolicy)
        self.area_prefix_type.setObjectName(_fromUtf8("area_prefix_type"))
        self.area_prefix_type.addItem(_fromUtf8(""))
        self.area_prefix_type.addItem(_fromUtf8(""))
        self.area_prefix_type.addItem(_fromUtf8(""))
        self.area_prefix_type.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.area_prefix_type, 0, 1, 1, 1)
        self.label_5 = QtGui.QLabel(self.area_box)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.area_prefix = QtGui.QLineEdit(self.area_box)
        self.area_prefix.setEnabled(False)
        self.area_prefix.setObjectName(_fromUtf8("area_prefix"))
        self.gridLayout_2.addWidget(self.area_prefix, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.area_box)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.area_suffix_type = QtGui.QComboBox(self.area_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.area_suffix_type.sizePolicy().hasHeightForWidth())
        self.area_suffix_type.setSizePolicy(sizePolicy)
        self.area_suffix_type.setObjectName(_fromUtf8("area_suffix_type"))
        self.area_suffix_type.addItem(_fromUtf8(""))
        self.area_suffix_type.addItem(_fromUtf8(""))
        self.area_suffix_type.addItem(_fromUtf8(""))
        self.area_suffix_type.addItem(_fromUtf8(""))
        self.gridLayout_2.addWidget(self.area_suffix_type, 2, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.area_box)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 3, 0, 1, 1)
        self.area_suffix = QtGui.QLineEdit(self.area_box)
        self.area_suffix.setEnabled(False)
        self.area_suffix.setObjectName(_fromUtf8("area_suffix"))
        self.gridLayout_2.addWidget(self.area_suffix, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.area_box, 3, 0, 1, 4)
        self.length_box = QtGui.QGroupBox(ShowMeasurements)
        self.length_box.setObjectName(_fromUtf8("length_box"))
        self.gridLayout_3 = QtGui.QGridLayout(self.length_box)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_7 = QtGui.QLabel(self.length_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 1)
        self.length_prefix_type = QtGui.QComboBox(self.length_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.length_prefix_type.sizePolicy().hasHeightForWidth())
        self.length_prefix_type.setSizePolicy(sizePolicy)
        self.length_prefix_type.setObjectName(_fromUtf8("length_prefix_type"))
        self.length_prefix_type.addItem(_fromUtf8(""))
        self.length_prefix_type.addItem(_fromUtf8(""))
        self.length_prefix_type.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.length_prefix_type, 0, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.length_box)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 1, 0, 1, 1)
        self.length_prefix = QtGui.QLineEdit(self.length_box)
        self.length_prefix.setEnabled(False)
        self.length_prefix.setObjectName(_fromUtf8("length_prefix"))
        self.gridLayout_3.addWidget(self.length_prefix, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.length_box)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 2, 0, 1, 1)
        self.length_suffix_type = QtGui.QComboBox(self.length_box)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.length_suffix_type.sizePolicy().hasHeightForWidth())
        self.length_suffix_type.setSizePolicy(sizePolicy)
        self.length_suffix_type.setObjectName(_fromUtf8("length_suffix_type"))
        self.length_suffix_type.addItem(_fromUtf8(""))
        self.length_suffix_type.addItem(_fromUtf8(""))
        self.length_suffix_type.addItem(_fromUtf8(""))
        self.gridLayout_3.addWidget(self.length_suffix_type, 2, 1, 1, 1)
        self.label_10 = QtGui.QLabel(self.length_box)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 3, 0, 1, 1)
        self.length_suffix = QtGui.QLineEdit(self.length_box)
        self.length_suffix.setEnabled(False)
        self.length_suffix.setObjectName(_fromUtf8("length_suffix"))
        self.gridLayout_3.addWidget(self.length_suffix, 3, 1, 1, 1)
        self.gridLayout.addWidget(self.length_box, 2, 0, 1, 4)
        spacerItem = QtGui.QSpacerItem(116, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.selected_features_rad = QtGui.QRadioButton(ShowMeasurements)
        self.selected_features_rad.setChecked(True)
        self.selected_features_rad.setObjectName(_fromUtf8("selected_features_rad"))
        self.gridLayout.addWidget(self.selected_features_rad, 4, 1, 1, 1)
        self.selected_layer_rad = QtGui.QRadioButton(ShowMeasurements)
        self.selected_layer_rad.setObjectName(_fromUtf8("selected_layer_rad"))
        self.gridLayout.addWidget(self.selected_layer_rad, 4, 2, 1, 1)
        self.cancel_btn = QtGui.QPushButton(ShowMeasurements)
        self.cancel_btn.setObjectName(_fromUtf8("cancel_btn"))
        self.gridLayout.addWidget(self.cancel_btn, 5, 1, 1, 1)
        self.label_2 = QtGui.QLabel(ShowMeasurements)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtGui.QLabel(ShowMeasurements)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.length_chk = QtGui.QCheckBox(ShowMeasurements)
        self.length_chk.setChecked(True)
        self.length_chk.setObjectName(_fromUtf8("length_chk"))
        self.gridLayout.addWidget(self.length_chk, 0, 1, 1, 1)
        self.run_btn = QtGui.QPushButton(ShowMeasurements)
        self.run_btn.setObjectName(_fromUtf8("run_btn"))
        self.gridLayout.addWidget(self.run_btn, 5, 2, 1, 2)
        self.area_chk = QtGui.QCheckBox(ShowMeasurements)
        self.area_chk.setObjectName(_fromUtf8("area_chk"))
        self.gridLayout.addWidget(self.area_chk, 0, 2, 1, 1)

        self.retranslateUi(ShowMeasurements)
        QtCore.QMetaObject.connectSlotsByName(ShowMeasurements)

    def retranslateUi(self, ShowMeasurements):
        ShowMeasurements.setWindowTitle(_translate("ShowMeasurements", "Form", None))
        self.area_box.setTitle(_translate("ShowMeasurements", "Area:", None))
        self.label_3.setText(_translate("ShowMeasurements", "Prefix type:", None))
        self.area_prefix_type.setItemText(0, _translate("ShowMeasurements", "None", None))
        self.area_prefix_type.setItemText(1, _translate("ShowMeasurements", "Map Unit", None))
        self.area_prefix_type.setItemText(2, _translate("ShowMeasurements", "Hectares", None))
        self.area_prefix_type.setItemText(3, _translate("ShowMeasurements", "Custom", None))
        self.label_5.setText(_translate("ShowMeasurements", "Prefix:", None))
        self.label_4.setText(_translate("ShowMeasurements", "Suffix type:", None))
        self.area_suffix_type.setItemText(0, _translate("ShowMeasurements", "None", None))
        self.area_suffix_type.setItemText(1, _translate("ShowMeasurements", "Map Unit", None))
        self.area_suffix_type.setItemText(2, _translate("ShowMeasurements", "Hectares", None))
        self.area_suffix_type.setItemText(3, _translate("ShowMeasurements", "Custom", None))
        self.label_6.setText(_translate("ShowMeasurements", "Suffix:", None))
        self.length_box.setTitle(_translate("ShowMeasurements", "Legth:", None))
        self.label_7.setText(_translate("ShowMeasurements", "Prefix type:", None))
        self.length_prefix_type.setItemText(0, _translate("ShowMeasurements", "None", None))
        self.length_prefix_type.setItemText(1, _translate("ShowMeasurements", "Map Unit", None))
        self.length_prefix_type.setItemText(2, _translate("ShowMeasurements", "Custom", None))
        self.label_9.setText(_translate("ShowMeasurements", "Prefix:", None))
        self.label_8.setText(_translate("ShowMeasurements", "Suffix type:", None))
        self.length_suffix_type.setItemText(0, _translate("ShowMeasurements", "None", None))
        self.length_suffix_type.setItemText(1, _translate("ShowMeasurements", "Map Unit", None))
        self.length_suffix_type.setItemText(2, _translate("ShowMeasurements", "Custom", None))
        self.label_10.setText(_translate("ShowMeasurements", "Suffix:", None))
        self.selected_features_rad.setText(_translate("ShowMeasurements", "Selected Features", None))
        self.selected_layer_rad.setText(_translate("ShowMeasurements", "Selected Layer", None))
        self.cancel_btn.setText(_translate("ShowMeasurements", "Cancel", None))
        self.label_2.setText(_translate("ShowMeasurements", "Show measurements:", None))
        self.label.setText(_translate("ShowMeasurements", "Apply on:", None))
        self.length_chk.setText(_translate("ShowMeasurements", "Length", None))
        self.run_btn.setText(_translate("ShowMeasurements", "Run", None))
        self.area_chk.setText(_translate("ShowMeasurements", "Area", None))

