# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_column_editor.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ColumnEditor(object):
    def setupUi(self, ColumnEditor):
        ColumnEditor.setObjectName(_fromUtf8("ColumnEditor"))
        ColumnEditor.resize(359, 377)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(ColumnEditor.sizePolicy().hasHeightForWidth())
        ColumnEditor.setSizePolicy(sizePolicy)
        ColumnEditor.setMaximumSize(QtCore.QSize(16777215, 560))
        self.gridLayout = QtGui.QGridLayout(ColumnEditor)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(ColumnEditor)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.edtColName = QtGui.QLineEdit(ColumnEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtColName.sizePolicy().hasHeightForWidth())
        self.edtColName.setSizePolicy(sizePolicy)
        self.edtColName.setObjectName(_fromUtf8("edtColName"))
        self.gridLayout.addWidget(self.edtColName, 2, 2, 1, 1)
        self.label = QtGui.QLabel(ColumnEditor)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 4, 0, 1, 1)
        self.txt_form_label = QtGui.QLineEdit(ColumnEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.txt_form_label.sizePolicy().hasHeightForWidth())
        self.txt_form_label.setSizePolicy(sizePolicy)
        self.txt_form_label.setInputMask(_fromUtf8(""))
        self.txt_form_label.setText(_fromUtf8(""))
        self.txt_form_label.setMaxLength(32767)
        self.txt_form_label.setObjectName(_fromUtf8("txt_form_label"))
        self.gridLayout.addWidget(self.txt_form_label, 4, 2, 1, 1)
        self.edtColDesc = QtGui.QLineEdit(ColumnEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtColDesc.sizePolicy().hasHeightForWidth())
        self.edtColDesc.setSizePolicy(sizePolicy)
        self.edtColDesc.setObjectName(_fromUtf8("edtColDesc"))
        self.gridLayout.addWidget(self.edtColDesc, 3, 2, 1, 1)
        self.label_4 = QtGui.QLabel(ColumnEditor)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 6, 0, 1, 2)
        self.edtUserTip = QtGui.QLineEdit(ColumnEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edtUserTip.sizePolicy().hasHeightForWidth())
        self.edtUserTip.setSizePolicy(sizePolicy)
        self.edtUserTip.setText(_fromUtf8(""))
        self.edtUserTip.setObjectName(_fromUtf8("edtUserTip"))
        self.gridLayout.addWidget(self.edtUserTip, 5, 2, 1, 1)
        self.label_11 = QtGui.QLabel(ColumnEditor)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 5, 0, 1, 1)
        self.cboDataType = QtGui.QComboBox(ColumnEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboDataType.sizePolicy().hasHeightForWidth())
        self.cboDataType.setSizePolicy(sizePolicy)
        self.cboDataType.setEditable(False)
        self.cboDataType.setInsertPolicy(QtGui.QComboBox.InsertAlphabetically)
        self.cboDataType.setObjectName(_fromUtf8("cboDataType"))
        self.gridLayout.addWidget(self.cboDataType, 6, 2, 1, 1)
        self.label_3 = QtGui.QLabel(ColumnEditor)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.btnColProp = QtGui.QPushButton(ColumnEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnColProp.sizePolicy().hasHeightForWidth())
        self.btnColProp.setSizePolicy(sizePolicy)
        self.btnColProp.setObjectName(_fromUtf8("btnColProp"))
        self.gridLayout.addWidget(self.btnColProp, 7, 2, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ColumnEditor)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 12, 0, 1, 3)
        self.notif_bar = QtGui.QVBoxLayout()
        self.notif_bar.setContentsMargins(-1, -1, -1, 0)
        self.notif_bar.setSpacing(8)
        self.notif_bar.setObjectName(_fromUtf8("notif_bar"))
        self.gridLayout.addLayout(self.notif_bar, 1, 0, 1, 3)
        self.cbIndex = QtGui.QCheckBox(ColumnEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbIndex.sizePolicy().hasHeightForWidth())
        self.cbIndex.setSizePolicy(sizePolicy)
        self.cbIndex.setObjectName(_fromUtf8("cbIndex"))
        self.gridLayout.addWidget(self.cbIndex, 11, 1, 1, 2)
        self.cbUnique = QtGui.QCheckBox(ColumnEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbUnique.sizePolicy().hasHeightForWidth())
        self.cbUnique.setSizePolicy(sizePolicy)
        self.cbUnique.setObjectName(_fromUtf8("cbUnique"))
        self.gridLayout.addWidget(self.cbUnique, 10, 1, 1, 2)
        self.cbSearch = QtGui.QCheckBox(ColumnEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbSearch.sizePolicy().hasHeightForWidth())
        self.cbSearch.setSizePolicy(sizePolicy)
        self.cbSearch.setObjectName(_fromUtf8("cbSearch"))
        self.gridLayout.addWidget(self.cbSearch, 9, 1, 1, 2)
        self.cbMandt = QtGui.QCheckBox(ColumnEditor)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbMandt.sizePolicy().hasHeightForWidth())
        self.cbMandt.setSizePolicy(sizePolicy)
        self.cbMandt.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.cbMandt.setChecked(False)
        self.cbMandt.setObjectName(_fromUtf8("cbMandt"))
        self.gridLayout.addWidget(self.cbMandt, 8, 1, 1, 2)

        self.retranslateUi(ColumnEditor)
        QtCore.QMetaObject.connectSlotsByName(ColumnEditor)
        ColumnEditor.setTabOrder(self.edtColName, self.edtColDesc)
        ColumnEditor.setTabOrder(self.edtColDesc, self.edtUserTip)
        ColumnEditor.setTabOrder(self.edtUserTip, self.cboDataType)
        ColumnEditor.setTabOrder(self.cboDataType, self.btnColProp)

    def retranslateUi(self, ColumnEditor):
        ColumnEditor.setWindowTitle(_translate("ColumnEditor", "Column editor", None))
        self.label_2.setText(_translate("ColumnEditor", "Column name", None))
        self.edtColName.setPlaceholderText(_translate("ColumnEditor", "Enter column name", None))
        self.label.setText(_translate("ColumnEditor", "Form Label", None))
        self.txt_form_label.setPlaceholderText(_translate("ColumnEditor", "Column name in the form", None))
        self.edtColDesc.setPlaceholderText(_translate("ColumnEditor", "Column Description", None))
        self.label_4.setText(_translate("ColumnEditor", "Column data type", None))
        self.edtUserTip.setPlaceholderText(_translate("ColumnEditor", "Enter text to appear in the form as a tooltip", None))
        self.label_11.setText(_translate("ColumnEditor", "User tip", None))
        self.label_3.setText(_translate("ColumnEditor", "Description", None))
        self.btnColProp.setText(_translate("ColumnEditor", "Column properties ...", None))
        self.cbIndex.setText(_translate("ColumnEditor", "Column Indexed", None))
        self.cbUnique.setText(_translate("ColumnEditor", "Unique", None))
        self.cbSearch.setText(_translate("ColumnEditor", "Searchable", None))
        self.cbMandt.setText(_translate("ColumnEditor", "Mandatory", None))

