# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_stdm_config.ui'
#
# Created: Mon Feb 22 17:22:38 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_STDMWizard(object):
    def setupUi(self, STDMWizard):
        STDMWizard.setObjectName(_fromUtf8("STDMWizard"))
        STDMWizard.resize(607, 491)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(STDMWizard.sizePolicy().hasHeightForWidth())
        STDMWizard.setSizePolicy(sizePolicy)
        STDMWizard.setMinimumSize(QtCore.QSize(255, 100))
        STDMWizard.setBaseSize(QtCore.QSize(0, 460))
        STDMWizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        self.wpLicense = QtGui.QWizardPage()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.wpLicense.setFont(font)
        self.wpLicense.setObjectName(_fromUtf8("wpLicense"))
        self.gridLayout_2 = QtGui.QGridLayout(self.wpLicense)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_16 = QtGui.QGroupBox(self.wpLicense)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_16)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.rbAccpt = QtGui.QRadioButton(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.rbAccpt.setFont(font)
        self.rbAccpt.setChecked(False)
        self.rbAccpt.setObjectName(_fromUtf8("rbAccpt"))
        self.gridLayout_20.addWidget(self.rbAccpt, 2, 0, 1, 1)
        self.rbReject = QtGui.QRadioButton(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.rbReject.setFont(font)
        self.rbReject.setCheckable(True)
        self.rbReject.setChecked(False)
        self.rbReject.setObjectName(_fromUtf8("rbReject"))
        self.gridLayout_20.addWidget(self.rbReject, 2, 1, 1, 1)
        self.txtLicense = QtGui.QTextEdit(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtLicense.setFont(font)
        self.txtLicense.setFrameShape(QtGui.QFrame.NoFrame)
        self.txtLicense.setFrameShadow(QtGui.QFrame.Raised)
        self.txtLicense.setObjectName(_fromUtf8("txtLicense"))
        self.gridLayout_20.addWidget(self.txtLicense, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox_16, 0, 0, 1, 1)
        STDMWizard.addPage(self.wpLicense)
        self.wpPathSetting = QtGui.QWizardPage()
        self.wpPathSetting.setObjectName(_fromUtf8("wpPathSetting"))
        self.gridLayout_27 = QtGui.QGridLayout(self.wpPathSetting)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.groupBox_15 = QtGui.QGroupBox(self.wpPathSetting)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_15.sizePolicy().hasHeightForWidth())
        self.groupBox_15.setSizePolicy(sizePolicy)
        self.groupBox_15.setMinimumSize(QtCore.QSize(0, 350))
        self.groupBox_15.setMaximumSize(QtCore.QSize(16777215, 500))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.label_37 = QtGui.QLabel(self.groupBox_15)
        self.label_37.setGeometry(QtCore.QRect(14, 43, 200, 30))
        self.label_37.setMinimumSize(QtCore.QSize(200, 30))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.edtOutputPath = QtGui.QLineEdit(self.groupBox_15)
        self.edtOutputPath.setGeometry(QtCore.QRect(190, 140, 231, 30))
        self.edtOutputPath.setMinimumSize(QtCore.QSize(0, 30))
        self.edtOutputPath.setReadOnly(True)
        self.edtOutputPath.setObjectName(_fromUtf8("edtOutputPath"))
        self.edtTemplatePath = QtGui.QLineEdit(self.groupBox_15)
        self.edtTemplatePath.setGeometry(QtCore.QRect(188, 230, 231, 30))
        self.edtTemplatePath.setMinimumSize(QtCore.QSize(0, 30))
        self.edtTemplatePath.setObjectName(_fromUtf8("edtTemplatePath"))
        self.label_4 = QtGui.QLabel(self.groupBox_15)
        self.label_4.setGeometry(QtCore.QRect(14, 237, 123, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_31 = QtGui.QLabel(self.groupBox_15)
        self.label_31.setGeometry(QtCore.QRect(14, 145, 166, 16))
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.btnDocOutput = QtGui.QPushButton(self.groupBox_15)
        self.btnDocOutput.setGeometry(QtCore.QRect(425, 139, 75, 30))
        self.btnDocOutput.setMinimumSize(QtCore.QSize(0, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/open_file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDocOutput.setIcon(icon)
        self.btnDocOutput.setObjectName(_fromUtf8("btnDocOutput"))
        self.edtDocPath = QtGui.QLineEdit(self.groupBox_15)
        self.edtDocPath.setGeometry(QtCore.QRect(190, 40, 231, 30))
        self.edtDocPath.setMinimumSize(QtCore.QSize(0, 30))
        self.edtDocPath.setText(_fromUtf8(""))
        self.edtDocPath.setReadOnly(True)
        self.edtDocPath.setObjectName(_fromUtf8("edtDocPath"))
        self.btnTemplates = QtGui.QPushButton(self.groupBox_15)
        self.btnTemplates.setGeometry(QtCore.QRect(422, 230, 75, 30))
        self.btnTemplates.setMinimumSize(QtCore.QSize(0, 30))
        self.btnTemplates.setIcon(icon)
        self.btnTemplates.setObjectName(_fromUtf8("btnTemplates"))
        self.btnDocPath = QtGui.QPushButton(self.groupBox_15)
        self.btnDocPath.setGeometry(QtCore.QRect(426, 40, 75, 30))
        self.btnDocPath.setMinimumSize(QtCore.QSize(0, 30))
        self.btnDocPath.setIcon(icon)
        self.btnDocPath.setObjectName(_fromUtf8("btnDocPath"))
        self.gridLayout_27.addWidget(self.groupBox_15, 0, 0, 1, 1)
        STDMWizard.addPage(self.wpPathSetting)
        self.wpProfile = QtGui.QWizardPage()
        self.wpProfile.setObjectName(_fromUtf8("wpProfile"))
        self.groupBox_17 = QtGui.QGroupBox(self.wpProfile)
        self.groupBox_17.setGeometry(QtCore.QRect(1, 7, 570, 70))
        self.groupBox_17.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_17.setMaximumSize(QtCore.QSize(800, 300))
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.label = QtGui.QLabel(self.groupBox_17)
        self.label.setGeometry(QtCore.QRect(10, 27, 50, 16))
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.cboProfile = QtGui.QComboBox(self.groupBox_17)
        self.cboProfile.setGeometry(QtCore.QRect(60, 19, 271, 30))
        self.cboProfile.setMinimumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cboProfile.setFont(font)
        self.cboProfile.setObjectName(_fromUtf8("cboProfile"))
        self.widget = QtGui.QWidget(self.groupBox_17)
        self.widget.setGeometry(QtCore.QRect(338, 9, 206, 48))
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_24 = QtGui.QGridLayout(self.widget)
        self.gridLayout_24.setMargin(0)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.btnPDelete = QtGui.QPushButton(self.widget)
        self.btnPDelete.setMinimumSize(QtCore.QSize(25, 30))
        self.btnPDelete.setMaximumSize(QtCore.QSize(150, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPDelete.setIcon(icon1)
        self.btnPDelete.setObjectName(_fromUtf8("btnPDelete"))
        self.gridLayout_24.addWidget(self.btnPDelete, 1, 5, 1, 1)
        self.btnNewP = QtGui.QPushButton(self.widget)
        self.btnNewP.setMinimumSize(QtCore.QSize(0, 30))
        self.btnNewP.setMaximumSize(QtCore.QSize(150, 16777215))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNewP.setIcon(icon2)
        self.btnNewP.setObjectName(_fromUtf8("btnNewP"))
        self.gridLayout_24.addWidget(self.btnNewP, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.gridLayout_24.addLayout(self.horizontalLayout, 1, 2, 1, 1)
        self.groupBox_18 = QtGui.QGroupBox(self.wpProfile)
        self.groupBox_18.setGeometry(QtCore.QRect(0, 84, 570, 300))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_18.sizePolicy().hasHeightForWidth())
        self.groupBox_18.setSizePolicy(sizePolicy)
        self.groupBox_18.setMinimumSize(QtCore.QSize(0, 300))
        self.groupBox_18.setMaximumSize(QtCore.QSize(800, 400))
        self.groupBox_18.setStyleSheet(_fromUtf8("font: 75 9pt \"Myriad Web Pro\";"))
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.pftableView = QtGui.QTableView(self.groupBox_18)
        self.pftableView.setGeometry(QtCore.QRect(11, 52, 540, 240))
        self.pftableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.pftableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.pftableView.setObjectName(_fromUtf8("pftableView"))
        self.pftableView.horizontalHeader().setStretchLastSection(True)
        self.btnNewEntity = QtGui.QPushButton(self.groupBox_18)
        self.btnNewEntity.setGeometry(QtCore.QRect(10, 21, 30, 25))
        self.btnNewEntity.setMinimumSize(QtCore.QSize(20, 20))
        self.btnNewEntity.setMaximumSize(QtCore.QSize(30, 25))
        self.btnNewEntity.setBaseSize(QtCore.QSize(30, 25))
        self.btnNewEntity.setText(_fromUtf8(""))
        self.btnNewEntity.setIcon(icon2)
        self.btnNewEntity.setObjectName(_fromUtf8("btnNewEntity"))
        self.btnEditEntity = QtGui.QPushButton(self.groupBox_18)
        self.btnEditEntity.setGeometry(QtCore.QRect(41, 21, 30, 25))
        self.btnEditEntity.setMinimumSize(QtCore.QSize(20, 20))
        self.btnEditEntity.setMaximumSize(QtCore.QSize(30, 25))
        self.btnEditEntity.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnEditEntity.setIcon(icon3)
        self.btnEditEntity.setObjectName(_fromUtf8("btnEditEntity"))
        self.btnDeleteEntity = QtGui.QPushButton(self.groupBox_18)
        self.btnDeleteEntity.setGeometry(QtCore.QRect(73, 21, 30, 25))
        self.btnDeleteEntity.setMinimumSize(QtCore.QSize(20, 20))
        self.btnDeleteEntity.setMaximumSize(QtCore.QSize(30, 25))
        self.btnDeleteEntity.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDeleteEntity.setIcon(icon4)
        self.btnDeleteEntity.setObjectName(_fromUtf8("btnDeleteEntity"))
        STDMWizard.addPage(self.wpProfile)
        self.wpEntityCustom = QtGui.QWizardPage()
        self.wpEntityCustom.setObjectName(_fromUtf8("wpEntityCustom"))
        self.groupBox = QtGui.QGroupBox(self.wpEntityCustom)
        self.groupBox.setGeometry(QtCore.QRect(0, 0, 230, 180))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.lvEntities = QtGui.QListView(self.groupBox)
        self.lvEntities.setGeometry(QtCore.QRect(10, 20, 210, 151))
        self.lvEntities.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lvEntities.setObjectName(_fromUtf8("lvEntities"))
        self.groupBox_2 = QtGui.QGroupBox(self.wpEntityCustom)
        self.groupBox_2.setGeometry(QtCore.QRect(241, 1, 340, 180))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.btnDeleteColumn = QtGui.QPushButton(self.groupBox_2)
        self.btnDeleteColumn.setGeometry(QtCore.QRect(76, 15, 30, 25))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnDeleteColumn.sizePolicy().hasHeightForWidth())
        self.btnDeleteColumn.setSizePolicy(sizePolicy)
        self.btnDeleteColumn.setMaximumSize(QtCore.QSize(50, 35))
        self.btnDeleteColumn.setText(_fromUtf8(""))
        self.btnDeleteColumn.setIcon(icon4)
        self.btnDeleteColumn.setObjectName(_fromUtf8("btnDeleteColumn"))
        self.btnEditColumn = QtGui.QPushButton(self.groupBox_2)
        self.btnEditColumn.setGeometry(QtCore.QRect(44, 15, 30, 25))
        self.btnEditColumn.setMaximumSize(QtCore.QSize(50, 40))
        self.btnEditColumn.setText(_fromUtf8(""))
        self.btnEditColumn.setIcon(icon3)
        self.btnEditColumn.setIconSize(QtCore.QSize(20, 20))
        self.btnEditColumn.setObjectName(_fromUtf8("btnEditColumn"))
        self.btnAddColumn = QtGui.QPushButton(self.groupBox_2)
        self.btnAddColumn.setGeometry(QtCore.QRect(12, 15, 30, 25))
        self.btnAddColumn.setMaximumSize(QtCore.QSize(42, 30))
        self.btnAddColumn.setText(_fromUtf8(""))
        self.btnAddColumn.setIcon(icon2)
        self.btnAddColumn.setIconSize(QtCore.QSize(20, 20))
        self.btnAddColumn.setObjectName(_fromUtf8("btnAddColumn"))
        self.tbvColumns = QtGui.QTableView(self.groupBox_2)
        self.tbvColumns.setGeometry(QtCore.QRect(10, 44, 320, 131))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbvColumns.sizePolicy().hasHeightForWidth())
        self.tbvColumns.setSizePolicy(sizePolicy)
        self.tbvColumns.setMinimumSize(QtCore.QSize(0, 0))
        self.tbvColumns.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tbvColumns.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tbvColumns.setObjectName(_fromUtf8("tbvColumns"))
        self.tbvColumns.horizontalHeader().setStretchLastSection(True)
        self.groupBox_5 = QtGui.QGroupBox(self.wpEntityCustom)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 183, 230, 190))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.lvLookups = QtGui.QListView(self.groupBox_5)
        self.lvLookups.setGeometry(QtCore.QRect(10, 50, 210, 130))
        self.lvLookups.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lvLookups.setObjectName(_fromUtf8("lvLookups"))
        self.btnEditLookup = QtGui.QPushButton(self.groupBox_5)
        self.btnEditLookup.setGeometry(QtCore.QRect(43, 20, 30, 25))
        self.btnEditLookup.setMinimumSize(QtCore.QSize(20, 25))
        self.btnEditLookup.setText(_fromUtf8(""))
        self.btnEditLookup.setIcon(icon3)
        self.btnEditLookup.setObjectName(_fromUtf8("btnEditLookup"))
        self.btnDeleteLookup = QtGui.QPushButton(self.groupBox_5)
        self.btnDeleteLookup.setGeometry(QtCore.QRect(74, 20, 30, 25))
        self.btnDeleteLookup.setMinimumSize(QtCore.QSize(20, 25))
        self.btnDeleteLookup.setText(_fromUtf8(""))
        self.btnDeleteLookup.setIcon(icon4)
        self.btnDeleteLookup.setObjectName(_fromUtf8("btnDeleteLookup"))
        self.btnAddLookup = QtGui.QPushButton(self.groupBox_5)
        self.btnAddLookup.setGeometry(QtCore.QRect(11, 20, 30, 25))
        self.btnAddLookup.setMinimumSize(QtCore.QSize(10, 25))
        self.btnAddLookup.setText(_fromUtf8(""))
        self.btnAddLookup.setIcon(icon2)
        self.btnAddLookup.setObjectName(_fromUtf8("btnAddLookup"))
        self.groupBox_6 = QtGui.QGroupBox(self.wpEntityCustom)
        self.groupBox_6.setGeometry(QtCore.QRect(240, 184, 340, 190))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.lvLookupValues = QtGui.QListView(self.groupBox_6)
        self.lvLookupValues.setGeometry(QtCore.QRect(10, 50, 320, 130))
        self.lvLookupValues.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lvLookupValues.setObjectName(_fromUtf8("lvLookupValues"))
        self.btnDeleteLkupValue = QtGui.QPushButton(self.groupBox_6)
        self.btnDeleteLkupValue.setGeometry(QtCore.QRect(72, 20, 30, 25))
        self.btnDeleteLkupValue.setMinimumSize(QtCore.QSize(0, 25))
        self.btnDeleteLkupValue.setMaximumSize(QtCore.QSize(45, 16777215))
        self.btnDeleteLkupValue.setText(_fromUtf8(""))
        self.btnDeleteLkupValue.setIcon(icon4)
        self.btnDeleteLkupValue.setObjectName(_fromUtf8("btnDeleteLkupValue"))
        self.btnEditLkupValue = QtGui.QPushButton(self.groupBox_6)
        self.btnEditLkupValue.setGeometry(QtCore.QRect(41, 20, 30, 25))
        self.btnEditLkupValue.setMinimumSize(QtCore.QSize(0, 25))
        self.btnEditLkupValue.setText(_fromUtf8(""))
        self.btnEditLkupValue.setIcon(icon3)
        self.btnEditLkupValue.setObjectName(_fromUtf8("btnEditLkupValue"))
        self.btnAddLkupValue = QtGui.QPushButton(self.groupBox_6)
        self.btnAddLkupValue.setGeometry(QtCore.QRect(10, 20, 30, 25))
        self.btnAddLkupValue.setMinimumSize(QtCore.QSize(0, 0))
        self.btnAddLkupValue.setMaximumSize(QtCore.QSize(45, 30))
        self.btnAddLkupValue.setText(_fromUtf8(""))
        self.btnAddLkupValue.setIcon(icon2)
        self.btnAddLkupValue.setObjectName(_fromUtf8("btnAddLkupValue"))
        STDMWizard.addPage(self.wpEntityCustom)
        self.wpSTR = QtGui.QWizardPage()
        self.wpSTR.setObjectName(_fromUtf8("wpSTR"))
        self.lblPartyDesc = QtGui.QLabel(self.wpSTR)
        self.lblPartyDesc.setGeometry(QtCore.QRect(10, 142, 16, 16))
        self.lblPartyDesc.setText(_fromUtf8(""))
        self.lblPartyDesc.setObjectName(_fromUtf8("lblPartyDesc"))
        self.groupBox_3 = QtGui.QGroupBox(self.wpSTR)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 124, 261, 260))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_34 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_34.setObjectName(_fromUtf8("gridLayout_34"))
        self.lvParty = QtGui.QListView(self.groupBox_3)
        self.lvParty.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lvParty.setObjectName(_fromUtf8("lvParty"))
        self.gridLayout_34.addWidget(self.lvParty, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.wpSTR)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 171, 16))
        self.label_5.setMinimumSize(QtCore.QSize(0, 0))
        self.label_5.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.cboParty = QtGui.QComboBox(self.wpSTR)
        self.cboParty.setGeometry(QtCore.QRect(20, 80, 251, 30))
        self.cboParty.setMinimumSize(QtCore.QSize(0, 30))
        self.cboParty.setMaximumSize(QtCore.QSize(600, 16777215))
        self.cboParty.setObjectName(_fromUtf8("cboParty"))
        self.label_6 = QtGui.QLabel(self.wpSTR)
        self.label_6.setGeometry(QtCore.QRect(280, 60, 191, 16))
        self.label_6.setMinimumSize(QtCore.QSize(0, 0))
        self.label_6.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.groupBox_4 = QtGui.QGroupBox(self.wpSTR)
        self.groupBox_4.setGeometry(QtCore.QRect(280, 120, 271, 260))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_35 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_35.setObjectName(_fromUtf8("gridLayout_35"))
        self.lvSpatialUnit = QtGui.QListView(self.groupBox_4)
        self.lvSpatialUnit.setObjectName(_fromUtf8("lvSpatialUnit"))
        self.gridLayout_35.addWidget(self.lvSpatialUnit, 0, 0, 1, 1)
        self.cboSPUnit = QtGui.QComboBox(self.wpSTR)
        self.cboSPUnit.setGeometry(QtCore.QRect(280, 80, 271, 30))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboSPUnit.sizePolicy().hasHeightForWidth())
        self.cboSPUnit.setSizePolicy(sizePolicy)
        self.cboSPUnit.setMinimumSize(QtCore.QSize(0, 30))
        self.cboSPUnit.setMaximumSize(QtCore.QSize(600, 16777215))
        self.cboSPUnit.setObjectName(_fromUtf8("cboSPUnit"))
        self.lblSpDesc = QtGui.QLabel(self.wpSTR)
        self.lblSpDesc.setGeometry(QtCore.QRect(10, 384, 16, 16))
        self.lblSpDesc.setText(_fromUtf8(""))
        self.lblSpDesc.setObjectName(_fromUtf8("lblSpDesc"))
        STDMWizard.addPage(self.wpSTR)
        self.wpSaveProfile = QtGui.QWizardPage()
        self.wpSaveProfile.setObjectName(_fromUtf8("wpSaveProfile"))
        self.gridLayout_10 = QtGui.QGridLayout(self.wpSaveProfile)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.scrollArea = QtGui.QScrollArea(self.wpSaveProfile)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(0, 100))
        self.scrollArea.setBaseSize(QtCore.QSize(0, 320))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 567, 375))
        self.scrollAreaWidgetContents.setMaximumSize(QtCore.QSize(800, 500))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.scrollAreaWidgetContents)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.txtHtml = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.txtHtml.setObjectName(_fromUtf8("txtHtml"))
        self.horizontalLayout_2.addWidget(self.txtHtml)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_10.addWidget(self.scrollArea, 0, 0, 1, 1)
        STDMWizard.addPage(self.wpSaveProfile)

        self.retranslateUi(STDMWizard)
        QtCore.QMetaObject.connectSlotsByName(STDMWizard)

    def retranslateUi(self, STDMWizard):
        STDMWizard.setWindowTitle(_translate("STDMWizard", "STDM Profile Wizard", None))
        self.wpLicense.setTitle(_translate("STDMWizard", "End User License Agreement", None))
        self.wpLicense.setSubTitle(_translate("STDMWizard", "Read carefully before you proceed", None))
        self.groupBox_16.setTitle(_translate("STDMWizard", "Terms and Conditions", None))
        self.rbAccpt.setText(_translate("STDMWizard", "I Agree", None))
        self.rbReject.setText(_translate("STDMWizard", "Decline", None))
        self.wpPathSetting.setTitle(_translate("STDMWizard", "Path Settings", None))
        self.wpPathSetting.setSubTitle(_translate("STDMWizard", "Set configuration and data directory path", None))
        self.groupBox_15.setTitle(_translate("STDMWizard", "Directory paths", None))
        self.label_37.setText(_translate("STDMWizard", "<html><head/><body><p>Supporting documents path</p></body></html>", None))
        self.label_4.setText(_translate("STDMWizard", "Document templates path", None))
        self.label_31.setText(_translate("STDMWizard", "Documents generated output path", None))
        self.btnDocOutput.setText(_translate("STDMWizard", "Change", None))
        self.btnTemplates.setText(_translate("STDMWizard", "Change", None))
        self.btnDocPath.setText(_translate("STDMWizard", "Change", None))
        self.wpProfile.setTitle(_translate("STDMWizard", "Profile", None))
        self.wpProfile.setSubTitle(_translate("STDMWizard", "Manage profile and related entities.  A profile represents a collection of related entities, some of which represent the party and spatial unit. Examples of profiles include household, neighbourhood or even city-wide profile.  ", None))
        self.groupBox_17.setTitle(_translate("STDMWizard", "Profile", None))
        self.label.setText(_translate("STDMWizard", "Select", None))
        self.btnPDelete.setText(_translate("STDMWizard", "Delete profile", None))
        self.btnNewP.setText(_translate("STDMWizard", "New profile", None))
        self.groupBox_18.setTitle(_translate("STDMWizard", "Profile entities ", None))
        self.wpEntityCustom.setTitle(_translate("STDMWizard", "Entity Customization", None))
        self.wpEntityCustom.setSubTitle(_translate("STDMWizard", "Add or edit entity columns, lookups and lookup values", None))
        self.groupBox.setTitle(_translate("STDMWizard", "Entities", None))
        self.groupBox_2.setTitle(_translate("STDMWizard", "Columns", None))
        self.groupBox_5.setTitle(_translate("STDMWizard", "Lookups", None))
        self.groupBox_6.setTitle(_translate("STDMWizard", "Values", None))
        self.wpSTR.setTitle(_translate("STDMWizard", "Defining Social Tenure Tables", None))
        self.wpSTR.setSubTitle(_translate("STDMWizard", "Define entities to participate in Social Tenure Relations views", None))
        self.groupBox_3.setTitle(_translate("STDMWizard", "Columns", None))
        self.label_5.setText(_translate("STDMWizard", "Party table in the STR definition", None))
        self.label_6.setText(_translate("STDMWizard", "Spatial unit table in the STR definition", None))
        self.groupBox_4.setTitle(_translate("STDMWizard", "Columns", None))
        self.wpSaveProfile.setTitle(_translate("STDMWizard", "Save Profile", None))
        self.wpSaveProfile.setSubTitle(_translate("STDMWizard", "Save your profile changes", None))

import resources_rc
