# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_admin_unit.ui'
#
# Created: Sun Jun 09 14:20:29 2013
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmAdminUnit(object):
    def setupUi(self, frmAdminUnit):
        frmAdminUnit.setObjectName(_fromUtf8("frmAdminUnit"))
        frmAdminUnit.resize(499, 423)
        self.gridLayout_2 = QtGui.QGridLayout(frmAdminUnit)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabWidget = QtGui.QTabWidget(frmAdminUnit)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 25))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout = QtGui.QGridLayout(self.tab)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tbDepartments = QtGui.QTableView(self.tab)
        self.tbDepartments.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tbDepartments.setObjectName(_fromUtf8("tbDepartments"))
        self.tbDepartments.verticalHeader().setVisible(False)
        self.gridLayout.addWidget(self.tbDepartments, 1, 0, 1, 1)
        self.btnBoxManageDpt = QtGui.QDialogButtonBox(self.tab)
        self.btnBoxManageDpt.setStandardButtons(QtGui.QDialogButtonBox.Discard|QtGui.QDialogButtonBox.Ok)
        self.btnBoxManageDpt.setObjectName(_fromUtf8("btnBoxManageDpt"))
        self.gridLayout.addWidget(self.btnBoxManageDpt, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 2)
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.cboDpt = QtGui.QComboBox(self.tab_2)
        self.cboDpt.setMinimumSize(QtCore.QSize(0, 25))
        self.cboDpt.setObjectName(_fromUtf8("cboDpt"))
        self.gridLayout_3.addWidget(self.cboDpt, 1, 1, 1, 1)
        self.btnBoxManageMunic = QtGui.QDialogButtonBox(self.tab_2)
        self.btnBoxManageMunic.setStandardButtons(QtGui.QDialogButtonBox.Discard|QtGui.QDialogButtonBox.Ok)
        self.btnBoxManageMunic.setObjectName(_fromUtf8("btnBoxManageMunic"))
        self.gridLayout_3.addWidget(self.btnBoxManageMunic, 3, 0, 1, 2)
        self.tbMunicipality = QtGui.QTableView(self.tab_2)
        self.tbMunicipality.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tbMunicipality.setObjectName(_fromUtf8("tbMunicipality"))
        self.tbMunicipality.verticalHeader().setVisible(False)
        self.gridLayout_3.addWidget(self.tbMunicipality, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_5 = QtGui.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 2)
        self.label_4 = QtGui.QLabel(self.tab_3)
        self.label_4.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 1, 0, 1, 1)
        self.cboMunicipality = QtGui.QComboBox(self.tab_3)
        self.cboMunicipality.setMinimumSize(QtCore.QSize(0, 25))
        self.cboMunicipality.setObjectName(_fromUtf8("cboMunicipality"))
        self.gridLayout_4.addWidget(self.cboMunicipality, 1, 1, 1, 1)
        self.tbSections = QtGui.QTableView(self.tab_3)
        self.tbSections.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tbSections.setObjectName(_fromUtf8("tbSections"))
        self.tbSections.verticalHeader().setVisible(False)
        self.gridLayout_4.addWidget(self.tbSections, 2, 0, 1, 2)
        self.btnBoxManageSection = QtGui.QDialogButtonBox(self.tab_3)
        self.btnBoxManageSection.setStandardButtons(QtGui.QDialogButtonBox.Discard|QtGui.QDialogButtonBox.Ok)
        self.btnBoxManageSection.setObjectName(_fromUtf8("btnBoxManageSection"))
        self.gridLayout_4.addWidget(self.btnBoxManageSection, 3, 0, 1, 2)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_6 = QtGui.QLabel(self.tab_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 2)
        self.label_7 = QtGui.QLabel(self.tab_4)
        self.label_7.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.cboMunicSections = QtGui.QComboBox(self.tab_4)
        self.cboMunicSections.setMinimumSize(QtCore.QSize(0, 25))
        self.cboMunicSections.setObjectName(_fromUtf8("cboMunicSections"))
        self.gridLayout_5.addWidget(self.cboMunicSections, 1, 1, 1, 1)
        self.tbLocality = QtGui.QTableView(self.tab_4)
        self.tbLocality.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tbLocality.setObjectName(_fromUtf8("tbLocality"))
        self.tbLocality.verticalHeader().setVisible(False)
        self.gridLayout_5.addWidget(self.tbLocality, 2, 0, 1, 2)
        self.btnBoxManageLocality = QtGui.QDialogButtonBox(self.tab_4)
        self.btnBoxManageLocality.setStandardButtons(QtGui.QDialogButtonBox.Discard|QtGui.QDialogButtonBox.Ok)
        self.btnBoxManageLocality.setObjectName(_fromUtf8("btnBoxManageLocality"))
        self.gridLayout_5.addWidget(self.btnBoxManageLocality, 3, 0, 1, 2)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(frmAdminUnit)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmAdminUnit)

    def retranslateUi(self, frmAdminUnit):
        frmAdminUnit.setWindowTitle(QtGui.QApplication.translate("frmAdminUnit", "Manage Administrative Units", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("frmAdminUnit", "<html><head/><body><p>Double click on an item in the table below to edit the department details</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), QtGui.QApplication.translate("frmAdminUnit", "Department", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("frmAdminUnit", "<html><head/><body><p>Double click on an item in the table below to edit the municipality details</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("frmAdminUnit", "Filter By Department", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), QtGui.QApplication.translate("frmAdminUnit", "Municipality", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("frmAdminUnit", "<html><head/><body><p>Double click on an item in the table below to edit the municipality section details</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("frmAdminUnit", "Filter By Municipality", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), QtGui.QApplication.translate("frmAdminUnit", "Section", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("frmAdminUnit", "<html><head/><body><p>Double click on an item in the table below to edit the locality details</p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("frmAdminUnit", "Filter By Municipality Section", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), QtGui.QApplication.translate("frmAdminUnit", "Locality", None, QtGui.QApplication.UnicodeUTF8))

