# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_quick_settings.ui'
#
# Created: Mon Sep 01 11:02:58 2014
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmAbout(object):
    def setupUi(self, frmAbout):
        frmAbout.setObjectName(_fromUtf8("frmAbout"))
        frmAbout.resize(678, 520)
        self.gridLayout = QtGui.QGridLayout(frmAbout)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.listWidget = QtGui.QListWidget(frmAbout)
        self.listWidget.setMaximumSize(QtCore.QSize(150, 16777215))
        self.listWidget.setObjectName(_fromUtf8("listWidget"))
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        item = QtGui.QListWidgetItem()
        self.listWidget.addItem(item)
        self.gridLayout.addWidget(self.listWidget, 0, 0, 1, 1)
        self.scrollArea = QtGui.QScrollArea(frmAbout)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 502, 471))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.stackedWidget = QtGui.QStackedWidget(self.scrollAreaWidgetContents)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.settingPg = QtGui.QWidget()
        self.settingPg.setObjectName(_fromUtf8("settingPg"))
        self.gridLayout_5 = QtGui.QGridLayout(self.settingPg)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.groupBox = QtGui.QGroupBox(self.settingPg)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 100))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.comboBox = QtGui.QComboBox(self.groupBox)
        self.comboBox.setObjectName(_fromUtf8("comboBox"))
        self.gridLayout_4.addWidget(self.comboBox, 0, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setMaximumSize(QtCore.QSize(70, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox, 1, 0, 1, 1)
        self.vlNotification = QtGui.QVBoxLayout()
        self.vlNotification.setObjectName(_fromUtf8("vlNotification"))
        self.gridLayout_5.addLayout(self.vlNotification, 0, 0, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.settingPg)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.lineEdit = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.gridLayout_3.addWidget(self.lineEdit, 1, 1, 1, 1)
        self.lineEdit_2 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_2.setObjectName(_fromUtf8("lineEdit_2"))
        self.gridLayout_3.addWidget(self.lineEdit_2, 2, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_2 = QtGui.QComboBox(self.groupBox_2)
        self.comboBox_2.setObjectName(_fromUtf8("comboBox_2"))
        self.gridLayout_3.addWidget(self.comboBox_2, 0, 1, 1, 1)
        self.gridLayout_5.addWidget(self.groupBox_2, 2, 0, 1, 1)
        self.pushButton = QtGui.QPushButton(self.settingPg)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_5.addWidget(self.pushButton, 3, 0, 1, 1)
        self.stackedWidget.addWidget(self.settingPg)
        self.pageNew = QtGui.QWidget()
        self.pageNew.setObjectName(_fromUtf8("pageNew"))
        self.gridLayout_6 = QtGui.QGridLayout(self.pageNew)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.textEdit = QtGui.QTextEdit(self.pageNew)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_6.addWidget(self.textEdit, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageNew)
        self.pageAbout = QtGui.QWidget()
        self.pageAbout.setObjectName(_fromUtf8("pageAbout"))
        self.gridLayout_7 = QtGui.QGridLayout(self.pageAbout)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.txtAbout = QtGui.QTextEdit(self.pageAbout)
        self.txtAbout.setReadOnly(True)
        self.txtAbout.setObjectName(_fromUtf8("txtAbout"))
        self.gridLayout_7.addWidget(self.txtAbout, 0, 0, 1, 2)
        self.btnSTDMHome = QtGui.QPushButton(self.pageAbout)
        self.btnSTDMHome.setMinimumSize(QtCore.QSize(0, 30))
        self.btnSTDMHome.setObjectName(_fromUtf8("btnSTDMHome"))
        self.gridLayout_7.addWidget(self.btnSTDMHome, 1, 0, 1, 1)
        self.btnContactUs = QtGui.QPushButton(self.pageAbout)
        self.btnContactUs.setMinimumSize(QtCore.QSize(0, 30))
        self.btnContactUs.setObjectName(_fromUtf8("btnContactUs"))
        self.gridLayout_7.addWidget(self.btnContactUs, 1, 1, 1, 1)
        self.stackedWidget.addWidget(self.pageAbout)
        self.pageLicense = QtGui.QWidget()
        self.pageLicense.setObjectName(_fromUtf8("pageLicense"))
        self.gridLayout_8 = QtGui.QGridLayout(self.pageLicense)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.textEdit_2 = QtGui.QTextEdit(self.pageLicense)
        self.textEdit_2.setObjectName(_fromUtf8("textEdit_2"))
        self.gridLayout_8.addWidget(self.textEdit_2, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageLicense)
        self.pageCommittee = QtGui.QWidget()
        self.pageCommittee.setObjectName(_fromUtf8("pageCommittee"))
        self.gridLayout_9 = QtGui.QGridLayout(self.pageCommittee)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.textEdit_3 = QtGui.QTextEdit(self.pageCommittee)
        self.textEdit_3.setObjectName(_fromUtf8("textEdit_3"))
        self.gridLayout_9.addWidget(self.textEdit_3, 0, 0, 1, 1)
        self.stackedWidget.addWidget(self.pageCommittee)
        self.gridLayout_2.addWidget(self.stackedWidget, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(frmAbout)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Close)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 2)

        self.retranslateUi(frmAbout)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("clicked(QAbstractButton*)")), frmAbout.close)
        QtCore.QMetaObject.connectSlotsByName(frmAbout)

    def retranslateUi(self, frmAbout):
        frmAbout.setWindowTitle(_translate("frmAbout", "Dialog", None))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        item = self.listWidget.item(0)
        item.setText(_translate("frmAbout", "Settings", None))
        item = self.listWidget.item(1)
        item.setText(_translate("frmAbout", "What\'s new", None))
        item = self.listWidget.item(2)
        item.setText(_translate("frmAbout", "About", None))
        item = self.listWidget.item(3)
        item.setText(_translate("frmAbout", "License", None))
        item = self.listWidget.item(4)
        item.setText(_translate("frmAbout", "Committee", None))
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.groupBox.setTitle(_translate("frmAbout", "User Profile", None))
        self.label_4.setText(_translate("frmAbout", "Current Profile", None))
        self.groupBox_2.setTitle(_translate("frmAbout", "Server Connections", None))
        self.label.setText(_translate("frmAbout", "Database", None))
        self.label_3.setText(_translate("frmAbout", "Port", None))
        self.label_2.setText(_translate("frmAbout", "Host", None))
        self.pushButton.setText(_translate("frmAbout", "Update", None))
        self.btnSTDMHome.setText(_translate("frmAbout", "STDM Home Page", None))
        self.btnContactUs.setText(_translate("frmAbout", "Contact Us", None))

