# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_column_editor.ui'
#
# Created: Fri Feb 12 16:04:04 2016
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_editor(object):
    def setupUi(self, editor):
        editor.setObjectName(_fromUtf8("editor"))
        editor.resize(511, 454)
        self.gridLayout = QtGui.QGridLayout(editor)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(editor)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(editor)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.edtColLen = QtGui.QLineEdit(self.groupBox)
        self.edtColLen.setObjectName(_fromUtf8("edtColLen"))
        self.gridLayout_2.addWidget(self.edtColLen, 4, 1, 1, 1)
        self.cbSearch = QtGui.QCheckBox(self.groupBox)
        self.cbSearch.setText(_fromUtf8(""))
        self.cbSearch.setObjectName(_fromUtf8("cbSearch"))
        self.gridLayout_2.addWidget(self.cbSearch, 10, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_2.addWidget(self.label_4, 2, 0, 1, 1)
        self.cboDataType = QtGui.QComboBox(self.groupBox)
        self.cboDataType.setEditable(False)
        self.cboDataType.setObjectName(_fromUtf8("cboDataType"))
        self.gridLayout_2.addWidget(self.cboDataType, 2, 1, 1, 2)
        self.edtColName = QtGui.QLineEdit(self.groupBox)
        self.edtColName.setObjectName(_fromUtf8("edtColName"))
        self.gridLayout_2.addWidget(self.edtColName, 0, 1, 1, 2)
        self.edtColDesc = QtGui.QLineEdit(self.groupBox)
        self.edtColDesc.setObjectName(_fromUtf8("edtColDesc"))
        self.gridLayout_2.addWidget(self.edtColDesc, 1, 1, 1, 2)
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_2.addWidget(self.label, 8, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_2.addWidget(self.label_5, 4, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 12, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_2.addWidget(self.label_6, 10, 0, 1, 1)
        self.cbMandt = QtGui.QCheckBox(self.groupBox)
        self.cbMandt.setText(_fromUtf8(""))
        self.cbMandt.setChecked(False)
        self.cbMandt.setObjectName(_fromUtf8("cbMandt"))
        self.gridLayout_2.addWidget(self.cbMandt, 8, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 11, 0, 1, 1)
        self.cbIndex = QtGui.QCheckBox(self.groupBox)
        self.cbIndex.setText(_fromUtf8(""))
        self.cbIndex.setObjectName(_fromUtf8("cbIndex"))
        self.gridLayout_2.addWidget(self.cbIndex, 12, 1, 1, 1)
        self.cbUnique = QtGui.QCheckBox(self.groupBox)
        self.cbUnique.setText(_fromUtf8(""))
        self.cbUnique.setObjectName(_fromUtf8("cbUnique"))
        self.gridLayout_2.addWidget(self.cbUnique, 11, 1, 1, 1)
        self.swColProp = QtGui.QStackedWidget(self.groupBox)
        self.swColProp.setMinimumSize(QtCore.QSize(0, 5))
        self.swColProp.setMaximumSize(QtCore.QSize(16777215, 75))
        self.swColProp.setObjectName(_fromUtf8("swColProp"))
        self.pgDefVal = QtGui.QWidget()
        self.pgDefVal.setObjectName(_fromUtf8("pgDefVal"))
        self.edtDefValue = QtGui.QLineEdit(self.pgDefVal)
        self.edtDefValue.setGeometry(QtCore.QRect(3, 16, 340, 20))
        self.edtDefValue.setText(_fromUtf8(""))
        self.edtDefValue.setObjectName(_fromUtf8("edtDefValue"))
        self.swColProp.addWidget(self.pgDefVal)
        self.pgDoubleDef = QtGui.QWidget()
        self.pgDoubleDef.setObjectName(_fromUtf8("pgDoubleDef"))
        self.label_9 = QtGui.QLabel(self.pgDoubleDef)
        self.label_9.setGeometry(QtCore.QRect(10, 0, 46, 13))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.label_19 = QtGui.QLabel(self.pgDoubleDef)
        self.label_19.setGeometry(QtCore.QRect(10, 30, 46, 13))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.sbPres = QtGui.QSpinBox(self.pgDoubleDef)
        self.sbPres.setGeometry(QtCore.QRect(60, 0, 51, 22))
        self.sbPres.setObjectName(_fromUtf8("sbPres"))
        self.sbScale = QtGui.QSpinBox(self.pgDoubleDef)
        self.sbScale.setGeometry(QtCore.QRect(60, 25, 51, 22))
        self.sbScale.setObjectName(_fromUtf8("sbScale"))
        self.swColProp.addWidget(self.pgDoubleDef)
        self.pgDateVal = QtGui.QWidget()
        self.pgDateVal.setObjectName(_fromUtf8("pgDateVal"))
        self.label_12 = QtGui.QLabel(self.pgDateVal)
        self.label_12.setGeometry(QtCore.QRect(20, 8, 46, 13))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.edtMinDate = QtGui.QDateEdit(self.pgDateVal)
        self.edtMinDate.setGeometry(QtCore.QRect(80, 4, 171, 22))
        self.edtMinDate.setObjectName(_fromUtf8("edtMinDate"))
        self.label_13 = QtGui.QLabel(self.pgDateVal)
        self.label_13.setGeometry(QtCore.QRect(20, 40, 46, 13))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.edtMaxDate = QtGui.QDateEdit(self.pgDateVal)
        self.edtMaxDate.setGeometry(QtCore.QRect(80, 36, 171, 22))
        self.edtMaxDate.setObjectName(_fromUtf8("edtMaxDate"))
        self.swColProp.addWidget(self.pgDateVal)
        self.pgDTimeVal = QtGui.QWidget()
        self.pgDTimeVal.setObjectName(_fromUtf8("pgDTimeVal"))
        self.label_14 = QtGui.QLabel(self.pgDTimeVal)
        self.label_14.setGeometry(QtCore.QRect(10, 3, 46, 13))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_15 = QtGui.QLabel(self.pgDTimeVal)
        self.label_15.setGeometry(QtCore.QRect(10, 34, 46, 13))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.edtMinDTime = QtGui.QDateTimeEdit(self.pgDTimeVal)
        self.edtMinDTime.setGeometry(QtCore.QRect(70, 0, 194, 22))
        self.edtMinDTime.setObjectName(_fromUtf8("edtMinDTime"))
        self.edtMaxDTime = QtGui.QDateTimeEdit(self.pgDTimeVal)
        self.edtMaxDTime.setGeometry(QtCore.QRect(69, 30, 194, 22))
        self.edtMaxDTime.setObjectName(_fromUtf8("edtMaxDTime"))
        self.swColProp.addWidget(self.pgDTimeVal)
        self.pgForeignVal = QtGui.QWidget()
        self.pgForeignVal.setObjectName(_fromUtf8("pgForeignVal"))
        self.label_16 = QtGui.QLabel(self.pgForeignVal)
        self.label_16.setGeometry(QtCore.QRect(20, 0, 71, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.label_17 = QtGui.QLabel(self.pgForeignVal)
        self.label_17.setGeometry(QtCore.QRect(7, 27, 81, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.cboParentEntity = QtGui.QComboBox(self.pgForeignVal)
        self.cboParentEntity.setGeometry(QtCore.QRect(93, 0, 221, 20))
        self.cboParentEntity.setObjectName(_fromUtf8("cboParentEntity"))
        self.cboParentCol = QtGui.QComboBox(self.pgForeignVal)
        self.cboParentCol.setGeometry(QtCore.QRect(93, 25, 221, 20))
        self.cboParentCol.setObjectName(_fromUtf8("cboParentCol"))
        self.lbldispCol = QtGui.QLabel(self.pgForeignVal)
        self.lbldispCol.setGeometry(QtCore.QRect(10, 50, 81, 16))
        self.lbldispCol.setObjectName(_fromUtf8("lbldispCol"))
        self.cboDispCol = QtGui.QComboBox(self.pgForeignVal)
        self.cboDispCol.setGeometry(QtCore.QRect(93, 50, 221, 20))
        self.cboDispCol.setObjectName(_fromUtf8("cboDispCol"))
        self.swColProp.addWidget(self.pgForeignVal)
        self.pgLookupVal = QtGui.QWidget()
        self.pgLookupVal.setObjectName(_fromUtf8("pgLookupVal"))
        self.label_18 = QtGui.QLabel(self.pgLookupVal)
        self.label_18.setGeometry(QtCore.QRect(3, 17, 71, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.cboLookup = QtGui.QComboBox(self.pgLookupVal)
        self.cboLookup.setGeometry(QtCore.QRect(69, 15, 210, 22))
        self.cboLookup.setObjectName(_fromUtf8("cboLookup"))
        self.btnNewLookup = QtGui.QPushButton(self.pgLookupVal)
        self.btnNewLookup.setGeometry(QtCore.QRect(288, 15, 51, 23))
        self.btnNewLookup.setObjectName(_fromUtf8("btnNewLookup"))
        self.swColProp.addWidget(self.pgLookupVal)
        self.pgGeoVal = QtGui.QWidget()
        self.pgGeoVal.setObjectName(_fromUtf8("pgGeoVal"))
        self.label_20 = QtGui.QLabel(self.pgGeoVal)
        self.label_20.setGeometry(QtCore.QRect(10, 6, 80, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.cboGeoType = QtGui.QComboBox(self.pgGeoVal)
        self.cboGeoType.setGeometry(QtCore.QRect(111, 0, 191, 22))
        self.cboGeoType.setObjectName(_fromUtf8("cboGeoType"))
        self.btnCoord = QtGui.QPushButton(self.pgGeoVal)
        self.btnCoord.setGeometry(QtCore.QRect(110, 35, 190, 23))
        self.btnCoord.setObjectName(_fromUtf8("btnCoord"))
        self.label_21 = QtGui.QLabel(self.pgGeoVal)
        self.label_21.setGeometry(QtCore.QRect(10, 40, 90, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.swColProp.addWidget(self.pgGeoVal)
        self.gridLayout_2.addWidget(self.swColProp, 5, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setMinimumSize(QtCore.QSize(0, 5))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 200))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 5, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 6, 0, 1, 1)
        self.edtUserTip = QtGui.QLineEdit(self.groupBox)
        self.edtUserTip.setObjectName(_fromUtf8("edtUserTip"))
        self.gridLayout_2.addWidget(self.edtUserTip, 6, 1, 1, 1)
        self.gridLayout.addWidget(self.groupBox, 0, 0, 1, 1)

        self.retranslateUi(editor)
        self.swColProp.setCurrentIndex(6)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), editor.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), editor.reject)
        QtCore.QMetaObject.connectSlotsByName(editor)

    def retranslateUi(self, editor):
        editor.setWindowTitle(_translate("editor", "Table Attributes", None))
        self.groupBox.setTitle(_translate("editor", "Add Table Column", None))
        self.edtColLen.setPlaceholderText(_translate("editor", "Column length", None))
        self.label_4.setText(_translate("editor", "Column Data Type", None))
        self.edtColName.setPlaceholderText(_translate("editor", "Enter column name", None))
        self.edtColDesc.setPlaceholderText(_translate("editor", "Column Description", None))
        self.label_3.setText(_translate("editor", "Description", None))
        self.label_2.setText(_translate("editor", "Column Name", None))
        self.label.setText(_translate("editor", "Is Mandatory Field", None))
        self.label_5.setText(_translate("editor", "Character Length", None))
        self.label_10.setText(_translate("editor", "Index Column", None))
        self.label_6.setText(_translate("editor", "Is Searchable", None))
        self.label_7.setText(_translate("editor", "Is Unique", None))
        self.edtDefValue.setPlaceholderText(_translate("editor", "Default value will be provided if user does not specify", None))
        self.label_9.setText(_translate("editor", "Precision", None))
        self.label_19.setText(_translate("editor", "Scale", None))
        self.label_12.setText(_translate("editor", "Min. Date", None))
        self.label_13.setText(_translate("editor", "Max Date", None))
        self.label_14.setText(_translate("editor", "Min.Date", None))
        self.label_15.setText(_translate("editor", "Max.Date", None))
        self.label_16.setText(_translate("editor", "Parent Entity", None))
        self.label_17.setText(_translate("editor", "Relation Column", None))
        self.lbldispCol.setText(_translate("editor", "Display Column", None))
        self.label_18.setText(_translate("editor", "Lookup Entity", None))
        self.btnNewLookup.setText(_translate("editor", "New ...", None))
        self.label_20.setText(_translate("editor", "Geometry Type", None))
        self.btnCoord.setText(_translate("editor", "Select ...", None))
        self.label_21.setText(_translate("editor", "Coordinate System", None))
        self.label_8.setText(_translate("editor", "Column Properties", None))
        self.label_11.setText(_translate("editor", "User Tip", None))
        self.edtUserTip.setPlaceholderText(_translate("editor", "Enter text to appear in the form as a tooltip", None))

