# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '..\ui_document_downloader_win.ui'
#
# Created: Thu Aug 08 18:03:57 2024
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DocumentDownloader(object):
    def setupUi(self, DocumentDownloader):
        DocumentDownloader.setObjectName(_fromUtf8("DocumentDownloader"))
        DocumentDownloader.resize(690, 761)
        self.centralwidget = QtGui.QWidget(DocumentDownloader)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.twDocument = QtGui.QTabWidget(self.centralwidget)
        self.twDocument.setObjectName(_fromUtf8("twDocument"))
        self.tbDownload = QtGui.QWidget()
        self.tbDownload.setObjectName(_fromUtf8("tbDownload"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tbDownload)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.tbDownload)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rbKoboMedia = QtGui.QRadioButton(self.groupBox_2)
        self.rbKoboMedia.setAutoExclusive(False)
        self.rbKoboMedia.setObjectName(_fromUtf8("rbKoboMedia"))
        self.horizontalLayout.addWidget(self.rbKoboMedia)
        self.rbSupportDoc = QtGui.QRadioButton(self.groupBox_2)
        self.rbSupportDoc.setAutoExclusive(False)
        self.rbSupportDoc.setObjectName(_fromUtf8("rbSupportDoc"))
        self.horizontalLayout.addWidget(self.rbSupportDoc)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(self.tbDownload)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.txtDataSource = QtGui.QLineEdit(self.groupBox)
        self.txtDataSource.setMaxLength(200)
        self.txtDataSource.setObjectName(_fromUtf8("txtDataSource"))
        self.horizontalLayout_2.addWidget(self.txtDataSource)
        self.btnBrowseSource = QtGui.QPushButton(self.groupBox)
        self.btnBrowseSource.setObjectName(_fromUtf8("btnBrowseSource"))
        self.horizontalLayout_2.addWidget(self.btnBrowseSource)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_7 = QtGui.QGroupBox(self.tbDownload)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_7)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_7)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.edtKoboUsername = QtGui.QLineEdit(self.groupBox_7)
        self.edtKoboUsername.setReadOnly(False)
        self.edtKoboUsername.setObjectName(_fromUtf8("edtKoboUsername"))
        self.gridLayout_4.addWidget(self.edtKoboUsername, 1, 1, 1, 1)
        self.edtKoboPassword = QtGui.QLineEdit(self.groupBox_7)
        self.edtKoboPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.edtKoboPassword.setObjectName(_fromUtf8("edtKoboPassword"))
        self.gridLayout_4.addWidget(self.edtKoboPassword, 2, 1, 1, 1)
        self.edtMediaUrl = QtGui.QLineEdit(self.groupBox_7)
        self.edtMediaUrl.setReadOnly(False)
        self.edtMediaUrl.setObjectName(_fromUtf8("edtMediaUrl"))
        self.gridLayout_4.addWidget(self.edtMediaUrl, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_7)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.tbDownload)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayout_2 = QtGui.QGridLayout()
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_7 = QtGui.QLabel(self.groupBox_8)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_2.addWidget(self.label_7, 0, 0, 1, 1)
        self.edtPersonSignatureFolder = QtGui.QLineEdit(self.groupBox_8)
        self.edtPersonSignatureFolder.setObjectName(_fromUtf8("edtPersonSignatureFolder"))
        self.gridLayout_2.addWidget(self.edtPersonSignatureFolder, 0, 1, 1, 1)
        self.cbPersonSignature = QtGui.QCheckBox(self.groupBox_8)
        self.cbPersonSignature.setCheckable(True)
        self.cbPersonSignature.setObjectName(_fromUtf8("cbPersonSignature"))
        self.gridLayout_2.addWidget(self.cbPersonSignature, 0, 2, 1, 1)
        self.tbPersonSignature = QtGui.QToolButton(self.groupBox_8)
        self.tbPersonSignature.setObjectName(_fromUtf8("tbPersonSignature"))
        self.gridLayout_2.addWidget(self.tbPersonSignature, 0, 3, 1, 1)
        self.btnPersonSignature = QtGui.QPushButton(self.groupBox_8)
        self.btnPersonSignature.setObjectName(_fromUtf8("btnPersonSignature"))
        self.gridLayout_2.addWidget(self.btnPersonSignature, 0, 4, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_8)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_2.addWidget(self.label_8, 1, 0, 1, 1)
        self.edtSignFolder = QtGui.QLineEdit(self.groupBox_8)
        self.edtSignFolder.setObjectName(_fromUtf8("edtSignFolder"))
        self.gridLayout_2.addWidget(self.edtSignFolder, 1, 1, 1, 1)
        self.cbHHoldSignature = QtGui.QCheckBox(self.groupBox_8)
        self.cbHHoldSignature.setObjectName(_fromUtf8("cbHHoldSignature"))
        self.gridLayout_2.addWidget(self.cbHHoldSignature, 1, 2, 1, 1)
        self.tbHHoldSignature = QtGui.QToolButton(self.groupBox_8)
        self.tbHHoldSignature.setObjectName(_fromUtf8("tbHHoldSignature"))
        self.gridLayout_2.addWidget(self.tbHHoldSignature, 1, 3, 1, 1)
        self.btnHHoldSignatureFolder = QtGui.QPushButton(self.groupBox_8)
        self.btnHHoldSignatureFolder.setObjectName(_fromUtf8("btnHHoldSignatureFolder"))
        self.gridLayout_2.addWidget(self.btnHHoldSignatureFolder, 1, 4, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_8)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.edtFingerPrintFolder = QtGui.QLineEdit(self.groupBox_8)
        self.edtFingerPrintFolder.setObjectName(_fromUtf8("edtFingerPrintFolder"))
        self.gridLayout_2.addWidget(self.edtFingerPrintFolder, 2, 1, 1, 1)
        self.cbFingerPrint = QtGui.QCheckBox(self.groupBox_8)
        self.cbFingerPrint.setObjectName(_fromUtf8("cbFingerPrint"))
        self.gridLayout_2.addWidget(self.cbFingerPrint, 2, 2, 1, 1)
        self.tbFingerPrint = QtGui.QToolButton(self.groupBox_8)
        self.tbFingerPrint.setObjectName(_fromUtf8("tbFingerPrint"))
        self.gridLayout_2.addWidget(self.tbFingerPrint, 2, 3, 1, 1)
        self.btnFingerPrint = QtGui.QPushButton(self.groupBox_8)
        self.btnFingerPrint.setObjectName(_fromUtf8("btnFingerPrint"))
        self.gridLayout_2.addWidget(self.btnFingerPrint, 2, 4, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_8)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.edtHHoldPhotoFolder = QtGui.QLineEdit(self.groupBox_8)
        self.edtHHoldPhotoFolder.setObjectName(_fromUtf8("edtHHoldPhotoFolder"))
        self.gridLayout_2.addWidget(self.edtHHoldPhotoFolder, 3, 1, 1, 1)
        self.cbHHoldPhoto = QtGui.QCheckBox(self.groupBox_8)
        self.cbHHoldPhoto.setObjectName(_fromUtf8("cbHHoldPhoto"))
        self.gridLayout_2.addWidget(self.cbHHoldPhoto, 3, 2, 1, 1)
        self.tbHHoldPhoto = QtGui.QToolButton(self.groupBox_8)
        self.tbHHoldPhoto.setObjectName(_fromUtf8("tbHHoldPhoto"))
        self.gridLayout_2.addWidget(self.tbHHoldPhoto, 3, 3, 1, 1)
        self.btnHHoldPhotoFolder = QtGui.QPushButton(self.groupBox_8)
        self.btnHHoldPhotoFolder.setObjectName(_fromUtf8("btnHHoldPhotoFolder"))
        self.gridLayout_2.addWidget(self.btnHHoldPhotoFolder, 3, 4, 1, 1)
        self.label_12 = QtGui.QLabel(self.groupBox_8)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 4, 0, 1, 1)
        self.edtFamilyPhoto = QtGui.QLineEdit(self.groupBox_8)
        self.edtFamilyPhoto.setObjectName(_fromUtf8("edtFamilyPhoto"))
        self.gridLayout_2.addWidget(self.edtFamilyPhoto, 4, 1, 1, 1)
        self.cbFamilyPhoto = QtGui.QCheckBox(self.groupBox_8)
        self.cbFamilyPhoto.setObjectName(_fromUtf8("cbFamilyPhoto"))
        self.gridLayout_2.addWidget(self.cbFamilyPhoto, 4, 2, 1, 1)
        self.tbFamilyPhoto = QtGui.QToolButton(self.groupBox_8)
        self.tbFamilyPhoto.setObjectName(_fromUtf8("tbFamilyPhoto"))
        self.gridLayout_2.addWidget(self.tbFamilyPhoto, 4, 3, 1, 1)
        self.btnFamilyPhotoFolder = QtGui.QPushButton(self.groupBox_8)
        self.btnFamilyPhotoFolder.setObjectName(_fromUtf8("btnFamilyPhotoFolder"))
        self.gridLayout_2.addWidget(self.btnFamilyPhotoFolder, 4, 4, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayout_2)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem = QtGui.QSpacerItem(20, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.btnDownload = QtGui.QPushButton(self.tbDownload)
        self.btnDownload.setMinimumSize(QtCore.QSize(200, 0))
        self.btnDownload.setObjectName(_fromUtf8("btnDownload"))
        self.horizontalLayout_4.addWidget(self.btnDownload)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.twDocument.addTab(self.tbDownload, _fromUtf8(""))
        self.tbUpload = QtGui.QWidget()
        self.tbUpload.setObjectName(_fromUtf8("tbUpload"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tbUpload)
        self.verticalLayout_3.setSpacing(15)
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 9)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.btnUpload = QtGui.QPushButton(self.tbUpload)
        self.btnUpload.setObjectName(_fromUtf8("btnUpload"))
        self.horizontalLayout_6.addWidget(self.btnUpload)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.groupBox_5 = QtGui.QGroupBox(self.tbUpload)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.rbScannedDoc = QtGui.QRadioButton(self.groupBox_5)
        self.rbScannedDoc.setObjectName(_fromUtf8("rbScannedDoc"))
        self.horizontalLayout_5.addWidget(self.rbScannedDoc)
        self.rbCSV = QtGui.QRadioButton(self.groupBox_5)
        self.rbCSV.setObjectName(_fromUtf8("rbCSV"))
        self.horizontalLayout_5.addWidget(self.rbCSV)
        self.verticalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_4 = QtGui.QGroupBox(self.tbUpload)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tbScannedDoc = QtGui.QToolButton(self.groupBox_4)
        self.tbScannedDoc.setObjectName(_fromUtf8("tbScannedDoc"))
        self.gridLayout.addWidget(self.tbScannedDoc, 0, 3, 1, 1)
        self.edtScannedDoc = QtGui.QLineEdit(self.groupBox_4)
        self.edtScannedDoc.setObjectName(_fromUtf8("edtScannedDoc"))
        self.gridLayout.addWidget(self.edtScannedDoc, 0, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.cbScannedDoc = QtGui.QCheckBox(self.groupBox_4)
        self.cbScannedDoc.setObjectName(_fromUtf8("cbScannedDoc"))
        self.gridLayout.addWidget(self.cbScannedDoc, 0, 2, 1, 1)
        self.btnScannedDoc = QtGui.QPushButton(self.groupBox_4)
        self.btnScannedDoc.setObjectName(_fromUtf8("btnScannedDoc"))
        self.gridLayout.addWidget(self.btnScannedDoc, 0, 4, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_4)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_4)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.groupBox_4)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout.addWidget(self.label_13, 3, 0, 1, 1)
        self.edtScannedHseMap = QtGui.QLineEdit(self.groupBox_4)
        self.edtScannedHseMap.setObjectName(_fromUtf8("edtScannedHseMap"))
        self.gridLayout.addWidget(self.edtScannedHseMap, 1, 1, 1, 1)
        self.edtScannedHsePic = QtGui.QLineEdit(self.groupBox_4)
        self.edtScannedHsePic.setObjectName(_fromUtf8("edtScannedHsePic"))
        self.gridLayout.addWidget(self.edtScannedHsePic, 2, 1, 1, 1)
        self.edtScannedIdDoc = QtGui.QLineEdit(self.groupBox_4)
        self.edtScannedIdDoc.setObjectName(_fromUtf8("edtScannedIdDoc"))
        self.gridLayout.addWidget(self.edtScannedIdDoc, 3, 1, 1, 1)
        self.cbScannedHseMap = QtGui.QCheckBox(self.groupBox_4)
        self.cbScannedHseMap.setObjectName(_fromUtf8("cbScannedHseMap"))
        self.gridLayout.addWidget(self.cbScannedHseMap, 1, 2, 1, 1)
        self.cbScannedHsePic = QtGui.QCheckBox(self.groupBox_4)
        self.cbScannedHsePic.setObjectName(_fromUtf8("cbScannedHsePic"))
        self.gridLayout.addWidget(self.cbScannedHsePic, 2, 2, 1, 1)
        self.cbScannedIdDoc = QtGui.QCheckBox(self.groupBox_4)
        self.cbScannedIdDoc.setObjectName(_fromUtf8("cbScannedIdDoc"))
        self.gridLayout.addWidget(self.cbScannedIdDoc, 3, 2, 1, 1)
        self.tbScannedHseMap = QtGui.QToolButton(self.groupBox_4)
        self.tbScannedHseMap.setObjectName(_fromUtf8("tbScannedHseMap"))
        self.gridLayout.addWidget(self.tbScannedHseMap, 1, 3, 1, 1)
        self.tbScannedHsePic = QtGui.QToolButton(self.groupBox_4)
        self.tbScannedHsePic.setObjectName(_fromUtf8("tbScannedHsePic"))
        self.gridLayout.addWidget(self.tbScannedHsePic, 2, 3, 1, 1)
        self.tbScannedIdDoc = QtGui.QToolButton(self.groupBox_4)
        self.tbScannedIdDoc.setObjectName(_fromUtf8("tbScannedIdDoc"))
        self.gridLayout.addWidget(self.tbScannedIdDoc, 3, 3, 1, 1)
        self.btnScannedHseMap = QtGui.QPushButton(self.groupBox_4)
        self.btnScannedHseMap.setObjectName(_fromUtf8("btnScannedHseMap"))
        self.gridLayout.addWidget(self.btnScannedHseMap, 1, 4, 1, 1)
        self.btnScannedHsePic = QtGui.QPushButton(self.groupBox_4)
        self.btnScannedHsePic.setObjectName(_fromUtf8("btnScannedHsePic"))
        self.gridLayout.addWidget(self.btnScannedHsePic, 2, 4, 1, 1)
        self.btnScannedIdDoc = QtGui.QPushButton(self.groupBox_4)
        self.btnScannedIdDoc.setObjectName(_fromUtf8("btnScannedIdDoc"))
        self.gridLayout.addWidget(self.btnScannedIdDoc, 3, 4, 1, 1)
        self.verticalLayout_5.addLayout(self.gridLayout)
        self.line = QtGui.QFrame(self.groupBox_4)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_5.addWidget(self.line)
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_16 = QtGui.QLabel(self.groupBox_4)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 1, 0, 1, 1)
        self.edtScannedSignature = QtGui.QLineEdit(self.groupBox_4)
        self.edtScannedSignature.setObjectName(_fromUtf8("edtScannedSignature"))
        self.gridLayout_3.addWidget(self.edtScannedSignature, 4, 1, 1, 1)
        self.edtScannedFamilyPhoto = QtGui.QLineEdit(self.groupBox_4)
        self.edtScannedFamilyPhoto.setObjectName(_fromUtf8("edtScannedFamilyPhoto"))
        self.gridLayout_3.addWidget(self.edtScannedFamilyPhoto, 3, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.groupBox_4)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 3, 0, 1, 1)
        self.cbScannedFamilyPhoto = QtGui.QCheckBox(self.groupBox_4)
        self.cbScannedFamilyPhoto.setObjectName(_fromUtf8("cbScannedFamilyPhoto"))
        self.gridLayout_3.addWidget(self.cbScannedFamilyPhoto, 3, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.groupBox_4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 4, 0, 1, 1)
        self.tbScannedFamilyPhoto = QtGui.QToolButton(self.groupBox_4)
        self.tbScannedFamilyPhoto.setObjectName(_fromUtf8("tbScannedFamilyPhoto"))
        self.gridLayout_3.addWidget(self.tbScannedFamilyPhoto, 3, 3, 1, 1)
        self.btnScannedFamilyPhoto = QtGui.QPushButton(self.groupBox_4)
        self.btnScannedFamilyPhoto.setObjectName(_fromUtf8("btnScannedFamilyPhoto"))
        self.gridLayout_3.addWidget(self.btnScannedFamilyPhoto, 3, 4, 1, 1)
        self.cbScannedSignature = QtGui.QCheckBox(self.groupBox_4)
        self.cbScannedSignature.setObjectName(_fromUtf8("cbScannedSignature"))
        self.gridLayout_3.addWidget(self.cbScannedSignature, 4, 2, 1, 1)
        self.tbScannedSignature = QtGui.QToolButton(self.groupBox_4)
        self.tbScannedSignature.setObjectName(_fromUtf8("tbScannedSignature"))
        self.gridLayout_3.addWidget(self.tbScannedSignature, 4, 3, 1, 1)
        self.btnScannedSignature = QtGui.QPushButton(self.groupBox_4)
        self.btnScannedSignature.setObjectName(_fromUtf8("btnScannedSignature"))
        self.gridLayout_3.addWidget(self.btnScannedSignature, 4, 4, 1, 1)
        self.btnUploadFile = QtGui.QPushButton(self.groupBox_4)
        self.btnUploadFile.setMinimumSize(QtCore.QSize(0, 25))
        self.btnUploadFile.setObjectName(_fromUtf8("btnUploadFile"))
        self.gridLayout_3.addWidget(self.btnUploadFile, 1, 4, 1, 1)
        self.edtUploadFile = QtGui.QLineEdit(self.groupBox_4)
        self.edtUploadFile.setObjectName(_fromUtf8("edtUploadFile"))
        self.gridLayout_3.addWidget(self.edtUploadFile, 1, 1, 1, 3)
        self.verticalLayout_5.addLayout(self.gridLayout_3)
        self.verticalLayout_3.addWidget(self.groupBox_4)
        spacerItem5 = QtGui.QSpacerItem(20, 227, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem5)
        self.twDocument.addTab(self.tbUpload, _fromUtf8(""))
        self.verticalLayout_4.addWidget(self.twDocument)
        self.gbProgress = QtGui.QGroupBox(self.centralwidget)
        self.gbProgress.setObjectName(_fromUtf8("gbProgress"))
        self.gridLayout_7 = QtGui.QGridLayout(self.gbProgress)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.edtProgress = QtGui.QTextEdit(self.gbProgress)
        self.edtProgress.setReadOnly(True)
        self.edtProgress.setObjectName(_fromUtf8("edtProgress"))
        self.gridLayout_7.addWidget(self.edtProgress, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.gbProgress)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem6)
        self.btnClose = QtGui.QPushButton(self.centralwidget)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.horizontalLayout_3.addWidget(self.btnClose)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        DocumentDownloader.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(DocumentDownloader)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        DocumentDownloader.setStatusBar(self.statusbar)

        self.retranslateUi(DocumentDownloader)
        self.twDocument.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(DocumentDownloader)

    def retranslateUi(self, DocumentDownloader):
        DocumentDownloader.setWindowTitle(_translate("DocumentDownloader", "Download and Upload Documents", None))
        self.groupBox_2.setTitle(_translate("DocumentDownloader", "Document Type:", None))
        self.rbKoboMedia.setText(_translate("DocumentDownloader", "Claims File Documents", None))
        self.rbSupportDoc.setText(_translate("DocumentDownloader", "Supporting Documents", None))
        self.groupBox.setTitle(_translate("DocumentDownloader", "Source:", None))
        self.label.setText(_translate("DocumentDownloader", "Dataset", None))
        self.btnBrowseSource.setText(_translate("DocumentDownloader", "Browse", None))
        self.groupBox_7.setTitle(_translate("DocumentDownloader", "Kobo Settings", None))
        self.label_4.setText(_translate("DocumentDownloader", "Media URL:", None))
        self.label_5.setText(_translate("DocumentDownloader", "Kobo Username:", None))
        self.label_6.setText(_translate("DocumentDownloader", "Kobo Password:", None))
        self.groupBox_8.setTitle(_translate("DocumentDownloader", "Local Document Folders:", None))
        self.label_7.setText(_translate("DocumentDownloader", "Person Signature:", None))
        self.cbPersonSignature.setText(_translate("DocumentDownloader", "Download", None))
        self.tbPersonSignature.setText(_translate("DocumentDownloader", "...", None))
        self.btnPersonSignature.setText(_translate("DocumentDownloader", "Browse ...", None))
        self.label_8.setText(_translate("DocumentDownloader", "H/Hold Signatures:", None))
        self.cbHHoldSignature.setText(_translate("DocumentDownloader", "Download", None))
        self.tbHHoldSignature.setText(_translate("DocumentDownloader", "...", None))
        self.btnHHoldSignatureFolder.setText(_translate("DocumentDownloader", "Browse ...", None))
        self.label_9.setText(_translate("DocumentDownloader", "H/Hold Finger Prints:", None))
        self.cbFingerPrint.setText(_translate("DocumentDownloader", "Download", None))
        self.tbFingerPrint.setText(_translate("DocumentDownloader", "...", None))
        self.btnFingerPrint.setText(_translate("DocumentDownloader", "Browse ...", None))
        self.label_11.setText(_translate("DocumentDownloader", "H/Hold Photo:", None))
        self.cbHHoldPhoto.setText(_translate("DocumentDownloader", "Download", None))
        self.tbHHoldPhoto.setText(_translate("DocumentDownloader", "...", None))
        self.btnHHoldPhotoFolder.setText(_translate("DocumentDownloader", "Browse ...", None))
        self.label_12.setText(_translate("DocumentDownloader", "Family Photo:", None))
        self.cbFamilyPhoto.setText(_translate("DocumentDownloader", "Download", None))
        self.tbFamilyPhoto.setText(_translate("DocumentDownloader", "...", None))
        self.btnFamilyPhotoFolder.setText(_translate("DocumentDownloader", "Browse ...", None))
        self.btnDownload.setText(_translate("DocumentDownloader", "Download", None))
        self.twDocument.setTabText(self.twDocument.indexOf(self.tbDownload), _translate("DocumentDownloader", "Download", None))
        self.btnUpload.setText(_translate("DocumentDownloader", "Upload", None))
        self.groupBox_5.setTitle(_translate("DocumentDownloader", "Document Type:", None))
        self.rbScannedDoc.setText(_translate("DocumentDownloader", "Scanned Supporting Documents", None))
        self.rbCSV.setText(_translate("DocumentDownloader", "File Names From CSV", None))
        self.groupBox_4.setTitle(_translate("DocumentDownloader", "Local Documents Folder:", None))
        self.tbScannedDoc.setText(_translate("DocumentDownloader", "...", None))
        self.label_2.setText(_translate("DocumentDownloader", "Certificate:", None))
        self.cbScannedDoc.setText(_translate("DocumentDownloader", "Upload", None))
        self.btnScannedDoc.setText(_translate("DocumentDownloader", "Browse ...", None))
        self.label_3.setText(_translate("DocumentDownloader", "House Map:", None))
        self.label_10.setText(_translate("DocumentDownloader", "House Picture:", None))
        self.label_13.setText(_translate("DocumentDownloader", "ID Document:", None))
        self.cbScannedHseMap.setText(_translate("DocumentDownloader", "Upload", None))
        self.cbScannedHsePic.setText(_translate("DocumentDownloader", "Upload", None))
        self.cbScannedIdDoc.setText(_translate("DocumentDownloader", "Upload", None))
        self.tbScannedHseMap.setText(_translate("DocumentDownloader", "...", None))
        self.tbScannedHsePic.setText(_translate("DocumentDownloader", "...", None))
        self.tbScannedIdDoc.setText(_translate("DocumentDownloader", "...", None))
        self.btnScannedHseMap.setText(_translate("DocumentDownloader", "Browse ...", None))
        self.btnScannedHsePic.setText(_translate("DocumentDownloader", "Browse ...", None))
        self.btnScannedIdDoc.setText(_translate("DocumentDownloader", "Browse ...", None))
        self.label_16.setText(_translate("DocumentDownloader", "Filename (CSV) :", None))
        self.label_14.setText(_translate("DocumentDownloader", "Family Photo:", None))
        self.cbScannedFamilyPhoto.setText(_translate("DocumentDownloader", "Upload", None))
        self.label_15.setText(_translate("DocumentDownloader", "Signature:", None))
        self.tbScannedFamilyPhoto.setText(_translate("DocumentDownloader", "...", None))
        self.btnScannedFamilyPhoto.setText(_translate("DocumentDownloader", "Browse ...", None))
        self.cbScannedSignature.setText(_translate("DocumentDownloader", "Upload", None))
        self.tbScannedSignature.setText(_translate("DocumentDownloader", "...", None))
        self.btnScannedSignature.setText(_translate("DocumentDownloader", "Browse ...", None))
        self.btnUploadFile.setText(_translate("DocumentDownloader", "Browse ...", None))
        self.twDocument.setTabText(self.twDocument.indexOf(self.tbUpload), _translate("DocumentDownloader", "Upload", None))
        self.gbProgress.setTitle(_translate("DocumentDownloader", "Download progress:", None))
        self.btnClose.setText(_translate("DocumentDownloader", "Close", None))

