# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_document_downloader.ui'
#
# Created: Thu Apr 16 18:20:11 2020
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_DocumentDownloader(object):
    def setupUi(self, DocumentDownloader):
        DocumentDownloader.setObjectName(_fromUtf8("DocumentDownloader"))
        DocumentDownloader.setWindowModality(QtCore.Qt.ApplicationModal)
        DocumentDownloader.resize(689, 543)
        self.verticalLayout = QtGui.QVBoxLayout(DocumentDownloader)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(DocumentDownloader)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.txtDataSource = QtGui.QLineEdit(self.groupBox)
        self.txtDataSource.setMaxLength(200)
        self.txtDataSource.setObjectName(_fromUtf8("txtDataSource"))
        self.horizontalLayout_2.addWidget(self.txtDataSource)
        self.btnBrowseSource = QtGui.QPushButton(self.groupBox)
        self.btnBrowseSource.setObjectName(_fromUtf8("btnBrowseSource"))
        self.horizontalLayout_2.addWidget(self.btnBrowseSource)
        self.btnHide = QtGui.QPushButton(self.groupBox)
        self.btnHide.setObjectName(_fromUtf8("btnHide"))
        self.horizontalLayout_2.addWidget(self.btnHide)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(DocumentDownloader)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rbKoboMedia = QtGui.QRadioButton(self.groupBox_2)
        self.rbKoboMedia.setObjectName(_fromUtf8("rbKoboMedia"))
        self.horizontalLayout.addWidget(self.rbKoboMedia)
        self.rbSupportDoc = QtGui.QRadioButton(self.groupBox_2)
        self.rbSupportDoc.setObjectName(_fromUtf8("rbSupportDoc"))
        self.horizontalLayout.addWidget(self.rbSupportDoc)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_7 = QtGui.QGroupBox(DocumentDownloader)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_4 = QtGui.QLabel(self.groupBox_7)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.groupBox_7)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 1, 0, 1, 1)
        self.edtKoboUsername = QtGui.QLineEdit(self.groupBox_7)
        self.edtKoboUsername.setReadOnly(False)
        self.edtKoboUsername.setObjectName(_fromUtf8("edtKoboUsername"))
        self.gridLayout_4.addWidget(self.edtKoboUsername, 1, 1, 1, 1)
        self.edtKoboPassword = QtGui.QLineEdit(self.groupBox_7)
        self.edtKoboPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.edtKoboPassword.setObjectName(_fromUtf8("edtKoboPassword"))
        self.gridLayout_4.addWidget(self.edtKoboPassword, 2, 1, 1, 1)
        self.edtMediaUrl = QtGui.QLineEdit(self.groupBox_7)
        self.edtMediaUrl.setReadOnly(False)
        self.edtMediaUrl.setObjectName(_fromUtf8("edtMediaUrl"))
        self.gridLayout_4.addWidget(self.edtMediaUrl, 0, 1, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_7)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(DocumentDownloader)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_12 = QtGui.QLabel(self.groupBox_8)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_6.addWidget(self.label_12, 4, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.groupBox_8)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_6.addWidget(self.label_8, 1, 0, 1, 1)
        self.edtSignFolder = QtGui.QLineEdit(self.groupBox_8)
        self.edtSignFolder.setObjectName(_fromUtf8("edtSignFolder"))
        self.gridLayout_6.addWidget(self.edtSignFolder, 1, 1, 1, 1)
        self.edtFamilyFolder = QtGui.QLineEdit(self.groupBox_8)
        self.edtFamilyFolder.setObjectName(_fromUtf8("edtFamilyFolder"))
        self.gridLayout_6.addWidget(self.edtFamilyFolder, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox_8)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_6.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.groupBox_8)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_6.addWidget(self.label_9, 2, 0, 1, 1)
        self.tbSignFolder = QtGui.QToolButton(self.groupBox_8)
        self.tbSignFolder.setObjectName(_fromUtf8("tbSignFolder"))
        self.gridLayout_6.addWidget(self.tbSignFolder, 1, 3, 1, 1)
        self.tbHouseFolder = QtGui.QToolButton(self.groupBox_8)
        self.tbHouseFolder.setObjectName(_fromUtf8("tbHouseFolder"))
        self.gridLayout_6.addWidget(self.tbHouseFolder, 2, 3, 1, 1)
        self.edtHouseFolder = QtGui.QLineEdit(self.groupBox_8)
        self.edtHouseFolder.setObjectName(_fromUtf8("edtHouseFolder"))
        self.gridLayout_6.addWidget(self.edtHouseFolder, 2, 1, 1, 1)
        self.tbFamilyFolder = QtGui.QToolButton(self.groupBox_8)
        self.tbFamilyFolder.setObjectName(_fromUtf8("tbFamilyFolder"))
        self.gridLayout_6.addWidget(self.tbFamilyFolder, 0, 3, 1, 1)
        self.btnFamilyBrowse = QtGui.QPushButton(self.groupBox_8)
        self.btnFamilyBrowse.setObjectName(_fromUtf8("btnFamilyBrowse"))
        self.gridLayout_6.addWidget(self.btnFamilyBrowse, 0, 4, 1, 1)
        self.btnSignFolder = QtGui.QPushButton(self.groupBox_8)
        self.btnSignFolder.setObjectName(_fromUtf8("btnSignFolder"))
        self.gridLayout_6.addWidget(self.btnSignFolder, 1, 4, 1, 1)
        self.btnHouseFolder = QtGui.QPushButton(self.groupBox_8)
        self.btnHouseFolder.setObjectName(_fromUtf8("btnHouseFolder"))
        self.gridLayout_6.addWidget(self.btnHouseFolder, 2, 4, 1, 1)
        self.cbFamilyPhoto = QtGui.QCheckBox(self.groupBox_8)
        self.cbFamilyPhoto.setCheckable(True)
        self.cbFamilyPhoto.setObjectName(_fromUtf8("cbFamilyPhoto"))
        self.gridLayout_6.addWidget(self.cbFamilyPhoto, 0, 2, 1, 1)
        self.cbSign = QtGui.QCheckBox(self.groupBox_8)
        self.cbSign.setObjectName(_fromUtf8("cbSign"))
        self.gridLayout_6.addWidget(self.cbSign, 1, 2, 1, 1)
        self.cbHousePhoto = QtGui.QCheckBox(self.groupBox_8)
        self.cbHousePhoto.setObjectName(_fromUtf8("cbHousePhoto"))
        self.gridLayout_6.addWidget(self.cbHousePhoto, 2, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.groupBox_8)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_6.addWidget(self.label_11, 3, 0, 1, 1)
        self.edtHousePic = QtGui.QLineEdit(self.groupBox_8)
        self.edtHousePic.setObjectName(_fromUtf8("edtHousePic"))
        self.gridLayout_6.addWidget(self.edtHousePic, 3, 1, 1, 1)
        self.cbHousePic = QtGui.QCheckBox(self.groupBox_8)
        self.cbHousePic.setObjectName(_fromUtf8("cbHousePic"))
        self.gridLayout_6.addWidget(self.cbHousePic, 3, 2, 1, 1)
        self.tbHousePic = QtGui.QToolButton(self.groupBox_8)
        self.tbHousePic.setObjectName(_fromUtf8("tbHousePic"))
        self.gridLayout_6.addWidget(self.tbHousePic, 3, 3, 1, 1)
        self.btnHousePic = QtGui.QPushButton(self.groupBox_8)
        self.btnHousePic.setObjectName(_fromUtf8("btnHousePic"))
        self.gridLayout_6.addWidget(self.btnHousePic, 3, 4, 1, 1)
        self.edtIdPic = QtGui.QLineEdit(self.groupBox_8)
        self.edtIdPic.setObjectName(_fromUtf8("edtIdPic"))
        self.gridLayout_6.addWidget(self.edtIdPic, 4, 1, 1, 1)
        self.cbIdPic = QtGui.QCheckBox(self.groupBox_8)
        self.cbIdPic.setObjectName(_fromUtf8("cbIdPic"))
        self.gridLayout_6.addWidget(self.cbIdPic, 4, 2, 1, 1)
        self.tbIdPic = QtGui.QToolButton(self.groupBox_8)
        self.tbIdPic.setObjectName(_fromUtf8("tbIdPic"))
        self.gridLayout_6.addWidget(self.tbIdPic, 4, 3, 1, 1)
        self.btnIdPic = QtGui.QPushButton(self.groupBox_8)
        self.btnIdPic.setObjectName(_fromUtf8("btnIdPic"))
        self.gridLayout_6.addWidget(self.btnIdPic, 4, 4, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_8)
        self.groupBox_9 = QtGui.QGroupBox(DocumentDownloader)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.lblCurrFile = QtGui.QLabel(self.groupBox_9)
        self.lblCurrFile.setObjectName(_fromUtf8("lblCurrFile"))
        self.gridLayout_7.addWidget(self.lblCurrFile, 3, 2, 1, 1)
        self.label_10 = QtGui.QLabel(self.groupBox_9)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_7.addWidget(self.label_10, 3, 1, 1, 1)
        self.labelrecord = QtGui.QLabel(self.groupBox_9)
        self.labelrecord.setObjectName(_fromUtf8("labelrecord"))
        self.gridLayout_7.addWidget(self.labelrecord, 0, 1, 1, 1)
        self.lblCurrRecord = QtGui.QLabel(self.groupBox_9)
        self.lblCurrRecord.setObjectName(_fromUtf8("lblCurrRecord"))
        self.gridLayout_7.addWidget(self.lblCurrRecord, 0, 2, 1, 1)
        self.btnDownload = QtGui.QPushButton(self.groupBox_9)
        self.btnDownload.setObjectName(_fromUtf8("btnDownload"))
        self.gridLayout_7.addWidget(self.btnDownload, 0, 3, 1, 1)
        self.lblMsg = QtGui.QLabel(self.groupBox_9)
        self.lblMsg.setObjectName(_fromUtf8("lblMsg"))
        self.gridLayout_7.addWidget(self.lblMsg, 3, 3, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_9)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(DocumentDownloader)
        QtCore.QMetaObject.connectSlotsByName(DocumentDownloader)

    def retranslateUi(self, DocumentDownloader):
        DocumentDownloader.setWindowTitle(_translate("DocumentDownloader", "Dialog", None))
        self.groupBox.setTitle(_translate("DocumentDownloader", "Source:", None))
        self.label.setText(_translate("DocumentDownloader", "Dataset", None))
        self.btnBrowseSource.setText(_translate("DocumentDownloader", "Browse", None))
        self.btnHide.setText(_translate("DocumentDownloader", "Hide", None))
        self.groupBox_2.setTitle(_translate("DocumentDownloader", "Destination Repository Type:", None))
        self.rbKoboMedia.setText(_translate("DocumentDownloader", "Kobo Images", None))
        self.rbSupportDoc.setText(_translate("DocumentDownloader", "Supporting Documents", None))
        self.groupBox_7.setTitle(_translate("DocumentDownloader", "Kobo Settings", None))
        self.label_4.setText(_translate("DocumentDownloader", "Media URL:", None))
        self.label_5.setText(_translate("DocumentDownloader", "Kobo Username:", None))
        self.label_6.setText(_translate("DocumentDownloader", "Kobo Password:", None))
        self.groupBox_8.setTitle(_translate("DocumentDownloader", "Local Media Folders:", None))
        self.label_12.setText(_translate("DocumentDownloader", "ID Picture", None))
        self.label_8.setText(_translate("DocumentDownloader", "Signatures:", None))
        self.label_7.setText(_translate("DocumentDownloader", "Family Photos:", None))
        self.label_9.setText(_translate("DocumentDownloader", "House Map:", None))
        self.tbSignFolder.setText(_translate("DocumentDownloader", "...", None))
        self.tbHouseFolder.setText(_translate("DocumentDownloader", "...", None))
        self.tbFamilyFolder.setText(_translate("DocumentDownloader", "...", None))
        self.btnFamilyBrowse.setText(_translate("DocumentDownloader", "Browse ...", None))
        self.btnSignFolder.setText(_translate("DocumentDownloader", "Browse ...", None))
        self.btnHouseFolder.setText(_translate("DocumentDownloader", "Browse ...", None))
        self.cbFamilyPhoto.setText(_translate("DocumentDownloader", "Download", None))
        self.cbSign.setText(_translate("DocumentDownloader", "Download", None))
        self.cbHousePhoto.setText(_translate("DocumentDownloader", "Download", None))
        self.label_11.setText(_translate("DocumentDownloader", "House Picture", None))
        self.cbHousePic.setText(_translate("DocumentDownloader", "Download", None))
        self.tbHousePic.setText(_translate("DocumentDownloader", "...", None))
        self.btnHousePic.setText(_translate("DocumentDownloader", "Browse ...", None))
        self.cbIdPic.setText(_translate("DocumentDownloader", "Download", None))
        self.tbIdPic.setText(_translate("DocumentDownloader", "...", None))
        self.btnIdPic.setText(_translate("DocumentDownloader", "Browse ...", None))
        self.groupBox_9.setTitle(_translate("DocumentDownloader", "Download:", None))
        self.lblCurrFile.setText(_translate("DocumentDownloader", "0", None))
        self.label_10.setText(_translate("DocumentDownloader", "Current File:", None))
        self.labelrecord.setText(_translate("DocumentDownloader", "Current Record:", None))
        self.lblCurrRecord.setText(_translate("DocumentDownloader", "0", None))
        self.btnDownload.setText(_translate("DocumentDownloader", "Download", None))
        self.lblMsg.setText(_translate("DocumentDownloader", "Ready.", None))

