# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_export_data.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmExportWizard(object):
    def setupUi(self, frmExportWizard):
        frmExportWizard.setObjectName(_fromUtf8("frmExportWizard"))
        frmExportWizard.resize(606, 498)
        frmExportWizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        self.pgDestination = QtGui.QWizardPage()
        self.pgDestination.setObjectName(_fromUtf8("pgDestination"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pgDestination)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.pgDestination)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.rbShp = QtGui.QRadioButton(self.groupBox_3)
        self.rbShp.setChecked(True)
        self.rbShp.setObjectName(_fromUtf8("rbShp"))
        self.verticalLayout.addWidget(self.rbShp)
        self.rbCSV = QtGui.QRadioButton(self.groupBox_3)
        self.rbCSV.setObjectName(_fromUtf8("rbCSV"))
        self.verticalLayout.addWidget(self.rbCSV)
        self.rbMapInfo = QtGui.QRadioButton(self.groupBox_3)
        self.rbMapInfo.setObjectName(_fromUtf8("rbMapInfo"))
        self.verticalLayout.addWidget(self.rbMapInfo)
        self.rbGPX = QtGui.QRadioButton(self.groupBox_3)
        self.rbGPX.setObjectName(_fromUtf8("rbGPX"))
        self.verticalLayout.addWidget(self.rbGPX)
        self.rbDXF = QtGui.QRadioButton(self.groupBox_3)
        self.rbDXF.setObjectName(_fromUtf8("rbDXF"))
        self.verticalLayout.addWidget(self.rbDXF)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.pgDestination)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.txtExportPath = QtGui.QLineEdit(self.groupBox_4)
        self.txtExportPath.setMaxLength(200)
        self.txtExportPath.setObjectName(_fromUtf8("txtExportPath"))
        self.gridLayout.addWidget(self.txtExportPath, 0, 0, 1, 1)
        self.btnDestFile = QtGui.QPushButton(self.groupBox_4)
        self.btnDestFile.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnDestFile.setObjectName(_fromUtf8("btnDestFile"))
        self.gridLayout.addWidget(self.btnDestFile, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        frmExportWizard.addPage(self.pgDestination)
        self.pgSrcTab = QtGui.QWizardPage()
        self.pgSrcTab.setObjectName(_fromUtf8("pgSrcTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.pgSrcTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.pgSrcTab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lstSrcTab = QtGui.QListWidget(self.groupBox_2)
        self.lstSrcTab.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lstSrcTab.setObjectName(_fromUtf8("lstSrcTab"))
        self.gridLayout_2.addWidget(self.lstSrcTab, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 2, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.pgSrcTab)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.select_all = QtGui.QToolButton(self.groupBox_7)
        self.select_all.setObjectName(_fromUtf8("select_all"))
        self.gridLayout_6.addWidget(self.select_all, 0, 0, 1, 1)
        self.select_none = QtGui.QToolButton(self.groupBox_7)
        self.select_none.setObjectName(_fromUtf8("select_none"))
        self.gridLayout_6.addWidget(self.select_none, 0, 1, 1, 1)
        self.lstSrcCols_2 = QtGui.QListWidget(self.groupBox_7)
        self.lstSrcCols_2.setObjectName(_fromUtf8("lstSrcCols_2"))
        self.gridLayout_6.addWidget(self.lstSrcCols_2, 1, 0, 1, 3)
        self.gridLayout_3.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.pgSrcTab)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.cboSpatialCols_2 = QtGui.QComboBox(self.groupBox_8)
        self.cboSpatialCols_2.setObjectName(_fromUtf8("cboSpatialCols_2"))
        self.gridLayout_7.addWidget(self.cboSpatialCols_2, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_8, 1, 1, 1, 1)
        frmExportWizard.addPage(self.pgSrcTab)
        self.pgFilter = QtGui.QWizardPage()
        self.pgFilter.setObjectName(_fromUtf8("pgFilter"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.pgFilter)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.gpQBuilder = QtGui.QGroupBox(self.pgFilter)
        self.gpQBuilder.setCheckable(True)
        self.gpQBuilder.setChecked(False)
        self.gpQBuilder.setObjectName(_fromUtf8("gpQBuilder"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.gpQBuilder)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_5 = QtGui.QGroupBox(self.gpQBuilder)
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.btnUniqueVals = QtGui.QPushButton(self.groupBox_5)
        self.btnUniqueVals.setObjectName(_fromUtf8("btnUniqueVals"))
        self.gridLayout_4.addWidget(self.btnUniqueVals, 2, 1, 1, 1)
        self.lstQueryCols = QtGui.QListWidget(self.groupBox_5)
        self.lstQueryCols.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lstQueryCols.setObjectName(_fromUtf8("lstQueryCols"))
        self.gridLayout_4.addWidget(self.lstQueryCols, 1, 0, 2, 1)
        self.lstUniqueVals = QtGui.QListWidget(self.groupBox_5)
        self.lstUniqueVals.setObjectName(_fromUtf8("lstUniqueVals"))
        self.gridLayout_4.addWidget(self.lstUniqueVals, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 0, 1, 1, 1)
        self.label = QtGui.QLabel(self.groupBox_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.groupBox_6 = QtGui.QGroupBox(self.gpQBuilder)
        self.groupBox_6.setMaximumSize(QtCore.QSize(221, 16777215))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.btnOpEq = QtGui.QPushButton(self.groupBox_6)
        self.btnOpEq.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnOpEq.setObjectName(_fromUtf8("btnOpEq"))
        self.gridLayout_5.addWidget(self.btnOpEq, 0, 0, 1, 1)
        self.btnOpNotEq = QtGui.QPushButton(self.groupBox_6)
        self.btnOpNotEq.setObjectName(_fromUtf8("btnOpNotEq"))
        self.gridLayout_5.addWidget(self.btnOpNotEq, 0, 1, 1, 1)
        self.btnOpLike = QtGui.QPushButton(self.groupBox_6)
        self.btnOpLike.setObjectName(_fromUtf8("btnOpLike"))
        self.gridLayout_5.addWidget(self.btnOpLike, 0, 2, 1, 1)
        self.btnOpGreater = QtGui.QPushButton(self.groupBox_6)
        self.btnOpGreater.setObjectName(_fromUtf8("btnOpGreater"))
        self.gridLayout_5.addWidget(self.btnOpGreater, 1, 0, 1, 1)
        self.btnOpGreaterEq = QtGui.QPushButton(self.groupBox_6)
        self.btnOpGreaterEq.setObjectName(_fromUtf8("btnOpGreaterEq"))
        self.gridLayout_5.addWidget(self.btnOpGreaterEq, 1, 1, 1, 1)
        self.btnOpAnd = QtGui.QPushButton(self.groupBox_6)
        self.btnOpAnd.setObjectName(_fromUtf8("btnOpAnd"))
        self.gridLayout_5.addWidget(self.btnOpAnd, 1, 2, 1, 1)
        self.btnOpLess = QtGui.QPushButton(self.groupBox_6)
        self.btnOpLess.setObjectName(_fromUtf8("btnOpLess"))
        self.gridLayout_5.addWidget(self.btnOpLess, 2, 0, 1, 1)
        self.btnOpLessEq = QtGui.QPushButton(self.groupBox_6)
        self.btnOpLessEq.setObjectName(_fromUtf8("btnOpLessEq"))
        self.gridLayout_5.addWidget(self.btnOpLessEq, 2, 1, 1, 1)
        self.btnOpOr = QtGui.QPushButton(self.groupBox_6)
        self.btnOpOr.setObjectName(_fromUtf8("btnOpOr"))
        self.gridLayout_5.addWidget(self.btnOpOr, 2, 2, 1, 1)
        self.horizontalLayout_2.addWidget(self.groupBox_6)
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.txtWhereQuery = QtGui.QTextEdit(self.gpQBuilder)
        self.txtWhereQuery.setObjectName(_fromUtf8("txtWhereQuery"))
        self.verticalLayout_3.addWidget(self.txtWhereQuery)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.btnClearQuery = QtGui.QPushButton(self.gpQBuilder)
        self.btnClearQuery.setObjectName(_fromUtf8("btnClearQuery"))
        self.horizontalLayout.addWidget(self.btnClearQuery)
        self.btnQueryVerify = QtGui.QPushButton(self.gpQBuilder)
        self.btnQueryVerify.setObjectName(_fromUtf8("btnQueryVerify"))
        self.horizontalLayout.addWidget(self.btnQueryVerify)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_2)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        self.groupBox_5.raise_()
        self.groupBox_6.raise_()
        self.txtWhereQuery.raise_()
        self.btnClearQuery.raise_()
        self.btnQueryVerify.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.verticalLayout_6.addWidget(self.gpQBuilder)
        frmExportWizard.addPage(self.pgFilter)

        self.retranslateUi(frmExportWizard)
        QtCore.QMetaObject.connectSlotsByName(frmExportWizard)

    def retranslateUi(self, frmExportWizard):
        frmExportWizard.setWindowTitle(_translate("frmExportWizard", "Export SIF Data...", None))
        self.pgDestination.setTitle(_translate("frmExportWizard", "Destination Options", None))
        self.pgDestination.setSubTitle(_translate("frmExportWizard", "Select destination file name and format.", None))
        self.groupBox_3.setTitle(_translate("frmExportWizard", "Destination Format:", None))
        self.rbShp.setText(_translate("frmExportWizard", "ESRI Shapefile", None))
        self.rbCSV.setText(_translate("frmExportWizard", "CSV", None))
        self.rbMapInfo.setText(_translate("frmExportWizard", "MapInfo File", None))
        self.rbGPX.setText(_translate("frmExportWizard", "GPX", None))
        self.rbDXF.setText(_translate("frmExportWizard", "DXF", None))
        self.groupBox_4.setTitle(_translate("frmExportWizard", "Destination File:", None))
        self.btnDestFile.setText(_translate("frmExportWizard", "...", None))
        self.pgSrcTab.setTitle(_translate("frmExportWizard", "Export Table", None))
        self.pgSrcTab.setSubTitle(_translate("frmExportWizard", "Select the table or view from the STDM database whose contents are to be exported.", None))
        self.groupBox_2.setTitle(_translate("frmExportWizard", "Source Table:", None))
        self.groupBox_7.setTitle(_translate("frmExportWizard", "Textual Columns:", None))
        self.select_all.setText(_translate("frmExportWizard", "Select All", None))
        self.select_none.setText(_translate("frmExportWizard", "Select None", None))
        self.groupBox_8.setTitle(_translate("frmExportWizard", "Spatial Columns:", None))
        self.pgFilter.setTitle(_translate("frmExportWizard", "Filter Data", None))
        self.pgFilter.setSubTitle(_translate("frmExportWizard", "Specify a custom query to filter out the resulting dataset.", None))
        self.gpQBuilder.setTitle(_translate("frmExportWizard", "Query Builder:", None))
        self.btnUniqueVals.setText(_translate("frmExportWizard", "Get Unique Values", None))
        self.label_2.setText(_translate("frmExportWizard", "Unique Values:", None))
        self.label.setText(_translate("frmExportWizard", "Columns:", None))
        self.groupBox_6.setTitle(_translate("frmExportWizard", "Operators:", None))
        self.btnOpEq.setText(_translate("frmExportWizard", "=", None))
        self.btnOpNotEq.setText(_translate("frmExportWizard", "<>", None))
        self.btnOpLike.setText(_translate("frmExportWizard", "LIKE", None))
        self.btnOpGreater.setText(_translate("frmExportWizard", ">", None))
        self.btnOpGreaterEq.setText(_translate("frmExportWizard", ">=", None))
        self.btnOpAnd.setText(_translate("frmExportWizard", "AND", None))
        self.btnOpLess.setText(_translate("frmExportWizard", "<", None))
        self.btnOpLessEq.setText(_translate("frmExportWizard", "<=", None))
        self.btnOpOr.setText(_translate("frmExportWizard", "OR", None))
        self.btnClearQuery.setText(_translate("frmExportWizard", "Clear", None))
        self.btnQueryVerify.setText(_translate("frmExportWizard", "Verify", None))

