# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_dataExport.ui'
#
# Created: Tue Dec 04 23:11:28 2012
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_frmExportWizard(object):
    def setupUi(self, frmExportWizard):
        frmExportWizard.setObjectName(_fromUtf8("frmExportWizard"))
        frmExportWizard.resize(512, 444)
        frmExportWizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        self.pgDestination = QtGui.QWizardPage()
        self.pgDestination.setObjectName(_fromUtf8("pgDestination"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.pgDestination)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.pgDestination)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.rbShp = QtGui.QRadioButton(self.groupBox_3)
        self.rbShp.setChecked(True)
        self.rbShp.setObjectName(_fromUtf8("rbShp"))
        self.verticalLayout.addWidget(self.rbShp)
        self.rbCSV = QtGui.QRadioButton(self.groupBox_3)
        self.rbCSV.setObjectName(_fromUtf8("rbCSV"))
        self.verticalLayout.addWidget(self.rbCSV)
        self.rbMapInfo = QtGui.QRadioButton(self.groupBox_3)
        self.rbMapInfo.setObjectName(_fromUtf8("rbMapInfo"))
        self.verticalLayout.addWidget(self.rbMapInfo)
        self.rbGPX = QtGui.QRadioButton(self.groupBox_3)
        self.rbGPX.setObjectName(_fromUtf8("rbGPX"))
        self.verticalLayout.addWidget(self.rbGPX)
        self.rbDXF = QtGui.QRadioButton(self.groupBox_3)
        self.rbDXF.setObjectName(_fromUtf8("rbDXF"))
        self.verticalLayout.addWidget(self.rbDXF)
        self.verticalLayout_2.addWidget(self.groupBox_3)
        self.groupBox_4 = QtGui.QGroupBox(self.pgDestination)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.txtExportPath = QtGui.QLineEdit(self.groupBox_4)
        self.txtExportPath.setMaxLength(200)
        self.txtExportPath.setObjectName(_fromUtf8("txtExportPath"))
        self.gridLayout.addWidget(self.txtExportPath, 0, 0, 1, 1)
        self.btnDestFile = QtGui.QPushButton(self.groupBox_4)
        self.btnDestFile.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnDestFile.setObjectName(_fromUtf8("btnDestFile"))
        self.gridLayout.addWidget(self.btnDestFile, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        frmExportWizard.addPage(self.pgDestination)
        self.pgSrcTab = QtGui.QWizardPage()
        self.pgSrcTab.setObjectName(_fromUtf8("pgSrcTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.pgSrcTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.pgSrcTab)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.lstSrcTab = QtGui.QListWidget(self.groupBox_2)
        self.lstSrcTab.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lstSrcTab.setObjectName(_fromUtf8("lstSrcTab"))
        self.gridLayout_2.addWidget(self.lstSrcTab, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 2, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.pgSrcTab)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lstSrcCols_2 = QtGui.QListWidget(self.groupBox_7)
        self.lstSrcCols_2.setObjectName(_fromUtf8("lstSrcCols_2"))
        self.gridLayout_6.addWidget(self.lstSrcCols_2, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_7, 0, 1, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.pgSrcTab)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.cboSpatialCols_2 = QtGui.QComboBox(self.groupBox_8)
        self.cboSpatialCols_2.setObjectName(_fromUtf8("cboSpatialCols_2"))
        self.gridLayout_7.addWidget(self.cboSpatialCols_2, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_8, 1, 1, 1, 1)
        frmExportWizard.addPage(self.pgSrcTab)
        self.pgFilter = QtGui.QWizardPage()
        self.pgFilter.setObjectName(_fromUtf8("pgFilter"))
        self.gpQBuilder = QtGui.QGroupBox(self.pgFilter)
        self.gpQBuilder.setGeometry(QtCore.QRect(10, 10, 471, 311))
        self.gpQBuilder.setCheckable(True)
        self.gpQBuilder.setChecked(False)
        self.gpQBuilder.setObjectName(_fromUtf8("gpQBuilder"))
        self.groupBox_5 = QtGui.QGroupBox(self.gpQBuilder)
        self.groupBox_5.setGeometry(QtCore.QRect(10, 23, 451, 155))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label = QtGui.QLabel(self.groupBox_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_5)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_4.addWidget(self.label_2, 0, 1, 1, 1)
        self.lstQueryCols = QtGui.QListWidget(self.groupBox_5)
        self.lstQueryCols.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lstQueryCols.setObjectName(_fromUtf8("lstQueryCols"))
        self.gridLayout_4.addWidget(self.lstQueryCols, 1, 0, 2, 1)
        self.lstUniqueVals = QtGui.QListWidget(self.groupBox_5)
        self.lstUniqueVals.setObjectName(_fromUtf8("lstUniqueVals"))
        self.gridLayout_4.addWidget(self.lstUniqueVals, 1, 1, 1, 1)
        self.btnUniqueVals = QtGui.QPushButton(self.groupBox_5)
        self.btnUniqueVals.setObjectName(_fromUtf8("btnUniqueVals"))
        self.gridLayout_4.addWidget(self.btnUniqueVals, 2, 1, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.gpQBuilder)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 184, 221, 117))
        self.groupBox_6.setMaximumSize(QtCore.QSize(221, 16777215))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.btnOpEq = QtGui.QPushButton(self.groupBox_6)
        self.btnOpEq.setMaximumSize(QtCore.QSize(100, 16777215))
        self.btnOpEq.setObjectName(_fromUtf8("btnOpEq"))
        self.gridLayout_5.addWidget(self.btnOpEq, 0, 0, 1, 1)
        self.btnOpNotEq = QtGui.QPushButton(self.groupBox_6)
        self.btnOpNotEq.setObjectName(_fromUtf8("btnOpNotEq"))
        self.gridLayout_5.addWidget(self.btnOpNotEq, 0, 1, 1, 1)
        self.btnOpLike = QtGui.QPushButton(self.groupBox_6)
        self.btnOpLike.setObjectName(_fromUtf8("btnOpLike"))
        self.gridLayout_5.addWidget(self.btnOpLike, 0, 2, 1, 1)
        self.btnOpGreater = QtGui.QPushButton(self.groupBox_6)
        self.btnOpGreater.setObjectName(_fromUtf8("btnOpGreater"))
        self.gridLayout_5.addWidget(self.btnOpGreater, 1, 0, 1, 1)
        self.btnOpGreaterEq = QtGui.QPushButton(self.groupBox_6)
        self.btnOpGreaterEq.setObjectName(_fromUtf8("btnOpGreaterEq"))
        self.gridLayout_5.addWidget(self.btnOpGreaterEq, 1, 1, 1, 1)
        self.btnOpAnd = QtGui.QPushButton(self.groupBox_6)
        self.btnOpAnd.setObjectName(_fromUtf8("btnOpAnd"))
        self.gridLayout_5.addWidget(self.btnOpAnd, 1, 2, 1, 1)
        self.btnOpLess = QtGui.QPushButton(self.groupBox_6)
        self.btnOpLess.setObjectName(_fromUtf8("btnOpLess"))
        self.gridLayout_5.addWidget(self.btnOpLess, 2, 0, 1, 1)
        self.btnOpLessEq = QtGui.QPushButton(self.groupBox_6)
        self.btnOpLessEq.setObjectName(_fromUtf8("btnOpLessEq"))
        self.gridLayout_5.addWidget(self.btnOpLessEq, 2, 1, 1, 1)
        self.btnOpOr = QtGui.QPushButton(self.groupBox_6)
        self.btnOpOr.setObjectName(_fromUtf8("btnOpOr"))
        self.gridLayout_5.addWidget(self.btnOpOr, 2, 2, 1, 1)
        self.txtWhereQuery = QtGui.QTextEdit(self.gpQBuilder)
        self.txtWhereQuery.setGeometry(QtCore.QRect(237, 184, 224, 88))
        self.txtWhereQuery.setObjectName(_fromUtf8("txtWhereQuery"))
        self.btnClearQuery = QtGui.QPushButton(self.gpQBuilder)
        self.btnClearQuery.setGeometry(QtCore.QRect(237, 278, 75, 23))
        self.btnClearQuery.setObjectName(_fromUtf8("btnClearQuery"))
        self.btnQueryVerify = QtGui.QPushButton(self.gpQBuilder)
        self.btnQueryVerify.setGeometry(QtCore.QRect(352, 278, 75, 23))
        self.btnQueryVerify.setObjectName(_fromUtf8("btnQueryVerify"))
        frmExportWizard.addPage(self.pgFilter)

        self.retranslateUi(frmExportWizard)
        QtCore.QMetaObject.connectSlotsByName(frmExportWizard)

    def retranslateUi(self, frmExportWizard):
        frmExportWizard.setWindowTitle(QtGui.QApplication.translate("frmExportWizard", "Export STDM Data...", None, QtGui.QApplication.UnicodeUTF8))
        self.pgDestination.setTitle(QtGui.QApplication.translate("frmExportWizard", "Destination Options", None, QtGui.QApplication.UnicodeUTF8))
        self.pgDestination.setSubTitle(QtGui.QApplication.translate("frmExportWizard", "Select destination file name and format.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_3.setTitle(QtGui.QApplication.translate("frmExportWizard", "Destination Format:", None, QtGui.QApplication.UnicodeUTF8))
        self.rbShp.setText(QtGui.QApplication.translate("frmExportWizard", "ESRI Shapefile", None, QtGui.QApplication.UnicodeUTF8))
        self.rbCSV.setText(QtGui.QApplication.translate("frmExportWizard", "CSV", None, QtGui.QApplication.UnicodeUTF8))
        self.rbMapInfo.setText(QtGui.QApplication.translate("frmExportWizard", "MapInfo File", None, QtGui.QApplication.UnicodeUTF8))
        self.rbGPX.setText(QtGui.QApplication.translate("frmExportWizard", "GPX", None, QtGui.QApplication.UnicodeUTF8))
        self.rbDXF.setText(QtGui.QApplication.translate("frmExportWizard", "DXF", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_4.setTitle(QtGui.QApplication.translate("frmExportWizard", "Destination File:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnDestFile.setText(QtGui.QApplication.translate("frmExportWizard", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.pgSrcTab.setTitle(QtGui.QApplication.translate("frmExportWizard", "Export Table", None, QtGui.QApplication.UnicodeUTF8))
        self.pgSrcTab.setSubTitle(QtGui.QApplication.translate("frmExportWizard", "Select the table or view from the STDM database whose contents are to be exported.", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("frmExportWizard", "Source Table:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_7.setTitle(QtGui.QApplication.translate("frmExportWizard", "Textual Columns:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_8.setTitle(QtGui.QApplication.translate("frmExportWizard", "Spatial Columns:", None, QtGui.QApplication.UnicodeUTF8))
        self.pgFilter.setTitle(QtGui.QApplication.translate("frmExportWizard", "Filter Data", None, QtGui.QApplication.UnicodeUTF8))
        self.pgFilter.setSubTitle(QtGui.QApplication.translate("frmExportWizard", "Specify a custom query to filter out the resulting dataset.", None, QtGui.QApplication.UnicodeUTF8))
        self.gpQBuilder.setTitle(QtGui.QApplication.translate("frmExportWizard", "Query Builder:", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("frmExportWizard", "Columns:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("frmExportWizard", "Unique Values:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnUniqueVals.setText(QtGui.QApplication.translate("frmExportWizard", "Get Unique Values", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_6.setTitle(QtGui.QApplication.translate("frmExportWizard", "Operators:", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpEq.setText(QtGui.QApplication.translate("frmExportWizard", "=", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpNotEq.setText(QtGui.QApplication.translate("frmExportWizard", "<>", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpLike.setText(QtGui.QApplication.translate("frmExportWizard", "LIKE", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpGreater.setText(QtGui.QApplication.translate("frmExportWizard", ">", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpGreaterEq.setText(QtGui.QApplication.translate("frmExportWizard", ">=", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpAnd.setText(QtGui.QApplication.translate("frmExportWizard", "AND", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpLess.setText(QtGui.QApplication.translate("frmExportWizard", "<", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpLessEq.setText(QtGui.QApplication.translate("frmExportWizard", "<=", None, QtGui.QApplication.UnicodeUTF8))
        self.btnOpOr.setText(QtGui.QApplication.translate("frmExportWizard", "OR", None, QtGui.QApplication.UnicodeUTF8))
        self.btnClearQuery.setText(QtGui.QApplication.translate("frmExportWizard", "Clear", None, QtGui.QApplication.UnicodeUTF8))
        self.btnQueryVerify.setText(QtGui.QApplication.translate("frmExportWizard", "Verify", None, QtGui.QApplication.UnicodeUTF8))

