# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_import_data.ui'
#
# Created: Sun Jun 08 23:06:16 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmImport(object):
    def setupUi(self, frmImport):
        frmImport.setObjectName(_fromUtf8("frmImport"))
        frmImport.resize(492, 402)
        frmImport.setWizardStyle(QtGui.QWizard.ModernStyle)
        frmImport.setOptions(QtGui.QWizard.HelpButtonOnRight)
        self.pgSource = QtGui.QWizardPage()
        self.pgSource.setObjectName(_fromUtf8("pgSource"))
        self.verticalLayout = QtGui.QVBoxLayout(self.pgSource)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox = QtGui.QGroupBox(self.pgSource)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_2.addWidget(self.label)
        self.txtDataSource = QtGui.QLineEdit(self.groupBox)
        self.txtDataSource.setMaxLength(200)
        self.txtDataSource.setObjectName(_fromUtf8("txtDataSource"))
        self.horizontalLayout_2.addWidget(self.txtDataSource)
        self.btnBrowseSource = QtGui.QPushButton(self.groupBox)
        self.btnBrowseSource.setObjectName(_fromUtf8("btnBrowseSource"))
        self.horizontalLayout_2.addWidget(self.btnBrowseSource)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.pgSource)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.rbTextType = QtGui.QRadioButton(self.groupBox_2)
        self.rbTextType.setChecked(True)
        self.rbTextType.setObjectName(_fromUtf8("rbTextType"))
        self.horizontalLayout.addWidget(self.rbTextType)
        self.rbSpType = QtGui.QRadioButton(self.groupBox_2)
        self.rbSpType.setObjectName(_fromUtf8("rbSpType"))
        self.horizontalLayout.addWidget(self.rbSpType)
        self.verticalLayout.addWidget(self.groupBox_2)
        frmImport.addPage(self.pgSource)
        self.destTable = QtGui.QWizardPage()
        self.destTable.setObjectName(_fromUtf8("destTable"))
        self.gridLayout_2 = QtGui.QGridLayout(self.destTable)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_3 = QtGui.QGroupBox(self.destTable)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.lstDestTables = QtGui.QListWidget(self.groupBox_3)
        self.lstDestTables.setObjectName(_fromUtf8("lstDestTables"))
        self.gridLayout.addWidget(self.lstDestTables, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.destTable)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.rbAppend = QtGui.QRadioButton(self.groupBox_4)
        self.rbAppend.setChecked(True)
        self.rbAppend.setObjectName(_fromUtf8("rbAppend"))
        self.gridLayout_5.addWidget(self.rbAppend, 0, 0, 1, 2)
        self.rbOverwrite = QtGui.QRadioButton(self.groupBox_4)
        self.rbOverwrite.setObjectName(_fromUtf8("rbOverwrite"))
        self.gridLayout_5.addWidget(self.rbOverwrite, 1, 0, 1, 2)
        self.geomClm = QtGui.QComboBox(self.groupBox_4)
        self.geomClm.setEnabled(False)
        self.geomClm.setMinimumSize(QtCore.QSize(100, 0))
        self.geomClm.setMaximumSize(QtCore.QSize(100, 16777215))
        self.geomClm.setObjectName(_fromUtf8("geomClm"))
        self.gridLayout_5.addWidget(self.geomClm, 3, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.groupBox_4)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_5.addWidget(self.label_2, 3, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 1, 1, 1)
        frmImport.addPage(self.destTable)
        self.assignColumns = QtGui.QWizardPage()
        self.assignColumns.setObjectName(_fromUtf8("assignColumns"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.assignColumns)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.groupBox_5 = QtGui.QGroupBox(self.assignColumns)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.btnSrcUp = QtGui.QPushButton(self.groupBox_5)
        self.btnSrcUp.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnSrcUp.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/up.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSrcUp.setIcon(icon)
        self.btnSrcUp.setObjectName(_fromUtf8("btnSrcUp"))
        self.gridLayout_3.addWidget(self.btnSrcUp, 0, 0, 1, 1)
        self.btnSrcDown = QtGui.QPushButton(self.groupBox_5)
        self.btnSrcDown.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnSrcDown.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/down.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnSrcDown.setIcon(icon1)
        self.btnSrcDown.setObjectName(_fromUtf8("btnSrcDown"))
        self.gridLayout_3.addWidget(self.btnSrcDown, 1, 0, 1, 1)
        self.btnSrcAll = QtGui.QPushButton(self.groupBox_5)
        self.btnSrcAll.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnSrcAll.setObjectName(_fromUtf8("btnSrcAll"))
        self.gridLayout_3.addWidget(self.btnSrcAll, 2, 0, 1, 1)
        self.btnSrcNone = QtGui.QPushButton(self.groupBox_5)
        self.btnSrcNone.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnSrcNone.setObjectName(_fromUtf8("btnSrcNone"))
        self.gridLayout_3.addWidget(self.btnSrcNone, 3, 0, 1, 1)
        self.lstSrcFields = QtGui.QListWidget(self.groupBox_5)
        self.lstSrcFields.setMinimumSize(QtCore.QSize(0, 250))
        self.lstSrcFields.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.lstSrcFields.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lstSrcFields.setObjectName(_fromUtf8("lstSrcFields"))
        self.gridLayout_3.addWidget(self.lstSrcFields, 0, 1, 5, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_5)
        self.groupBox_6 = QtGui.QGroupBox(self.assignColumns)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.btnDestUp = QtGui.QPushButton(self.groupBox_6)
        self.btnDestUp.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnDestUp.setText(_fromUtf8(""))
        self.btnDestUp.setIcon(icon)
        self.btnDestUp.setObjectName(_fromUtf8("btnDestUp"))
        self.gridLayout_4.addWidget(self.btnDestUp, 0, 2, 1, 1)
        self.btnDestDown = QtGui.QPushButton(self.groupBox_6)
        self.btnDestDown.setMaximumSize(QtCore.QSize(50, 16777215))
        self.btnDestDown.setText(_fromUtf8(""))
        self.btnDestDown.setIcon(icon1)
        self.btnDestDown.setObjectName(_fromUtf8("btnDestDown"))
        self.gridLayout_4.addWidget(self.btnDestDown, 1, 2, 1, 1)
        self.lstTargetFields = QtGui.QListWidget(self.groupBox_6)
        self.lstTargetFields.setMinimumSize(QtCore.QSize(0, 250))
        self.lstTargetFields.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.lstTargetFields.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.lstTargetFields.setObjectName(_fromUtf8("lstTargetFields"))
        self.gridLayout_4.addWidget(self.lstTargetFields, 0, 0, 3, 1)
        self.horizontalLayout_3.addWidget(self.groupBox_6)
        frmImport.addPage(self.assignColumns)

        self.retranslateUi(frmImport)
        QtCore.QMetaObject.connectSlotsByName(frmImport)

    def retranslateUi(self, frmImport):
        frmImport.setWindowTitle(_translate("frmImport", "Import to STDM", None))
        self.pgSource.setTitle(_translate("frmImport", "Source Data", None))
        self.pgSource.setSubTitle(_translate("frmImport", "Specify the location of the source file and representative data type.", None))
        self.groupBox.setTitle(_translate("frmImport", "Source:", None))
        self.label.setText(_translate("frmImport", "Dataset", None))
        self.btnBrowseSource.setText(_translate("frmImport", "Browse", None))
        self.groupBox_2.setTitle(_translate("frmImport", "Destination Repository Type:", None))
        self.rbTextType.setText(_translate("frmImport", "Textual Data", None))
        self.rbSpType.setText(_translate("frmImport", "Spatial Data", None))
        self.destTable.setTitle(_translate("frmImport", "Copy Table", None))
        self.destTable.setSubTitle(_translate("frmImport", "Destination table and import options.", None))
        self.groupBox_3.setTitle(_translate("frmImport", "Select Destination Table:", None))
        self.groupBox_4.setTitle(_translate("frmImport", "Options:", None))
        self.rbAppend.setText(_translate("frmImport", "A&ppend Data", None))
        self.rbOverwrite.setText(_translate("frmImport", "&Overwrite Existing", None))
        self.label_2.setText(_translate("frmImport", "Geometry Column:", None))
        self.assignColumns.setTitle(_translate("frmImport", "Assign Columns", None))
        self.assignColumns.setSubTitle(_translate("frmImport", "Match source and destination table columns.", None))
        self.groupBox_5.setTitle(_translate("frmImport", "Source Table:", None))
        self.btnSrcAll.setText(_translate("frmImport", "&All", None))
        self.btnSrcNone.setText(_translate("frmImport", "Non&e", None))
        self.groupBox_6.setTitle(_translate("frmImport", "Destination Table:", None))
