# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_image_export_settings.ui'
#
# Created: Wed Nov 30 22:55:00 2016
#      by: PyQt4 UI code generator 4.9.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_ImageExportSettings(object):
    def setupUi(self, ImageExportSettings):
        ImageExportSettings.setObjectName(_fromUtf8("ImageExportSettings"))
        ImageExportSettings.resize(299, 283)
        self.gridLayout_4 = QtGui.QGridLayout(ImageExportSettings)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.btn_path = QtGui.QToolButton(ImageExportSettings)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/open_file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_path.setIcon(icon)
        self.btn_path.setObjectName(_fromUtf8("btn_path"))
        self.gridLayout_4.addWidget(self.btn_path, 2, 1, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(ImageExportSettings)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_4.addWidget(self.buttonBox, 5, 0, 1, 2)
        self.txt_path = QtGui.QLineEdit(ImageExportSettings)
        self.txt_path.setObjectName(_fromUtf8("txt_path"))
        self.gridLayout_4.addWidget(self.txt_path, 2, 0, 1, 1)
        self.label = QtGui.QLabel(ImageExportSettings)
        self.label.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 2)
        self.groupBox = QtGui.QGroupBox(ImageExportSettings)
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setSpacing(2)
        self.horizontalLayout.setContentsMargins(-1, 0, -1, 9)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.sb_resolution = QtGui.QSpinBox(self.groupBox)
        self.sb_resolution.setMinimum(72)
        self.sb_resolution.setMaximum(600)
        self.sb_resolution.setProperty("value", 96)
        self.sb_resolution.setObjectName(_fromUtf8("sb_resolution"))
        self.horizontalLayout.addWidget(self.sb_resolution)
        self.frame = QtGui.QFrame(self.groupBox)
        self.frame.setMinimumSize(QtCore.QSize(0, 40))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout = QtGui.QGridLayout(self.frame)
        self.gridLayout.setContentsMargins(-1, 0, -1, 0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 4)
        self.label_3 = QtGui.QLabel(self.frame)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lbl_width = QtGui.QLabel(self.frame)
        self.lbl_width.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_width.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbl_width.setText(_fromUtf8(""))
        self.lbl_width.setObjectName(_fromUtf8("lbl_width"))
        self.gridLayout.addWidget(self.lbl_width, 1, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 1, 2, 1, 1)
        self.lbl_height = QtGui.QLabel(self.frame)
        self.lbl_height.setMinimumSize(QtCore.QSize(50, 0))
        self.lbl_height.setFrameShape(QtGui.QFrame.NoFrame)
        self.lbl_height.setText(_fromUtf8(""))
        self.lbl_height.setObjectName(_fromUtf8("lbl_height"))
        self.gridLayout.addWidget(self.lbl_height, 1, 3, 1, 1)
        self.horizontalLayout.addWidget(self.frame)
        self.gridLayout_4.addWidget(self.groupBox, 3, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(ImageExportSettings)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.rb_transparent = QtGui.QRadioButton(self.groupBox_2)
        self.rb_transparent.setChecked(True)
        self.rb_transparent.setObjectName(_fromUtf8("rb_transparent"))
        self.gridLayout_2.addWidget(self.rb_transparent, 0, 0, 1, 3)
        self.rb_fill = QtGui.QRadioButton(self.groupBox_2)
        self.rb_fill.setObjectName(_fromUtf8("rb_fill"))
        self.gridLayout_2.addWidget(self.rb_fill, 1, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(160, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 1, 1, 1, 1)
        self.btn_color = QgsColorButtonV2(self.groupBox_2)
        self.btn_color.setObjectName(_fromUtf8("btn_color"))
        self.gridLayout_2.addWidget(self.btn_color, 1, 2, 1, 1)
        self.gridLayout_4.addWidget(self.groupBox_2, 4, 0, 1, 2)
        self.vl_notification = QtGui.QVBoxLayout()
        self.vl_notification.setObjectName(_fromUtf8("vl_notification"))
        self.gridLayout_4.addLayout(self.vl_notification, 0, 0, 1, 2)

        self.retranslateUi(ImageExportSettings)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), ImageExportSettings.reject)
        QtCore.QObject.connect(self.rb_fill, QtCore.SIGNAL(_fromUtf8("toggled(bool)")), self.btn_color.setVisible)
        QtCore.QMetaObject.connectSlotsByName(ImageExportSettings)

    def retranslateUi(self, ImageExportSettings):
        ImageExportSettings.setWindowTitle(QtGui.QApplication.translate("ImageExportSettings", "Image Export Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_path.setText(QtGui.QApplication.translate("ImageExportSettings", "...", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("ImageExportSettings", "Image location", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("ImageExportSettings", "Resolution", None, QtGui.QApplication.UnicodeUTF8))
        self.sb_resolution.setSuffix(QtGui.QApplication.translate("ImageExportSettings", " dpi", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("ImageExportSettings", "<html><head/><body><p><span style=\" font-weight:600;\">Image size</span></p></body></html>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("ImageExportSettings", "Width:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("ImageExportSettings", "Height:", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("ImageExportSettings", "Background", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_transparent.setText(QtGui.QApplication.translate("ImageExportSettings", "Transparent", None, QtGui.QApplication.UnicodeUTF8))
        self.rb_fill.setText(QtGui.QApplication.translate("ImageExportSettings", "Fill color", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_color.setText(QtGui.QApplication.translate("ImageExportSettings", "...", None, QtGui.QApplication.UnicodeUTF8))

from qgis.gui import QgsColorButtonV2
from stdm import resources_rc
