# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_length_conversion.ui'
#
# Created: Fri Sep 14 18:20:17 2018
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_LengthConversion(object):
    def setupUi(self, LengthConversion):
        LengthConversion.setObjectName(_fromUtf8("LengthConversion"))
        LengthConversion.resize(482, 201)
        self.verticalLayout = QtGui.QVBoxLayout(LengthConversion)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.swTo = QtGui.QStackedWidget(LengthConversion)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swTo.sizePolicy().hasHeightForWidth())
        self.swTo.setSizePolicy(sizePolicy)
        self.swTo.setMinimumSize(QtCore.QSize(200, 0))
        self.swTo.setFrameShape(QtGui.QFrame.Box)
        self.swTo.setObjectName(_fromUtf8("swTo"))
        self.pgSqMtr2 = QtGui.QWidget()
        self.pgSqMtr2.setObjectName(_fromUtf8("pgSqMtr2"))
        self.layoutWidget_3 = QtGui.QWidget(self.pgSqMtr2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 20, 161, 41))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.label_5 = QtGui.QLabel(self.layoutWidget_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout_4.addWidget(self.label_5)
        self.edtSqMtr2 = QtGui.QDoubleSpinBox(self.layoutWidget_3)
        self.edtSqMtr2.setReadOnly(True)
        self.edtSqMtr2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtSqMtr2.setObjectName(_fromUtf8("edtSqMtr2"))
        self.verticalLayout_4.addWidget(self.edtSqMtr2)
        self.swTo.addWidget(self.pgSqMtr2)
        self.pgSqFt2 = QtGui.QWidget()
        self.pgSqFt2.setObjectName(_fromUtf8("pgSqFt2"))
        self.layoutWidget_4 = QtGui.QWidget(self.pgSqFt2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(10, 20, 161, 41))
        self.layoutWidget_4.setObjectName(_fromUtf8("layoutWidget_4"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label_15 = QtGui.QLabel(self.layoutWidget_4)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_5.addWidget(self.label_15)
        self.edtSqFt2 = QtGui.QDoubleSpinBox(self.layoutWidget_4)
        self.edtSqFt2.setReadOnly(True)
        self.edtSqFt2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtSqFt2.setObjectName(_fromUtf8("edtSqFt2"))
        self.verticalLayout_5.addWidget(self.edtSqFt2)
        self.swTo.addWidget(self.pgSqFt2)
        self.pgRopani2 = QtGui.QWidget()
        self.pgRopani2.setObjectName(_fromUtf8("pgRopani2"))
        self.layoutWidget_5 = QtGui.QWidget(self.pgRopani2)
        self.layoutWidget_5.setGeometry(QtCore.QRect(10, 10, 174, 100))
        self.layoutWidget_5.setObjectName(_fromUtf8("layoutWidget_5"))
        self.gridLayout_4 = QtGui.QGridLayout(self.layoutWidget_5)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_6 = QtGui.QLabel(self.layoutWidget_5)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_4.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget_5)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_4.addWidget(self.label_17, 1, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget_5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_4.addWidget(self.label_18, 2, 0, 1, 1)
        self.label_19 = QtGui.QLabel(self.layoutWidget_5)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_4.addWidget(self.label_19, 3, 0, 1, 1)
        self.edtRopani2 = QtGui.QDoubleSpinBox(self.layoutWidget_5)
        self.edtRopani2.setReadOnly(True)
        self.edtRopani2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtRopani2.setObjectName(_fromUtf8("edtRopani2"))
        self.gridLayout_4.addWidget(self.edtRopani2, 0, 1, 1, 1)
        self.edtAana2 = QtGui.QDoubleSpinBox(self.layoutWidget_5)
        self.edtAana2.setReadOnly(True)
        self.edtAana2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtAana2.setObjectName(_fromUtf8("edtAana2"))
        self.gridLayout_4.addWidget(self.edtAana2, 1, 1, 1, 1)
        self.edtPaisa2 = QtGui.QDoubleSpinBox(self.layoutWidget_5)
        self.edtPaisa2.setReadOnly(True)
        self.edtPaisa2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtPaisa2.setObjectName(_fromUtf8("edtPaisa2"))
        self.gridLayout_4.addWidget(self.edtPaisa2, 2, 1, 1, 1)
        self.edtDaam2 = QtGui.QDoubleSpinBox(self.layoutWidget_5)
        self.edtDaam2.setReadOnly(True)
        self.edtDaam2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtDaam2.setObjectName(_fromUtf8("edtDaam2"))
        self.gridLayout_4.addWidget(self.edtDaam2, 3, 1, 1, 1)
        self.swTo.addWidget(self.pgRopani2)
        self.pgBigaha2 = QtGui.QWidget()
        self.pgBigaha2.setObjectName(_fromUtf8("pgBigaha2"))
        self.layoutWidget_6 = QtGui.QWidget(self.pgBigaha2)
        self.layoutWidget_6.setGeometry(QtCore.QRect(10, 10, 174, 100))
        self.layoutWidget_6.setObjectName(_fromUtf8("layoutWidget_6"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget_6)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_7 = QtGui.QLabel(self.layoutWidget_6)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_20 = QtGui.QLabel(self.layoutWidget_6)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_5.addWidget(self.label_20, 1, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.layoutWidget_6)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_5.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.layoutWidget_6)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_5.addWidget(self.label_22, 3, 0, 1, 1)
        self.edtBigaha2 = QtGui.QDoubleSpinBox(self.layoutWidget_6)
        self.edtBigaha2.setReadOnly(True)
        self.edtBigaha2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtBigaha2.setObjectName(_fromUtf8("edtBigaha2"))
        self.gridLayout_5.addWidget(self.edtBigaha2, 0, 1, 1, 1)
        self.edtKattha2 = QtGui.QDoubleSpinBox(self.layoutWidget_6)
        self.edtKattha2.setReadOnly(True)
        self.edtKattha2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtKattha2.setObjectName(_fromUtf8("edtKattha2"))
        self.gridLayout_5.addWidget(self.edtKattha2, 1, 1, 1, 1)
        self.edtDhur2 = QtGui.QDoubleSpinBox(self.layoutWidget_6)
        self.edtDhur2.setReadOnly(True)
        self.edtDhur2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtDhur2.setObjectName(_fromUtf8("edtDhur2"))
        self.gridLayout_5.addWidget(self.edtDhur2, 2, 1, 1, 1)
        self.edtKanuwa2 = QtGui.QDoubleSpinBox(self.layoutWidget_6)
        self.edtKanuwa2.setReadOnly(True)
        self.edtKanuwa2.setButtonSymbols(QtGui.QAbstractSpinBox.NoButtons)
        self.edtKanuwa2.setObjectName(_fromUtf8("edtKanuwa2"))
        self.gridLayout_5.addWidget(self.edtKanuwa2, 3, 1, 1, 1)
        self.swTo.addWidget(self.pgBigaha2)
        self.gridLayout.addWidget(self.swTo, 1, 3, 1, 1)
        self.swFrom = QtGui.QStackedWidget(LengthConversion)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.swFrom.sizePolicy().hasHeightForWidth())
        self.swFrom.setSizePolicy(sizePolicy)
        self.swFrom.setMinimumSize(QtCore.QSize(200, 0))
        self.swFrom.setFrameShape(QtGui.QFrame.Box)
        self.swFrom.setObjectName(_fromUtf8("swFrom"))
        self.pgSqMtr = QtGui.QWidget()
        self.pgSqMtr.setObjectName(_fromUtf8("pgSqMtr"))
        self.widget = QtGui.QWidget(self.pgSqMtr)
        self.widget.setGeometry(QtCore.QRect(20, 20, 161, 41))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.widget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_2.addWidget(self.label_2)
        self.edtSqMtr = QtGui.QDoubleSpinBox(self.widget)
        self.edtSqMtr.setObjectName(_fromUtf8("edtSqMtr"))
        self.verticalLayout_2.addWidget(self.edtSqMtr)
        self.swFrom.addWidget(self.pgSqMtr)
        self.pgSqFt = QtGui.QWidget()
        self.pgSqFt.setObjectName(_fromUtf8("pgSqFt"))
        self.layoutWidget = QtGui.QWidget(self.pgSqFt)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 20, 161, 41))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_8 = QtGui.QLabel(self.layoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_3.addWidget(self.label_8)
        self.edtSqFt = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.edtSqFt.setObjectName(_fromUtf8("edtSqFt"))
        self.verticalLayout_3.addWidget(self.edtSqFt)
        self.swFrom.addWidget(self.pgSqFt)
        self.pgRopani = QtGui.QWidget()
        self.pgRopani.setObjectName(_fromUtf8("pgRopani"))
        self.widget1 = QtGui.QWidget(self.pgRopani)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 174, 100))
        self.widget1.setObjectName(_fromUtf8("widget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.widget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.widget1)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.widget1)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.widget1)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_2.addWidget(self.label_10, 2, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.widget1)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 3, 0, 1, 1)
        self.edtRopani = QtGui.QDoubleSpinBox(self.widget1)
        self.edtRopani.setObjectName(_fromUtf8("edtRopani"))
        self.gridLayout_2.addWidget(self.edtRopani, 0, 1, 1, 1)
        self.edtAana = QtGui.QDoubleSpinBox(self.widget1)
        self.edtAana.setObjectName(_fromUtf8("edtAana"))
        self.gridLayout_2.addWidget(self.edtAana, 1, 1, 1, 1)
        self.edtPaisa = QtGui.QDoubleSpinBox(self.widget1)
        self.edtPaisa.setObjectName(_fromUtf8("edtPaisa"))
        self.gridLayout_2.addWidget(self.edtPaisa, 2, 1, 1, 1)
        self.edtDaam = QtGui.QDoubleSpinBox(self.widget1)
        self.edtDaam.setObjectName(_fromUtf8("edtDaam"))
        self.gridLayout_2.addWidget(self.edtDaam, 3, 1, 1, 1)
        self.swFrom.addWidget(self.pgRopani)
        self.pgBigaha = QtGui.QWidget()
        self.pgBigaha.setObjectName(_fromUtf8("pgBigaha"))
        self.layoutWidget_2 = QtGui.QWidget(self.pgBigaha)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 10, 174, 100))
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.layoutWidget_2)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_4 = QtGui.QLabel(self.layoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_12 = QtGui.QLabel(self.layoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 1, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.layoutWidget_2)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.layoutWidget_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 3, 0, 1, 1)
        self.edtBigaha = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.edtBigaha.setObjectName(_fromUtf8("edtBigaha"))
        self.gridLayout_3.addWidget(self.edtBigaha, 0, 1, 1, 1)
        self.edtKattha = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.edtKattha.setObjectName(_fromUtf8("edtKattha"))
        self.gridLayout_3.addWidget(self.edtKattha, 1, 1, 1, 1)
        self.edtDhur = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.edtDhur.setObjectName(_fromUtf8("edtDhur"))
        self.gridLayout_3.addWidget(self.edtDhur, 2, 1, 1, 1)
        self.edtKanuwa = QtGui.QDoubleSpinBox(self.layoutWidget_2)
        self.edtKanuwa.setObjectName(_fromUtf8("edtKanuwa"))
        self.gridLayout_3.addWidget(self.edtKanuwa, 3, 1, 1, 1)
        self.swFrom.addWidget(self.pgBigaha)
        self.gridLayout.addWidget(self.swFrom, 1, 0, 1, 2)
        spacerItem = QtGui.QSpacerItem(200, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 2, 1, 1)
        self.cbFrom = QtGui.QComboBox(LengthConversion)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbFrom.sizePolicy().hasHeightForWidth())
        self.cbFrom.setSizePolicy(sizePolicy)
        self.cbFrom.setMinimumSize(QtCore.QSize(50, 0))
        self.cbFrom.setObjectName(_fromUtf8("cbFrom"))
        self.gridLayout.addWidget(self.cbFrom, 0, 0, 1, 2)
        self.cbTo = QtGui.QComboBox(LengthConversion)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbTo.sizePolicy().hasHeightForWidth())
        self.cbTo.setSizePolicy(sizePolicy)
        self.cbTo.setObjectName(_fromUtf8("cbTo"))
        self.gridLayout.addWidget(self.cbTo, 0, 3, 1, 1)
        self.label = QtGui.QLabel(LengthConversion)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 2, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setColumnStretch(3, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.btnClose = QtGui.QPushButton(LengthConversion)
        self.btnClose.setObjectName(_fromUtf8("btnClose"))
        self.horizontalLayout.addWidget(self.btnClose)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(LengthConversion)
        self.swTo.setCurrentIndex(3)
        self.swFrom.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(LengthConversion)

    def retranslateUi(self, LengthConversion):
        LengthConversion.setWindowTitle(_translate("LengthConversion", "Length Conversion Tool", None))
        self.label_5.setText(_translate("LengthConversion", "Square Meter", None))
        self.label_15.setText(_translate("LengthConversion", "Square Feet", None))
        self.label_6.setText(_translate("LengthConversion", "Ropani", None))
        self.label_17.setText(_translate("LengthConversion", "Aana", None))
        self.label_18.setText(_translate("LengthConversion", "Paisa", None))
        self.label_19.setText(_translate("LengthConversion", "Daam", None))
        self.label_7.setText(_translate("LengthConversion", "Bigaha", None))
        self.label_20.setText(_translate("LengthConversion", "Kattha", None))
        self.label_21.setText(_translate("LengthConversion", "Dhur", None))
        self.label_22.setText(_translate("LengthConversion", "Kunuwa", None))
        self.label_2.setText(_translate("LengthConversion", "Square Meter", None))
        self.label_8.setText(_translate("LengthConversion", "Square Feet", None))
        self.label_3.setText(_translate("LengthConversion", "Ropani", None))
        self.label_9.setText(_translate("LengthConversion", "Aana", None))
        self.label_10.setText(_translate("LengthConversion", "Paisa", None))
        self.label_11.setText(_translate("LengthConversion", "Daam", None))
        self.label_4.setText(_translate("LengthConversion", "Bigaha", None))
        self.label_12.setText(_translate("LengthConversion", "Kattha", None))
        self.label_13.setText(_translate("LengthConversion", "Dhur", None))
        self.label_14.setText(_translate("LengthConversion", "Kunuwa", None))
        self.label.setText(_translate("LengthConversion", "TO", None))
        self.btnClose.setText(_translate("LengthConversion", "Close", None))

