# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_new_str.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmNewSTR(object):
    def setupUi(self, frmNewSTR):
        frmNewSTR.setObjectName(_fromUtf8("frmNewSTR"))
        frmNewSTR.resize(663, 576)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmNewSTR.sizePolicy().hasHeightForWidth())
        frmNewSTR.setSizePolicy(sizePolicy)
        frmNewSTR.setWizardStyle(QtGui.QWizard.ModernStyle)
        frmNewSTR.setOptions(QtGui.QWizard.HelpButtonOnRight)
        self.frmWizAbout = QtGui.QWizardPage()
        self.frmWizAbout.setObjectName(_fromUtf8("frmWizAbout"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frmWizAbout)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.frmWizAbout)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        frmNewSTR.addPage(self.frmWizAbout)
        self.frmWizPerson = QtGui.QWizardPage()
        self.frmWizPerson.setObjectName(_fromUtf8("frmWizPerson"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frmWizPerson)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.vlPersonNotif = QtGui.QVBoxLayout()
        self.vlPersonNotif.setObjectName(_fromUtf8("vlPersonNotif"))
        self.verticalLayout_2.addLayout(self.vlPersonNotif)
        self.groupBox = QtGui.QGroupBox(self.frmWizPerson)
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.AddPartybtn = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddPartybtn.sizePolicy().hasHeightForWidth())
        self.AddPartybtn.setSizePolicy(sizePolicy)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.AddPartybtn.setIcon(icon)
        self.AddPartybtn.setObjectName(_fromUtf8("AddPartybtn"))
        self.horizontalLayout.addWidget(self.AddPartybtn)
        self.RemovePartybtn = QtGui.QPushButton(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemovePartybtn.sizePolicy().hasHeightForWidth())
        self.RemovePartybtn.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.RemovePartybtn.setIcon(icon1)
        self.RemovePartybtn.setObjectName(_fromUtf8("RemovePartybtn"))
        self.horizontalLayout.addWidget(self.RemovePartybtn)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.scrollArea_2 = QtGui.QScrollArea(self.frmWizPerson)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 617, 367))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.tvPersonInfo = QtGui.QWidget(self.scrollAreaWidgetContents_3)
        self.tvPersonInfo.setGeometry(QtCore.QRect(0, 0, 619, 371))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tvPersonInfo.sizePolicy().hasHeightForWidth())
        self.tvPersonInfo.setSizePolicy(sizePolicy)
        self.tvPersonInfo.setObjectName(_fromUtf8("tvPersonInfo"))
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.addWidget(self.scrollArea_2)
        frmNewSTR.addPage(self.frmWizPerson)
        self.frmWizProperty = QtGui.QWizardPage()
        self.frmWizProperty.setObjectName(_fromUtf8("frmWizProperty"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frmWizProperty)
        self.verticalLayout_8.setContentsMargins(0, 3, 0, 8)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.vlPropNotif = QtGui.QVBoxLayout()
        self.vlPropNotif.setObjectName(_fromUtf8("vlPropNotif"))
        self.verticalLayout_8.addLayout(self.vlPropNotif)
        self.tabWidget = QtGui.QTabWidget(self.frmWizProperty)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_5.sizePolicy().hasHeightForWidth())
        self.groupBox_5.setSizePolicy(sizePolicy)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_5)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.AddSpatialUnitbtn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.AddSpatialUnitbtn.sizePolicy().hasHeightForWidth())
        self.AddSpatialUnitbtn.setSizePolicy(sizePolicy)
        self.AddSpatialUnitbtn.setIcon(icon)
        self.AddSpatialUnitbtn.setObjectName(_fromUtf8("AddSpatialUnitbtn"))
        self.horizontalLayout_3.addWidget(self.AddSpatialUnitbtn)
        self.RemoveSpatialUnitbtn = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.RemoveSpatialUnitbtn.sizePolicy().hasHeightForWidth())
        self.RemoveSpatialUnitbtn.setSizePolicy(sizePolicy)
        self.RemoveSpatialUnitbtn.setIcon(icon1)
        self.RemoveSpatialUnitbtn.setObjectName(_fromUtf8("RemoveSpatialUnitbtn"))
        self.horizontalLayout_3.addWidget(self.RemoveSpatialUnitbtn)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout_4.addWidget(self.groupBox_5)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.tvPropInfo = QtGui.QWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tvPropInfo.sizePolicy().hasHeightForWidth())
        self.tvPropInfo.setSizePolicy(sizePolicy)
        self.tvPropInfo.setObjectName(_fromUtf8("tvPropInfo"))
        self.verticalLayout_9.addWidget(self.tvPropInfo)
        self.verticalLayout_4.addLayout(self.verticalLayout_9)
        spacerItem2 = QtGui.QSpacerItem(20, 238, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gpOpenLayers = QtGui.QGroupBox(self.tab_2)
        self.gpOpenLayers.setCheckable(True)
        self.gpOpenLayers.setChecked(False)
        self.gpOpenLayers.setObjectName(_fromUtf8("gpOpenLayers"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gpOpenLayers)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.propWebView = QtWebKit.QWebView(self.gpOpenLayers)
        self.propWebView.setStyleSheet(_fromUtf8(""))
        self.propWebView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.propWebView.setObjectName(_fromUtf8("propWebView"))
        self.gridLayout_3.addWidget(self.propWebView, 0, 0, 1, 4)
        self.label_9 = QtGui.QLabel(self.gpOpenLayers)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 3, 2, 1, 1)
        self.zoomSlider = QtGui.QSlider(self.gpOpenLayers)
        self.zoomSlider.setMinimum(2)
        self.zoomSlider.setMaximum(20)
        self.zoomSlider.setProperty("value", 12)
        self.zoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zoomSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.zoomSlider.setTickInterval(2)
        self.zoomSlider.setObjectName(_fromUtf8("zoomSlider"))
        self.gridLayout_3.addWidget(self.zoomSlider, 2, 0, 1, 3)
        self.btnResetMap = QtGui.QPushButton(self.gpOpenLayers)
        self.btnResetMap.setObjectName(_fromUtf8("btnResetMap"))
        self.gridLayout_3.addWidget(self.btnResetMap, 2, 3, 1, 1)
        self.label_7 = QtGui.QLabel(self.gpOpenLayers)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 3, 1, 1, 1)
        self.groupBox_2 = QtGui.QGroupBox(self.gpOpenLayers)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.rbOSM = QtGui.QRadioButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbOSM.sizePolicy().hasHeightForWidth())
        self.rbOSM.setSizePolicy(sizePolicy)
        self.rbOSM.setMinimumSize(QtCore.QSize(0, 16))
        self.rbOSM.setObjectName(_fromUtf8("rbOSM"))
        self.gridLayout_5.addWidget(self.rbOSM, 0, 1, 1, 1)
        self.rbGMaps = QtGui.QRadioButton(self.groupBox_2)
        self.rbGMaps.setMinimumSize(QtCore.QSize(0, 16))
        self.rbGMaps.setChecked(True)
        self.rbGMaps.setObjectName(_fromUtf8("rbGMaps"))
        self.gridLayout_5.addWidget(self.rbGMaps, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 4)
        self.label_8 = QtGui.QLabel(self.gpOpenLayers)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.gpOpenLayers)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_8.addWidget(self.tabWidget)
        frmNewSTR.addPage(self.frmWizProperty)
        self.frmWizSTRType = QtGui.QWizardPage()
        self.frmWizSTRType.setToolTip(_fromUtf8(""))
        self.frmWizSTRType.setObjectName(_fromUtf8("frmWizSTRType"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frmWizSTRType)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.vlSTRTypeNotif = QtGui.QVBoxLayout()
        self.vlSTRTypeNotif.setObjectName(_fromUtf8("vlSTRTypeNotif"))
        self.verticalLayout_7.addLayout(self.vlSTRTypeNotif)
        self.scrollArea_3 = QtGui.QScrollArea(self.frmWizSTRType)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.STRTypeWidget = QtGui.QWidget()
        self.STRTypeWidget.setEnabled(True)
        self.STRTypeWidget.setGeometry(QtCore.QRect(0, 0, 617, 427))
        self.STRTypeWidget.setObjectName(_fromUtf8("STRTypeWidget"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.STRTypeWidget)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.verticalLayout_12.addLayout(self.verticalLayout_11)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem3)
        self.scrollArea_3.setWidget(self.STRTypeWidget)
        self.verticalLayout_7.addWidget(self.scrollArea_3)
        frmNewSTR.addPage(self.frmWizSTRType)
        self.frmWizSourceDocs = QtGui.QWizardPage()
        self.frmWizSourceDocs.setObjectName(_fromUtf8("frmWizSourceDocs"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frmWizSourceDocs)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.vlSourceDocNotif = QtGui.QVBoxLayout()
        self.vlSourceDocNotif.setObjectName(_fromUtf8("vlSourceDocNotif"))
        self.verticalLayout_6.addLayout(self.vlSourceDocNotif)
        self.groupBox_3 = QtGui.QGroupBox(self.frmWizSourceDocs)
        self.groupBox_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.cboDocType = QtGui.QComboBox(self.groupBox_3)
        self.cboDocType.setMinimumSize(QtCore.QSize(0, 30))
        self.cboDocType.setObjectName(_fromUtf8("cboDocType"))
        self.gridLayout_6.addWidget(self.cboDocType, 0, 1, 1, 1)
        self.btnAddTitleDeed = QtGui.QPushButton(self.groupBox_3)
        self.btnAddTitleDeed.setMinimumSize(QtCore.QSize(0, 30))
        self.btnAddTitleDeed.setMaximumSize(QtCore.QSize(200, 32))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/attachment.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddTitleDeed.setIcon(icon2)
        self.btnAddTitleDeed.setObjectName(_fromUtf8("btnAddTitleDeed"))
        self.gridLayout_6.addWidget(self.btnAddTitleDeed, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_6)
        self.scrollArea = QtGui.QScrollArea(self.groupBox_3)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 593, 348))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_2 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.vlDocTitleDeed = QtGui.QVBoxLayout()
        self.vlDocTitleDeed.setObjectName(_fromUtf8("vlDocTitleDeed"))
        self.gridLayout_7.addLayout(self.vlDocTitleDeed, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_3.addWidget(self.scrollArea)
        self.verticalLayout_6.addWidget(self.groupBox_3)
        frmNewSTR.addPage(self.frmWizSourceDocs)
        self.frmSTRSummary = QtGui.QWizardPage()
        self.frmSTRSummary.setObjectName(_fromUtf8("frmSTRSummary"))
        self.gridLayout_14 = QtGui.QGridLayout(self.frmSTRSummary)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.twSTRSummary = QtGui.QTreeWidget(self.frmSTRSummary)
        self.twSTRSummary.setFrameShadow(QtGui.QFrame.Sunken)
        self.twSTRSummary.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.twSTRSummary.setObjectName(_fromUtf8("twSTRSummary"))
        self.twSTRSummary.headerItem().setText(0, _fromUtf8("1"))
        self.twSTRSummary.header().setVisible(False)
        self.gridLayout_14.addWidget(self.twSTRSummary, 1, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.frmSTRSummary)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_14.addWidget(self.label_18, 0, 0, 1, 1)
        frmNewSTR.addPage(self.frmSTRSummary)

        self.retranslateUi(frmNewSTR)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmNewSTR)

    def retranslateUi(self, frmNewSTR):
        frmNewSTR.setWindowTitle(_translate("frmNewSTR", "New Social Tenure Relationship", None))
        self.frmWizAbout.setTitle(_translate("frmNewSTR", "About", None))
        self.frmWizAbout.setSubTitle(_translate("frmNewSTR", "General information about Social Tenure Relationship (STR).", None))
        self.label.setText(_translate("frmNewSTR", "<html><head/><body><p>Scoial Tenure Relationship refers to the right or \'relationship\' between persons and properties (which as represented as polygons on the map). It also includes conflict information associated with a given property.</p><p>This module provides a mechanism for defining STR applicable to property - both land and building</p><p>Click on the \'Next\' button below to proceed.</p></body></html>", None))
        self.frmWizPerson.setTitle(_translate("frmNewSTR", "Occupant Information", None))
        self.frmWizPerson.setSubTitle(_translate("frmNewSTR", "Select the occupant information by searching through the existing repository.", None))
        self.AddPartybtn.setText(_translate("frmNewSTR", "Add", None))
        self.RemovePartybtn.setText(_translate("frmNewSTR", "Remove", None))
        self.frmWizProperty.setTitle(_translate("frmNewSTR", "Spatial unit information", None))
        self.frmWizProperty.setSubTitle(_translate("frmNewSTR", "Select the land or building information.", None))
        self.AddSpatialUnitbtn.setText(_translate("frmNewSTR", "Add", None))
        self.RemoveSpatialUnitbtn.setText(_translate("frmNewSTR", "Remove", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmNewSTR", "Add Record", None))
        self.gpOpenLayers.setTitle(_translate("frmNewSTR", "Preview Spatial Unit:", None))
        self.label_9.setText(_translate("frmNewSTR", "+", None))
        self.btnResetMap.setText(_translate("frmNewSTR", "Reset Map", None))
        self.label_7.setText(_translate("frmNewSTR", "Zoom", None))
        self.groupBox_2.setTitle(_translate("frmNewSTR", "Choose Base Layer", None))
        self.rbOSM.setText(_translate("frmNewSTR", "Open Street Maps", None))
        self.rbGMaps.setText(_translate("frmNewSTR", "Google Maps", None))
        self.label_8.setText(_translate("frmNewSTR", "-", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmNewSTR", "Preview", None))
        self.frmWizSTRType.setTitle(_translate("frmNewSTR", "Social Tenure Relationship (STR) Type", None))
        self.frmWizSTRType.setSubTitle(_translate("frmNewSTR", "Select the type of relationship that the specified person has with the selected property.", None))
        self.frmWizSourceDocs.setTitle(_translate("frmNewSTR", "Source Documents", None))
        self.frmWizSourceDocs.setSubTitle(_translate("frmNewSTR", "Upload one or more documents.", None))
        self.groupBox_3.setTitle(_translate("frmNewSTR", "Supporting Documents", None))
        self.btnAddTitleDeed.setText(_translate("frmNewSTR", "Add Supporting Document", None))
        self.label_4.setText(_translate("frmNewSTR", "Document Type", None))
        self.frmSTRSummary.setTitle(_translate("frmNewSTR", "STR Definition Summary", None))
        self.frmSTRSummary.setSubTitle(_translate("frmNewSTR", "A new social tenure relationship will be created based on the information that you have supplied, as summarized below.", None))
        self.label_18.setText(_translate("frmNewSTR", "If you want to review or change any selections, click Back. If you are satisified with the selections, click Finish.", None))

from PyQt4 import QtWebKit
from stdm import resources_rc
