# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_new_str.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_frmNewSTR(object):
    def setupUi(self, frmNewSTR):
        frmNewSTR.setObjectName(_fromUtf8("frmNewSTR"))
        frmNewSTR.resize(672, 576)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(frmNewSTR.sizePolicy().hasHeightForWidth())
        frmNewSTR.setSizePolicy(sizePolicy)
        frmNewSTR.setWizardStyle(QtGui.QWizard.ModernStyle)
        frmNewSTR.setOptions(QtGui.QWizard.HelpButtonOnRight)
        self.frmWizAbout = QtGui.QWizardPage()
        self.frmWizAbout.setObjectName(_fromUtf8("frmWizAbout"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frmWizAbout)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.frmWizAbout)
        self.label.setWordWrap(True)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        frmNewSTR.addPage(self.frmWizAbout)
        self.frmWizParty = QtGui.QWizardPage()
        self.frmWizParty.setObjectName(_fromUtf8("frmWizParty"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frmWizParty)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.vlPartyNotif = QtGui.QVBoxLayout()
        self.vlPartyNotif.setObjectName(_fromUtf8("vlPartyNotif"))
        self.verticalLayout_2.addLayout(self.vlPartyNotif)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.scrollArea_2 = QtGui.QScrollArea(self.frmWizParty)
        self.scrollArea_2.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_2.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName(_fromUtf8("scrollArea_2"))
        self.scrollAreaWidgetContents_3 = QtGui.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, 0, 626, 427))
        self.scrollAreaWidgetContents_3.setObjectName(_fromUtf8("scrollAreaWidgetContents_3"))
        self.verticalLayout_14 = QtGui.QVBoxLayout(self.scrollAreaWidgetContents_3)
        self.verticalLayout_14.setMargin(0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.partyRecBox = QtGui.QWidget(self.scrollAreaWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.partyRecBox.sizePolicy().hasHeightForWidth())
        self.partyRecBox.setSizePolicy(sizePolicy)
        self.partyRecBox.setObjectName(_fromUtf8("partyRecBox"))
        self.verticalLayout_14.addWidget(self.partyRecBox)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_13.addWidget(self.scrollArea_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_13)
        frmNewSTR.addPage(self.frmWizParty)
        self.frmWizSpatialUnit = QtGui.QWizardPage()
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.frmWizSpatialUnit.setFont(font)
        self.frmWizSpatialUnit.setObjectName(_fromUtf8("frmWizSpatialUnit"))
        self.verticalLayout_8 = QtGui.QVBoxLayout(self.frmWizSpatialUnit)
        self.verticalLayout_8.setContentsMargins(0, 3, 0, 8)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.vlSpatialUnitNotif = QtGui.QVBoxLayout()
        self.vlSpatialUnitNotif.setObjectName(_fromUtf8("vlSpatialUnitNotif"))
        self.verticalLayout_8.addLayout(self.vlSpatialUnitNotif)
        self.tabWidget = QtGui.QTabWidget(self.frmWizSpatialUnit)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.scrollArea = QtGui.QScrollArea(self.tab)
        self.scrollArea.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.spatialUnitRecBox = QtGui.QWidget()
        self.spatialUnitRecBox.setGeometry(QtCore.QRect(0, 0, 620, 387))
        self.spatialUnitRecBox.setObjectName(_fromUtf8("spatialUnitRecBox"))
        self.scrollArea.setWidget(self.spatialUnitRecBox)
        self.verticalLayout_10.addWidget(self.scrollArea)
        self.verticalLayout_4.addLayout(self.verticalLayout_10)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.tab_2)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.gpOpenLayers = QtGui.QGroupBox(self.tab_2)
        self.gpOpenLayers.setCheckable(True)
        self.gpOpenLayers.setChecked(False)
        self.gpOpenLayers.setObjectName(_fromUtf8("gpOpenLayers"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gpOpenLayers)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.gpOpenLayers)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 50))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.rbOSM = QtGui.QRadioButton(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rbOSM.sizePolicy().hasHeightForWidth())
        self.rbOSM.setSizePolicy(sizePolicy)
        self.rbOSM.setMinimumSize(QtCore.QSize(0, 16))
        self.rbOSM.setObjectName(_fromUtf8("rbOSM"))
        self.gridLayout_5.addWidget(self.rbOSM, 0, 1, 1, 1)
        self.rbGMaps = QtGui.QRadioButton(self.groupBox_2)
        self.rbGMaps.setMinimumSize(QtCore.QSize(0, 16))
        self.rbGMaps.setChecked(True)
        self.rbGMaps.setObjectName(_fromUtf8("rbGMaps"))
        self.gridLayout_5.addWidget(self.rbGMaps, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 1, 0, 1, 4)
        self.propWebView = QtWebKit.QWebView(self.gpOpenLayers)
        self.propWebView.setStyleSheet(_fromUtf8(""))
        self.propWebView.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.propWebView.setObjectName(_fromUtf8("propWebView"))
        self.gridLayout_3.addWidget(self.propWebView, 0, 0, 1, 4)
        self.label_7 = QtGui.QLabel(self.gpOpenLayers)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_3.addWidget(self.label_7, 3, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gpOpenLayers)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        font.setKerning(False)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 3, 2, 1, 1)
        self.btnResetMap = QtGui.QPushButton(self.gpOpenLayers)
        self.btnResetMap.setObjectName(_fromUtf8("btnResetMap"))
        self.gridLayout_3.addWidget(self.btnResetMap, 2, 3, 1, 1)
        self.zoomSlider = QtGui.QSlider(self.gpOpenLayers)
        self.zoomSlider.setMinimum(2)
        self.zoomSlider.setMaximum(20)
        self.zoomSlider.setProperty("value", 12)
        self.zoomSlider.setOrientation(QtCore.Qt.Horizontal)
        self.zoomSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.zoomSlider.setTickInterval(2)
        self.zoomSlider.setObjectName(_fromUtf8("zoomSlider"))
        self.gridLayout_3.addWidget(self.zoomSlider, 2, 0, 1, 3)
        self.label_8 = QtGui.QLabel(self.gpOpenLayers)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.verticalLayout_5.addWidget(self.gpOpenLayers)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.verticalLayout_8.addWidget(self.tabWidget)
        frmNewSTR.addPage(self.frmWizSpatialUnit)
        self.frmWizSTRType = QtGui.QWizardPage()
        self.frmWizSTRType.setToolTip(_fromUtf8(""))
        self.frmWizSTRType.setObjectName(_fromUtf8("frmWizSTRType"))
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.frmWizSTRType)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.vlSTRTypeNotif = QtGui.QVBoxLayout()
        self.vlSTRTypeNotif.setObjectName(_fromUtf8("vlSTRTypeNotif"))
        self.verticalLayout_7.addLayout(self.vlSTRTypeNotif)
        self.label_2 = QtGui.QLabel(self.frmWizSTRType)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_7.addWidget(self.label_2)
        self.scrollArea_3 = QtGui.QScrollArea(self.frmWizSTRType)
        self.scrollArea_3.setFrameShape(QtGui.QFrame.NoFrame)
        self.scrollArea_3.setFrameShadow(QtGui.QFrame.Plain)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName(_fromUtf8("scrollArea_3"))
        self.STRTypeWidget = QtGui.QWidget()
        self.STRTypeWidget.setEnabled(True)
        self.STRTypeWidget.setGeometry(QtCore.QRect(0, 0, 628, 406))
        self.STRTypeWidget.setObjectName(_fromUtf8("STRTypeWidget"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.STRTypeWidget)
        self.verticalLayout_12.setMargin(0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.STRTypePartyBox = QtGui.QVBoxLayout()
        self.STRTypePartyBox.setSpacing(0)
        self.STRTypePartyBox.setObjectName(_fromUtf8("STRTypePartyBox"))
        self.verticalLayout_12.addLayout(self.STRTypePartyBox)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_12.addItem(spacerItem)
        self.scrollArea_3.setWidget(self.STRTypeWidget)
        self.verticalLayout_7.addWidget(self.scrollArea_3)
        frmNewSTR.addPage(self.frmWizSTRType)
        self.frmWizSourceDocs = QtGui.QWizardPage()
        self.frmWizSourceDocs.setObjectName(_fromUtf8("frmWizSourceDocs"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.frmWizSourceDocs)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.vlSourceDocNotif = QtGui.QVBoxLayout()
        self.vlSourceDocNotif.setObjectName(_fromUtf8("vlSourceDocNotif"))
        self.verticalLayout_6.addLayout(self.vlSourceDocNotif)
        self.gridLayout_6 = QtGui.QGridLayout()
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.cboDocType = QtGui.QComboBox(self.frmWizSourceDocs)
        self.cboDocType.setMinimumSize(QtCore.QSize(0, 30))
        self.cboDocType.setMaximumSize(QtCore.QSize(16777215, 32))
        self.cboDocType.setObjectName(_fromUtf8("cboDocType"))
        self.gridLayout_6.addWidget(self.cboDocType, 0, 1, 1, 1)
        self.btnAddDocument = QtGui.QPushButton(self.frmWizSourceDocs)
        self.btnAddDocument.setMinimumSize(QtCore.QSize(0, 30))
        self.btnAddDocument.setMaximumSize(QtCore.QSize(200, 32))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/attachment.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnAddDocument.setIcon(icon)
        self.btnAddDocument.setObjectName(_fromUtf8("btnAddDocument"))
        self.gridLayout_6.addWidget(self.btnAddDocument, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.frmWizSourceDocs)
        self.label_4.setMaximumSize(QtCore.QSize(100, 32))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_6.addWidget(self.label_4, 0, 0, 1, 1)
        self.verticalLayout_6.addLayout(self.gridLayout_6)
        self.frame_3 = QtGui.QFrame(self.frmWizSourceDocs)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setAutoFillBackground(False)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setContentsMargins(0, 8, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.suppDocumentBox = QtGui.QVBoxLayout()
        self.suppDocumentBox.setSpacing(0)
        self.suppDocumentBox.setObjectName(_fromUtf8("suppDocumentBox"))
        self.verticalLayout_3.addLayout(self.suppDocumentBox)
        self.verticalLayout_6.addWidget(self.frame_3)
        frmNewSTR.addPage(self.frmWizSourceDocs)
        self.frmSTRSummary = QtGui.QWizardPage()
        self.frmSTRSummary.setObjectName(_fromUtf8("frmSTRSummary"))
        self.gridLayout_14 = QtGui.QGridLayout(self.frmSTRSummary)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.twSTRSummary = QtGui.QTreeWidget(self.frmSTRSummary)
        self.twSTRSummary.setFrameShadow(QtGui.QFrame.Sunken)
        self.twSTRSummary.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.twSTRSummary.setObjectName(_fromUtf8("twSTRSummary"))
        self.twSTRSummary.headerItem().setText(0, _fromUtf8("1"))
        self.twSTRSummary.header().setVisible(False)
        self.gridLayout_14.addWidget(self.twSTRSummary, 1, 0, 1, 1)
        self.label_18 = QtGui.QLabel(self.frmSTRSummary)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_14.addWidget(self.label_18, 0, 0, 1, 1)
        frmNewSTR.addPage(self.frmSTRSummary)

        self.retranslateUi(frmNewSTR)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(frmNewSTR)

    def retranslateUi(self, frmNewSTR):
        frmNewSTR.setWindowTitle(_translate("frmNewSTR", "New Social Tenure Relationship", None))
        self.frmWizAbout.setTitle(_translate("frmNewSTR", "About", None))
        self.frmWizAbout.setSubTitle(_translate("frmNewSTR", "General information about Social Tenure Relationship (STR).", None))
        self.label.setText(_translate("frmNewSTR", "<html><head/><body><p>Social Tenure Relationship (STR) refers to the right or \'relationship\' between party and spatial unit (which is represented as polygons on the map). It also includes conflict information associated with a given spatial unit.</p><p>This module provides a mechanism for defining STR applicable to property - both land and building</p><p>Click on the \'Next\' button below to proceed.</p></body></html>", None))
        self.frmWizParty.setTitle(_translate("frmNewSTR", "Party Information", None))
        self.frmWizParty.setSubTitle(_translate("frmNewSTR", "Select the party by searching through the existing record.", None))
        self.frmWizSpatialUnit.setTitle(_translate("frmNewSTR", "Spatial unit information", None))
        self.frmWizSpatialUnit.setSubTitle(_translate("frmNewSTR", "Select the land or building information.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("frmNewSTR", "Add Spatial Unit", None))
        self.gpOpenLayers.setTitle(_translate("frmNewSTR", "Preview Spatial Unit:", None))
        self.groupBox_2.setTitle(_translate("frmNewSTR", "Choose Base Layer", None))
        self.rbOSM.setText(_translate("frmNewSTR", "Open Street Maps", None))
        self.rbGMaps.setText(_translate("frmNewSTR", "Google Maps", None))
        self.label_7.setText(_translate("frmNewSTR", "Zoom", None))
        self.label_9.setText(_translate("frmNewSTR", "+", None))
        self.btnResetMap.setText(_translate("frmNewSTR", "Reset Map", None))
        self.label_8.setText(_translate("frmNewSTR", "-", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("frmNewSTR", "Preview Spatial Unit", None))
        self.frmWizSTRType.setTitle(_translate("frmNewSTR", "Social Tenure Relationship Type", None))
        self.frmWizSTRType.setSubTitle(_translate("frmNewSTR", "Select the type of relationship that the specified person has with the selected spatial unit.", None))
        self.label_2.setText(_translate("frmNewSTR", "Choose the social tenure type from the first column by clicking on the cell.", None))
        self.frmWizSourceDocs.setTitle(_translate("frmNewSTR", "Supporting Documents", None))
        self.frmWizSourceDocs.setSubTitle(_translate("frmNewSTR", "Upload one or more documents for each document types by selecting a document type from the drop down menu and by clicking on Add Supporting Document button.", None))
        self.btnAddDocument.setText(_translate("frmNewSTR", "Add Supporting Document", None))
        self.label_4.setText(_translate("frmNewSTR", "Document Type", None))
        self.frmSTRSummary.setTitle(_translate("frmNewSTR", "STR Definition Summary", None))
        self.frmSTRSummary.setSubTitle(_translate("frmNewSTR", "A new social tenure relationship will be created based on the information that you have supplied, as summarized below.", None))
        self.label_18.setText(_translate("frmNewSTR", "If you want to review or change any selections, click Back. If you are satisified with the selections, click Finish.", None))

from PyQt4 import QtWebKit
from stdm import resources_rc
