# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_table_property.ui'
#
# Created: Mon Jun  9 20:50:20 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TableProperty(object):
    def setupUi(self, TableProperty):
        TableProperty.setObjectName(_fromUtf8("TableProperty"))
        TableProperty.resize(400, 494)
        self.gridLayout_3 = QtGui.QGridLayout(TableProperty)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gpRelation = QtGui.QGroupBox(TableProperty)
        self.gpRelation.setObjectName(_fromUtf8("gpRelation"))
        self.gridLayout = QtGui.QGridLayout(self.gpRelation)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label = QtGui.QLabel(self.gpRelation)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gpRelation)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.cboDelAct = QtGui.QComboBox(self.gpRelation)
        self.cboDelAct.setObjectName(_fromUtf8("cboDelAct"))
        self.gridLayout.addWidget(self.cboDelAct, 4, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.gpRelation)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.cboTable = QtGui.QComboBox(self.gpRelation)
        self.cboTable.setObjectName(_fromUtf8("cboTable"))
        self.gridLayout.addWidget(self.cboTable, 1, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.gpRelation)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.gpRelation)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.cboUpAct = QtGui.QComboBox(self.gpRelation)
        self.cboUpAct.setObjectName(_fromUtf8("cboUpAct"))
        self.gridLayout.addWidget(self.cboUpAct, 5, 1, 1, 1)
        self.cboColumn = QtGui.QComboBox(self.gpRelation)
        self.cboColumn.setObjectName(_fromUtf8("cboColumn"))
        self.gridLayout.addWidget(self.cboColumn, 3, 1, 1, 1)
        self.txtName = QtGui.QLineEdit(self.gpRelation)
        self.txtName.setObjectName(_fromUtf8("txtName"))
        self.gridLayout.addWidget(self.txtName, 0, 1, 1, 1)
        self.cboRefCol = QtGui.QComboBox(self.gpRelation)
        self.cboRefCol.setObjectName(_fromUtf8("cboRefCol"))
        self.gridLayout.addWidget(self.cboRefCol, 2, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.gpRelation)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout.addWidget(self.label_11, 2, 0, 1, 1)
        self.gridLayout_3.addWidget(self.gpRelation, 1, 0, 2, 2)
        self.gpConstraint = QtGui.QGroupBox(TableProperty)
        self.gpConstraint.setObjectName(_fromUtf8("gpConstraint"))
        self.gridLayout_5 = QtGui.QGridLayout(self.gpConstraint)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.label_6 = QtGui.QLabel(self.gpConstraint)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_5.addWidget(self.label_6, 0, 0, 1, 1)
        self.cboType = QtGui.QComboBox(self.gpConstraint)
        self.cboType.setObjectName(_fromUtf8("cboType"))
        self.gridLayout_5.addWidget(self.cboType, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gpConstraint)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.gpConstraint)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_5.addWidget(self.label_10, 2, 0, 1, 1)
        self.cboTable_2 = QtGui.QComboBox(self.gpConstraint)
        self.cboTable_2.setObjectName(_fromUtf8("cboTable_2"))
        self.gridLayout_5.addWidget(self.cboTable_2, 2, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.gpConstraint)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_5.addWidget(self.label_9, 3, 0, 1, 1)
        self.cboColumn_2 = QtGui.QComboBox(self.gpConstraint)
        self.cboColumn_2.setObjectName(_fromUtf8("cboColumn_2"))
        self.gridLayout_5.addWidget(self.cboColumn_2, 3, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.gpConstraint)
        self.label_8.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_5.addWidget(self.label_8, 4, 0, 1, 1)
        self.frame = QtGui.QFrame(self.gpConstraint)
        self.frame.setMaximumSize(QtCore.QSize(16777215, 210))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.txtConstraint = QtGui.QTextEdit(self.frame)
        self.txtConstraint.setMaximumSize(QtCore.QSize(16777215, 200))
        self.txtConstraint.setObjectName(_fromUtf8("txtConstraint"))
        self.gridLayout_2.addWidget(self.txtConstraint, 0, 0, 1, 1)
        self.gridLayout_5.addWidget(self.frame, 4, 1, 1, 1)
        self.txtType = QtGui.QLineEdit(self.gpConstraint)
        self.txtType.setObjectName(_fromUtf8("txtType"))
        self.gridLayout_5.addWidget(self.txtType, 1, 1, 1, 1)
        self.gridLayout_3.addWidget(self.gpConstraint, 4, 0, 1, 2)
        self.groupBox_2 = QtGui.QGroupBox(TableProperty)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.rbRelation = QtGui.QRadioButton(self.groupBox_2)
        self.rbRelation.setChecked(True)
        self.rbRelation.setObjectName(_fromUtf8("rbRelation"))
        self.gridLayout_4.addWidget(self.rbRelation, 0, 0, 1, 1)
        self.rbConstrain = QtGui.QRadioButton(self.groupBox_2)
        self.rbConstrain.setObjectName(_fromUtf8("rbConstrain"))
        self.gridLayout_4.addWidget(self.rbConstrain, 0, 1, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_2, 0, 0, 1, 2)
        self.buttonBox = QtGui.QDialogButtonBox(TableProperty)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout_3.addWidget(self.buttonBox, 5, 0, 1, 1)

        self.retranslateUi(TableProperty)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TableProperty.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TableProperty.reject)
        QtCore.QMetaObject.connectSlotsByName(TableProperty)

    def retranslateUi(self, TableProperty):
        TableProperty.setWindowTitle(_translate("TableProperty", "Table Properties", None))
        self.gpRelation.setTitle(_translate("TableProperty", "Add relation", None))
        self.label.setText(_translate("TableProperty", "Relation name", None))
        self.label_5.setText(_translate("TableProperty", "On Update action", None))
        self.label_4.setText(_translate("TableProperty", "On Delete action", None))
        self.label_2.setText(_translate("TableProperty", "Reference table", None))
        self.label_3.setText(_translate("TableProperty", "Referenced column", None))
        self.label_11.setText(_translate("TableProperty", "Local Column", None))
        self.gpConstraint.setTitle(_translate("TableProperty", "Add Table Constraint", None))
        self.label_6.setText(_translate("TableProperty", "Constraint type", None))
        self.label_7.setText(_translate("TableProperty", "Constraint name", None))
        self.label_10.setText(_translate("TableProperty", "Table", None))
        self.label_9.setText(_translate("TableProperty", "Column", None))
        self.label_8.setText(_translate("TableProperty", "Definition", None))
        self.groupBox_2.setTitle(_translate("TableProperty", "Constraint type", None))
        self.rbRelation.setText(_translate("TableProperty", "Add relation", None))
        self.rbConstrain.setText(_translate("TableProperty", "Add constraint", None))

