# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_workspace_config.ui'
#
# Created: Mon Jun 29 23:57:34 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_STDMWizard(object):
    def setupUi(self, STDMWizard):
        STDMWizard.setObjectName(_fromUtf8("STDMWizard"))
        STDMWizard.resize(827, 591)
        STDMWizard.setWizardStyle(QtGui.QWizard.ModernStyle)
        self.wizardPage1 = QtGui.QWizardPage()
        self.wizardPage1.setStyleSheet(_fromUtf8("background-image: url(:/plugins/stdm/res/image1.png);"))
        self.wizardPage1.setObjectName(_fromUtf8("wizardPage1"))
        self.label_2 = QtGui.QLabel(self.wizardPage1)
        self.label_2.setGeometry(QtCore.QRect(0, 10, 771, 441))
        self.label_2.setMinimumSize(QtCore.QSize(400, 0))
        self.label_2.setText(_fromUtf8(""))
        self.label_2.setPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/QGIS Splash.png")))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        STDMWizard.addPage(self.wizardPage1)
        self.wizardPage2 = QtGui.QWizardPage()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.wizardPage2.setFont(font)
        self.wizardPage2.setObjectName(_fromUtf8("wizardPage2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.wizardPage2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_16 = QtGui.QGroupBox(self.wizardPage2)
        self.groupBox_16.setObjectName(_fromUtf8("groupBox_16"))
        self.gridLayout_20 = QtGui.QGridLayout(self.groupBox_16)
        self.gridLayout_20.setObjectName(_fromUtf8("gridLayout_20"))
        self.rbAccpt = QtGui.QRadioButton(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.rbAccpt.setFont(font)
        self.rbAccpt.setChecked(False)
        self.rbAccpt.setObjectName(_fromUtf8("rbAccpt"))
        self.gridLayout_20.addWidget(self.rbAccpt, 2, 0, 1, 1)
        self.rbReject = QtGui.QRadioButton(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.rbReject.setFont(font)
        self.rbReject.setCheckable(True)
        self.rbReject.setChecked(False)
        self.rbReject.setObjectName(_fromUtf8("rbReject"))
        self.gridLayout_20.addWidget(self.rbReject, 2, 1, 1, 1)
        self.txtLicense = QtGui.QTextEdit(self.groupBox_16)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.txtLicense.setFont(font)
        self.txtLicense.setFrameShape(QtGui.QFrame.NoFrame)
        self.txtLicense.setFrameShadow(QtGui.QFrame.Raised)
        self.txtLicense.setObjectName(_fromUtf8("txtLicense"))
        self.gridLayout_20.addWidget(self.txtLicense, 1, 0, 1, 2)
        self.gridLayout_2.addWidget(self.groupBox_16, 0, 0, 1, 1)
        STDMWizard.addPage(self.wizardPage2)
        self.wizardPage = QtGui.QWizardPage()
        self.wizardPage.setObjectName(_fromUtf8("wizardPage"))
        self.gridLayout_27 = QtGui.QGridLayout(self.wizardPage)
        self.gridLayout_27.setObjectName(_fromUtf8("gridLayout_27"))
        self.groupBox_15 = QtGui.QGroupBox(self.wizardPage)
        self.groupBox_15.setMinimumSize(QtCore.QSize(0, 400))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.groupBox_15.setFont(font)
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_15)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.widget_4 = QtGui.QWidget(self.groupBox_15)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.gridLayout_22 = QtGui.QGridLayout(self.widget_4)
        self.gridLayout_22.setMargin(0)
        self.gridLayout_22.setObjectName(_fromUtf8("gridLayout_22"))
        self.txtDefaultFolder = QtGui.QLineEdit(self.widget_4)
        self.txtDefaultFolder.setMinimumSize(QtCore.QSize(0, 30))
        self.txtDefaultFolder.setReadOnly(True)
        self.txtDefaultFolder.setObjectName(_fromUtf8("txtDefaultFolder"))
        self.gridLayout_22.addWidget(self.txtDefaultFolder, 1, 1, 1, 1)
        self.btnBrowse = QtGui.QPushButton(self.widget_4)
        self.btnBrowse.setMinimumSize(QtCore.QSize(0, 30))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/open_file.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBrowse.setIcon(icon)
        self.btnBrowse.setObjectName(_fromUtf8("btnBrowse"))
        self.gridLayout_22.addWidget(self.btnBrowse, 1, 2, 1, 1)
        self.label_37 = QtGui.QLabel(self.widget_4)
        self.label_37.setMinimumSize(QtCore.QSize(200, 30))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_22.addWidget(self.label_37, 1, 0, 1, 1)
        self.btnBrowse2_2 = QtGui.QPushButton(self.widget_4)
        self.btnBrowse2_2.setMinimumSize(QtCore.QSize(0, 30))
        self.btnBrowse2_2.setIcon(icon)
        self.btnBrowse2_2.setObjectName(_fromUtf8("btnBrowse2_2"))
        self.gridLayout_22.addWidget(self.btnBrowse2_2, 0, 2, 1, 1)
        self.txtSetting = QtGui.QLineEdit(self.widget_4)
        self.txtSetting.setMinimumSize(QtCore.QSize(0, 30))
        self.txtSetting.setReadOnly(True)
        self.txtSetting.setObjectName(_fromUtf8("txtSetting"))
        self.gridLayout_22.addWidget(self.txtSetting, 0, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self.widget_4)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_22.addWidget(self.label_39, 0, 0, 1, 1)
        self.btnBrowse2 = QtGui.QPushButton(self.widget_4)
        self.btnBrowse2.setMinimumSize(QtCore.QSize(0, 30))
        self.btnBrowse2.setIcon(icon)
        self.btnBrowse2.setObjectName(_fromUtf8("btnBrowse2"))
        self.gridLayout_22.addWidget(self.btnBrowse2, 2, 2, 1, 1)
        self.label_31 = QtGui.QLabel(self.widget_4)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.gridLayout_22.addWidget(self.label_31, 2, 0, 1, 1)
        self.txtCertFolder = QtGui.QLineEdit(self.widget_4)
        self.txtCertFolder.setMinimumSize(QtCore.QSize(0, 30))
        self.txtCertFolder.setReadOnly(True)
        self.txtCertFolder.setObjectName(_fromUtf8("txtCertFolder"))
        self.gridLayout_22.addWidget(self.txtCertFolder, 2, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.widget_4)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_22.addWidget(self.label_4, 3, 0, 1, 1)
        self.txtTemplates = QtGui.QLineEdit(self.widget_4)
        self.txtTemplates.setMinimumSize(QtCore.QSize(0, 30))
        self.txtTemplates.setObjectName(_fromUtf8("txtTemplates"))
        self.gridLayout_22.addWidget(self.txtTemplates, 3, 1, 1, 1)
        self.btnTemplates = QtGui.QPushButton(self.widget_4)
        self.btnTemplates.setMinimumSize(QtCore.QSize(0, 30))
        self.btnTemplates.setIcon(icon)
        self.btnTemplates.setObjectName(_fromUtf8("btnTemplates"))
        self.gridLayout_22.addWidget(self.btnTemplates, 3, 2, 1, 1)
        self.gridLayout_3.addWidget(self.widget_4, 0, 0, 1, 1)
        self.gridLayout_27.addWidget(self.groupBox_15, 0, 0, 1, 1)
        STDMWizard.addPage(self.wizardPage)
        self.wizardPage_6 = QtGui.QWizardPage()
        self.wizardPage_6.setObjectName(_fromUtf8("wizardPage_6"))
        self.gridLayout_26 = QtGui.QGridLayout(self.wizardPage_6)
        self.gridLayout_26.setObjectName(_fromUtf8("gridLayout_26"))
        self.groupBox_17 = QtGui.QGroupBox(self.wizardPage_6)
        self.groupBox_17.setObjectName(_fromUtf8("groupBox_17"))
        self.gridLayout_28 = QtGui.QGridLayout(self.groupBox_17)
        self.gridLayout_28.setObjectName(_fromUtf8("gridLayout_28"))
        self.cboProfile = QtGui.QComboBox(self.groupBox_17)
        self.cboProfile.setMinimumSize(QtCore.QSize(180, 30))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.cboProfile.setFont(font)
        self.cboProfile.setObjectName(_fromUtf8("cboProfile"))
        self.gridLayout_28.addWidget(self.cboProfile, 0, 2, 1, 1)
        self.label_3 = QtGui.QLabel(self.groupBox_17)
        self.label_3.setStyleSheet(_fromUtf8("font: 75 10pt \"Myriad Web Pro\";"))
        self.label_3.setFrameShape(QtGui.QFrame.Box)
        self.label_3.setScaledContents(True)
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_28.addWidget(self.label_3, 0, 0, 3, 1)
        self.label = QtGui.QLabel(self.groupBox_17)
        self.label.setMinimumSize(QtCore.QSize(50, 0))
        self.label.setMaximumSize(QtCore.QSize(30, 16777215))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_28.addWidget(self.label, 0, 1, 1, 1)
        self.widget = QtGui.QWidget(self.groupBox_17)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_24 = QtGui.QGridLayout(self.widget)
        self.gridLayout_24.setMargin(0)
        self.gridLayout_24.setObjectName(_fromUtf8("gridLayout_24"))
        self.btnNewP = QtGui.QPushButton(self.widget)
        self.btnNewP.setMinimumSize(QtCore.QSize(0, 30))
        self.btnNewP.setMaximumSize(QtCore.QSize(150, 16777215))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/property_manager.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNewP.setIcon(icon1)
        self.btnNewP.setObjectName(_fromUtf8("btnNewP"))
        self.gridLayout_24.addWidget(self.btnNewP, 1, 0, 1, 1)
        self.btnPDelete = QtGui.QPushButton(self.widget)
        self.btnPDelete.setMinimumSize(QtCore.QSize(25, 30))
        self.btnPDelete.setMaximumSize(QtCore.QSize(150, 16777215))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/remove.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnPDelete.setIcon(icon2)
        self.btnPDelete.setObjectName(_fromUtf8("btnPDelete"))
        self.gridLayout_24.addWidget(self.btnPDelete, 1, 5, 1, 1)
        self.lblDescprition = QtGui.QLabel(self.widget)
        self.lblDescprition.setStyleSheet(_fromUtf8("color: rgb(0, 85, 0);"))
        self.lblDescprition.setObjectName(_fromUtf8("lblDescprition"))
        self.gridLayout_24.addWidget(self.lblDescprition, 0, 0, 1, 2)
        self.gridLayout_28.addWidget(self.widget, 2, 1, 1, 2)
        self.gridLayout_26.addWidget(self.groupBox_17, 0, 0, 1, 2)
        self.groupBox_18 = QtGui.QGroupBox(self.wizardPage_6)
        self.groupBox_18.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_18.setStyleSheet(_fromUtf8("font: 75 9pt \"Myriad Web Pro\";"))
        self.groupBox_18.setObjectName(_fromUtf8("groupBox_18"))
        self.gridLayout_25 = QtGui.QGridLayout(self.groupBox_18)
        self.gridLayout_25.setObjectName(_fromUtf8("gridLayout_25"))
        self.groupBox_19 = QtGui.QGroupBox(self.groupBox_18)
        self.groupBox_19.setMaximumSize(QtCore.QSize(400, 16777215))
        self.groupBox_19.setFlat(True)
        self.groupBox_19.setObjectName(_fromUtf8("groupBox_19"))
        self.gridLayout_29 = QtGui.QGridLayout(self.groupBox_19)
        self.gridLayout_29.setObjectName(_fromUtf8("gridLayout_29"))
        self.btnNew_2 = QtGui.QPushButton(self.groupBox_19)
        self.btnNew_2.setMinimumSize(QtCore.QSize(70, 30))
        self.btnNew_2.setMaximumSize(QtCore.QSize(55, 16777215))
        self.btnNew_2.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/edit.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNew_2.setIcon(icon3)
        self.btnNew_2.setObjectName(_fromUtf8("btnNew_2"))
        self.gridLayout_29.addWidget(self.btnNew_2, 2, 2, 1, 1)
        self.btnNew = QtGui.QPushButton(self.groupBox_19)
        self.btnNew.setMinimumSize(QtCore.QSize(70, 30))
        self.btnNew.setMaximumSize(QtCore.QSize(55, 16777215))
        self.btnNew.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/add.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnNew.setIcon(icon4)
        self.btnNew.setObjectName(_fromUtf8("btnNew"))
        self.gridLayout_29.addWidget(self.btnNew, 0, 2, 1, 1)
        self.btnDelete = QtGui.QPushButton(self.groupBox_19)
        self.btnDelete.setMinimumSize(QtCore.QSize(70, 30))
        self.btnDelete.setMaximumSize(QtCore.QSize(55, 16777215))
        self.btnDelete.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/stdm/images/icons/delete.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnDelete.setIcon(icon5)
        self.btnDelete.setObjectName(_fromUtf8("btnDelete"))
        self.gridLayout_29.addWidget(self.btnDelete, 3, 2, 1, 1)
        self.gridLayout_25.addWidget(self.groupBox_19, 0, 1, 1, 1)
        self.pftableView = QtGui.QTableView(self.groupBox_18)
        self.pftableView.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.pftableView.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.pftableView.setObjectName(_fromUtf8("pftableView"))
        self.pftableView.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_25.addWidget(self.pftableView, 0, 0, 1, 1)
        self.gridLayout_26.addWidget(self.groupBox_18, 2, 0, 1, 2)
        STDMWizard.addPage(self.wizardPage_6)
        self.wizardPage_3 = QtGui.QWizardPage()
        self.wizardPage_3.setObjectName(_fromUtf8("wizardPage_3"))
        self.gridLayout_30 = QtGui.QGridLayout(self.wizardPage_3)
        self.gridLayout_30.setObjectName(_fromUtf8("gridLayout_30"))
        self.tbSTR = QtGui.QTabWidget(self.wizardPage_3)
        self.tbSTR.setObjectName(_fromUtf8("tbSTR"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_6 = QtGui.QGridLayout(self.frame)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.lstEntity = QtGui.QListView(self.frame)
        self.lstEntity.setMinimumSize(QtCore.QSize(150, 0))
        self.lstEntity.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lstEntity.setObjectName(_fromUtf8("lstEntity"))
        self.gridLayout_6.addWidget(self.lstEntity, 0, 0, 1, 2)
        self.gridLayout_8.addWidget(self.frame, 0, 0, 1, 1)
        self.tabWidget_2 = QtGui.QTabWidget(self.tab)
        self.tabWidget_2.setMinimumSize(QtCore.QSize(500, 0))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_16 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.tblEdit = QtGui.QTableView(self.tab_3)
        self.tblEdit.setMinimumSize(QtCore.QSize(400, 0))
        self.tblEdit.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblEdit.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblEdit.setObjectName(_fromUtf8("tblEdit"))
        self.tblEdit.horizontalHeader().setStretchLastSection(True)
        self.gridLayout_16.addWidget(self.tblEdit, 0, 0, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.tab_3)
        self.groupBox_8.setFlat(True)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.btnDel = QtGui.QPushButton(self.groupBox_8)
        self.btnDel.setMaximumSize(QtCore.QSize(50, 40))
        self.btnDel.setText(_fromUtf8(""))
        self.btnDel.setIcon(icon5)
        self.btnDel.setObjectName(_fromUtf8("btnDel"))
        self.gridLayout_12.addWidget(self.btnDel, 2, 2, 1, 1)
        self.btnAdd = QtGui.QPushButton(self.groupBox_8)
        self.btnAdd.setMaximumSize(QtCore.QSize(50, 40))
        self.btnAdd.setText(_fromUtf8(""))
        self.btnAdd.setIcon(icon4)
        self.btnAdd.setIconSize(QtCore.QSize(20, 20))
        self.btnAdd.setObjectName(_fromUtf8("btnAdd"))
        self.gridLayout_12.addWidget(self.btnAdd, 0, 2, 1, 1)
        self.btnEdit = QtGui.QPushButton(self.groupBox_8)
        self.btnEdit.setMaximumSize(QtCore.QSize(50, 40))
        self.btnEdit.setText(_fromUtf8(""))
        self.btnEdit.setIcon(icon3)
        self.btnEdit.setIconSize(QtCore.QSize(20, 20))
        self.btnEdit.setObjectName(_fromUtf8("btnEdit"))
        self.gridLayout_12.addWidget(self.btnEdit, 1, 2, 1, 1)
        self.gridLayout_16.addWidget(self.groupBox_8, 0, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tblLookup_2 = QtGui.QTableView(self.tab_4)
        self.tblLookup_2.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblLookup_2.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblLookup_2.setObjectName(_fromUtf8("tblLookup_2"))
        self.gridLayout_9.addWidget(self.tblLookup_2, 0, 0, 1, 1)
        self.groupBox_12 = QtGui.QGroupBox(self.tab_4)
        self.groupBox_12.setFlat(True)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.gridLayout_17 = QtGui.QGridLayout(self.groupBox_12)
        self.gridLayout_17.setObjectName(_fromUtf8("gridLayout_17"))
        self.btnGeomDel = QtGui.QPushButton(self.groupBox_12)
        self.btnGeomDel.setMaximumSize(QtCore.QSize(45, 30))
        self.btnGeomDel.setText(_fromUtf8(""))
        self.btnGeomDel.setIcon(icon5)
        self.btnGeomDel.setObjectName(_fromUtf8("btnGeomDel"))
        self.gridLayout_17.addWidget(self.btnGeomDel, 1, 2, 1, 1)
        self.btnGeomEdit = QtGui.QPushButton(self.groupBox_12)
        self.btnGeomEdit.setMaximumSize(QtCore.QSize(45, 30))
        self.btnGeomEdit.setText(_fromUtf8(""))
        self.btnGeomEdit.setIcon(icon3)
        self.btnGeomEdit.setIconSize(QtCore.QSize(20, 20))
        self.btnGeomEdit.setObjectName(_fromUtf8("btnGeomEdit"))
        self.gridLayout_17.addWidget(self.btnGeomEdit, 0, 2, 1, 1)
        self.gridLayout_9.addWidget(self.groupBox_12, 0, 1, 1, 1)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout_8.addWidget(self.tabWidget_2, 0, 1, 1, 1)
        self.frame_5 = QtGui.QFrame(self.tab)
        self.frame_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.gridLayout_7 = QtGui.QGridLayout(self.frame_5)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.tblLookupList = QtGui.QTreeView(self.frame_5)
        self.tblLookupList.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tblLookupList.setItemsExpandable(False)
        self.tblLookupList.setObjectName(_fromUtf8("tblLookupList"))
        self.gridLayout_7.addWidget(self.tblLookupList, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.frame_5, 1, 0, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.tab)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox_7)
        self.groupBox_2.setFlat(True)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.btnAddLk = QtGui.QPushButton(self.groupBox_2)
        self.btnAddLk.setMinimumSize(QtCore.QSize(0, 30))
        self.btnAddLk.setMaximumSize(QtCore.QSize(45, 30))
        self.btnAddLk.setText(_fromUtf8(""))
        self.btnAddLk.setIcon(icon4)
        self.btnAddLk.setObjectName(_fromUtf8("btnAddLk"))
        self.gridLayout_4.addWidget(self.btnAddLk, 0, 1, 1, 1)
        self.btnLkDel = QtGui.QPushButton(self.groupBox_2)
        self.btnLkDel.setMinimumSize(QtCore.QSize(0, 30))
        self.btnLkDel.setMaximumSize(QtCore.QSize(45, 16777215))
        self.btnLkDel.setText(_fromUtf8(""))
        self.btnLkDel.setIcon(icon5)
        self.btnLkDel.setObjectName(_fromUtf8("btnLkDel"))
        self.gridLayout_4.addWidget(self.btnLkDel, 1, 1, 1, 1)
        self.gridLayout_11.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.tblLookup = QtGui.QListView(self.groupBox_7)
        self.tblLookup.setObjectName(_fromUtf8("tblLookup"))
        self.gridLayout_11.addWidget(self.tblLookup, 0, 0, 1, 1)
        self.gridLayout_8.addWidget(self.groupBox_7, 1, 1, 1, 1)
        self.tbSTR.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout = QtGui.QGridLayout(self.tab_2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_9 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_9.setMaximumSize(QtCore.QSize(16777215, 1000))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.gridLayout_15 = QtGui.QGridLayout(self.groupBox_9)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.lstEntity_2 = QtGui.QListView(self.groupBox_9)
        self.lstEntity_2.setMinimumSize(QtCore.QSize(150, 0))
        self.lstEntity_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lstEntity_2.setObjectName(_fromUtf8("lstEntity_2"))
        self.gridLayout_15.addWidget(self.lstEntity_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_9, 0, 0, 1, 1)
        self.groupBox_10 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_10.setMinimumSize(QtCore.QSize(550, 0))
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_14 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.groupBox_13 = QtGui.QGroupBox(self.groupBox_10)
        self.groupBox_13.setFlat(True)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.gridLayout_19 = QtGui.QGridLayout(self.groupBox_13)
        self.gridLayout_19.setObjectName(_fromUtf8("gridLayout_19"))
        self.btnPropDel = QtGui.QPushButton(self.groupBox_13)
        self.btnPropDel.setMaximumSize(QtCore.QSize(50, 40))
        self.btnPropDel.setText(_fromUtf8(""))
        self.btnPropDel.setIcon(icon5)
        self.btnPropDel.setObjectName(_fromUtf8("btnPropDel"))
        self.gridLayout_19.addWidget(self.btnPropDel, 0, 4, 1, 1)
        self.btnProperty = QtGui.QPushButton(self.groupBox_13)
        self.btnProperty.setMaximumSize(QtCore.QSize(50, 40))
        self.btnProperty.setText(_fromUtf8(""))
        self.btnProperty.setIcon(icon4)
        self.btnProperty.setIconSize(QtCore.QSize(20, 20))
        self.btnProperty.setObjectName(_fromUtf8("btnProperty"))
        self.gridLayout_19.addWidget(self.btnProperty, 0, 2, 1, 1)
        self.pushButton = QtGui.QPushButton(self.groupBox_13)
        self.pushButton.setMaximumSize(QtCore.QSize(45, 30))
        self.pushButton.setText(_fromUtf8(""))
        self.pushButton.setIcon(icon3)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.gridLayout_19.addWidget(self.pushButton, 0, 3, 1, 1)
        self.gridLayout_14.addWidget(self.groupBox_13, 1, 0, 1, 1)
        self.tblEdit_2 = QtGui.QTableView(self.groupBox_10)
        self.tblEdit_2.setMinimumSize(QtCore.QSize(0, 0))
        self.tblEdit_2.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.tblEdit_2.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.tblEdit_2.setObjectName(_fromUtf8("tblEdit_2"))
        self.gridLayout_14.addWidget(self.tblEdit_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_10, 0, 1, 1, 1)
        self.tbSTR.addTab(self.tab_2, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.gridLayout_23 = QtGui.QGridLayout(self.tab_5)
        self.gridLayout_23.setObjectName(_fromUtf8("gridLayout_23"))
        self.groupBox = QtGui.QGroupBox(self.tab_5)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(200, 16777215))
        self.groupBox.setFlat(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.lstParty = QtGui.QListView(self.groupBox)
        self.lstParty.setMinimumSize(QtCore.QSize(300, 0))
        self.lstParty.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lstParty.setObjectName(_fromUtf8("lstParty"))
        self.gridLayout_13.addWidget(self.lstParty, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_11 = QtGui.QGroupBox(self.tab_5)
        self.groupBox_11.setFlat(True)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.gridLayout_31 = QtGui.QGridLayout(self.groupBox_11)
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        self.lstTableCol = QtGui.QListView(self.groupBox_11)
        self.lstTableCol.setMinimumSize(QtCore.QSize(200, 0))
        self.lstTableCol.setObjectName(_fromUtf8("lstTableCol"))
        self.gridLayout_31.addWidget(self.lstTableCol, 0, 0, 1, 1)
        self.gridLayout_23.addWidget(self.groupBox_11, 0, 1, 1, 1)
        self.tbSTR.addTab(self.tab_5, _fromUtf8(""))
        self.gridLayout_30.addWidget(self.tbSTR, 0, 0, 1, 1)
        STDMWizard.addPage(self.wizardPage_3)
        self.wizardPage_4 = QtGui.QWizardPage()
        self.wizardPage_4.setObjectName(_fromUtf8("wizardPage_4"))
        self.gridLayout_10 = QtGui.QGridLayout(self.wizardPage_4)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.scrollArea = QtGui.QScrollArea(self.wizardPage_4)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName(_fromUtf8("scrollArea"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 659, 136))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.gridLayout_21 = QtGui.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_21.setObjectName(_fromUtf8("gridLayout_21"))
        self.txtHtml = QtGui.QTextEdit(self.scrollAreaWidgetContents)
        self.txtHtml.setObjectName(_fromUtf8("txtHtml"))
        self.gridLayout_21.addWidget(self.txtHtml, 1, 0, 1, 1)
        self.frame1 = QtGui.QFrame(self.scrollAreaWidgetContents)
        self.frame1.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame1.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame1.setFrameShadow(QtGui.QFrame.Raised)
        self.frame1.setObjectName(_fromUtf8("frame1"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame1)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.rbSchema = QtGui.QRadioButton(self.frame1)
        self.rbSchema.setObjectName(_fromUtf8("rbSchema"))
        self.gridLayout_5.addWidget(self.rbSchema, 1, 1, 1, 1)
        self.rbSchemaNew = QtGui.QRadioButton(self.frame1)
        self.rbSchemaNew.setObjectName(_fromUtf8("rbSchemaNew"))
        self.gridLayout_5.addWidget(self.rbSchemaNew, 1, 0, 1, 1)
        self.btnSQL = QtGui.QPushButton(self.frame1)
        self.btnSQL.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnSQL.setCheckable(False)
        self.btnSQL.setAutoRepeat(False)
        self.btnSQL.setAutoExclusive(False)
        self.btnSQL.setAutoDefault(True)
        self.btnSQL.setDefault(False)
        self.btnSQL.setFlat(False)
        self.btnSQL.setObjectName(_fromUtf8("btnSQL"))
        self.gridLayout_5.addWidget(self.btnSQL, 1, 3, 1, 1)
        self.rbSkip = QtGui.QRadioButton(self.frame1)
        self.rbSkip.setObjectName(_fromUtf8("rbSkip"))
        self.gridLayout_5.addWidget(self.rbSkip, 1, 2, 1, 1)
        self.gridLayout_21.addWidget(self.frame1, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_10.addWidget(self.scrollArea, 0, 0, 1, 1)
        STDMWizard.addPage(self.wizardPage_4)

        self.retranslateUi(STDMWizard)
        self.tbSTR.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(STDMWizard)

    def retranslateUi(self, STDMWizard):
        STDMWizard.setWindowTitle(_translate("STDMWizard", "Wizard", None))
        self.wizardPage1.setTitle(_translate("STDMWizard", "Introduction", None))
        self.wizardPage1.setSubTitle(_translate("STDMWizard", "Welcome to STDM configuration wizard", None))
        self.wizardPage2.setTitle(_translate("STDMWizard", "End User License Agreement", None))
        self.wizardPage2.setSubTitle(_translate("STDMWizard", "Read carefully before you proceed", None))
        self.groupBox_16.setTitle(_translate("STDMWizard", "Terms and Conditions", None))
        self.rbAccpt.setText(_translate("STDMWizard", "I Agree", None))
        self.rbReject.setText(_translate("STDMWizard", "Decline", None))
        self.wizardPage.setTitle(_translate("STDMWizard", "Path Settings", None))
        self.wizardPage.setSubTitle(_translate("STDMWizard", "Set configuration and data directory path", None))
        self.groupBox_15.setTitle(_translate("STDMWizard", "Directory paths", None))
        self.btnBrowse.setText(_translate("STDMWizard", "Change", None))
        self.label_37.setText(_translate("STDMWizard", "Source document path", None))
        self.btnBrowse2_2.setText(_translate("STDMWizard", "Change", None))
        self.label_39.setText(_translate("STDMWizard", "Settings path", None))
        self.btnBrowse2.setText(_translate("STDMWizard", "Change", None))
        self.label_31.setText(_translate("STDMWizard", "Document output path", None))
        self.label_4.setText(_translate("STDMWizard", "Templates path", None))
        self.btnTemplates.setText(_translate("STDMWizard", "Change", None))
        self.wizardPage_6.setTitle(_translate("STDMWizard", "Profile Options", None))
        self.wizardPage_6.setSubTitle(_translate("STDMWizard", "Set/ Modify Data Collection Levels (Profiles)", None))
        self.groupBox_17.setTitle(_translate("STDMWizard", "Profiles", None))
        self.label_3.setText(_translate("STDMWizard", "A profile in STDM tool refers to a series of questions to be used in a particular survey in which order of questions and responses is organized in a modular format for easier analysis and presentation within STDM", None))
        self.label.setText(_translate("STDMWizard", "Select", None))
        self.btnNewP.setText(_translate("STDMWizard", "New Profile", None))
        self.btnPDelete.setText(_translate("STDMWizard", "Delete Selected ", None))
        self.lblDescprition.setText(_translate("STDMWizard", "Profile description", None))
        self.groupBox_18.setTitle(_translate("STDMWizard", "Profile modules/ tables ", None))
        self.groupBox_19.setTitle(_translate("STDMWizard", "Actions", None))
        self.wizardPage_3.setTitle(_translate("STDMWizard", "Data Forms customization", None))
        self.wizardPage_3.setSubTitle(_translate("STDMWizard", "Add or Edit Fields/ Columns For Each Module", None))
        self.groupBox_8.setTitle(_translate("STDMWizard", "Actions", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("STDMWizard", "Basic data types columns", None))
        self.groupBox_12.setTitle(_translate("STDMWizard", "Actions", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("STDMWizard", "Geometry columns", None))
        self.groupBox_7.setTitle(_translate("STDMWizard", "Lookup choices", None))
        self.groupBox_2.setTitle(_translate("STDMWizard", "Actions", None))
        self.tbSTR.setTabText(self.tbSTR.indexOf(self.tab), _translate("STDMWizard", "Tables", None))
        self.groupBox_9.setTitle(_translate("STDMWizard", "Table/ Entity ", None))
        self.groupBox_10.setTitle(_translate("STDMWizard", "Relations", None))
        self.groupBox_13.setTitle(_translate("STDMWizard", "Actions", None))
        self.tbSTR.setTabText(self.tbSTR.indexOf(self.tab_2), _translate("STDMWizard", "Table relation and constraint", None))
        self.groupBox.setTitle(_translate("STDMWizard", "Select tables participating in social Tenure Relation (STR)", None))
        self.groupBox_11.setTitle(_translate("STDMWizard", "List of column(s) from selected tables participating in STR", None))
        self.tbSTR.setTabText(self.tbSTR.indexOf(self.tab_5), _translate("STDMWizard", "Social Tenure Relation tables", None))
        self.wizardPage_4.setTitle(_translate("STDMWizard", "Update Database", None))
        self.wizardPage_4.setSubTitle(_translate("STDMWizard", "Commit SQL changes to the database", None))
        self.rbSchema.setText(_translate("STDMWizard", "Update existing STDM database", None))
        self.rbSchemaNew.setText(_translate("STDMWizard", "Create new STDM database", None))
        self.btnSQL.setText(_translate("STDMWizard", "Show generated SQL file", None))
        self.rbSkip.setText(_translate("STDMWizard", "Skip changes to database", None))

import resources_rc
