name: Tests

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  test-qgis:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .docker
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          submodules: 'true'
      - name: Launching docker-compose
        run: ./start.sh with-qgis
      - name: Running tests
        run: ./exec.sh